local ItemDefs = {}

function ItemDefs:DefineItems()
    items = {
        -- Ansem Reports
        {ID = 226, Name = "Secret Ansem's Report 1",  Type = "Report", Address = 0x36C4, Bitmask = 6},
        {ID = 227, Name = "Secret Ansem's Report 2",  Type = "Report", Address = 0x36C4, Bitmask = 7},
        {ID = 228, Name = "Secret Ansem's Report 3",  Type = "Report", Address = 0x36C5, Bitmask = 0},
        {ID = 229, Name = "Secret Ansem's Report 4",  Type = "Report", Address = 0x36C5, Bitmask = 1},
        {ID = 230, Name = "Secret Ansem's Report 5",  Type = "Report", Address = 0x36C5, Bitmask = 2},
        {ID = 231, Name = "Secret Ansem's Report 6",  Type = "Report", Address = 0x36C5, Bitmask = 3},
        {ID = 232, Name = "Secret Ansem's Report 7",  Type = "Report", Address = 0x36C5, Bitmask = 4},
        {ID = 233, Name = "Secret Ansem's Report 8",  Type = "Report", Address = 0x36C5, Bitmask = 5},
        {ID = 234, Name = "Secret Ansem's Report 9",  Type = "Report", Address = 0x36C5, Bitmask = 6},
        {ID = 235, Name = "Secret Ansem's Report 10", Type = "Report", Address = 0x36C5, Bitmask = 7},
        {ID = 236, Name = "Secret Ansem's Report 11", Type = "Report", Address = 0x36C6, Bitmask = 0},
        {ID = 237, Name = "Secret Ansem's Report 12", Type = "Report", Address = 0x36C6, Bitmask = 1},
        {ID = 238, Name = "Secret Ansem's Report 13", Type = "Report", Address = 0x36C6, Bitmask = 2},

        --Progression
        {ID = 593, Name = "Proof of Connection",      Type = "Progression", Address = 0x36B2},
        {ID = 594, Name = "Proof of Nonexistence",    Type = "Progression", Address = 0x36B3},
        {ID = 595, Name = "Proof of Peace",           Type = "Progression", Address = 0x36B4},
        {ID = 524, Name = "Promise Charm",            Type = "Progression", Address = 0x3694},
        {ID = 368, Name = "Namine Sketches",          Type = "Progression", Address = 0x3642},
        {ID = 460, Name = "Royal Summons",            Type = "Progression", Address = 0x365D}, --dummy 13
        {ID = 54,  Name = "Battlefields of War",      Type = "Progression", Address = 0x35AE},
        {ID = 55,  Name = "Sword of the Ancestor",    Type = "Progression", Address = 0x35AF},
        {ID = 59,  Name = "Beast's Claw",             Type = "Progression", Address = 0x35B3},
        {ID = 60,  Name = "Bone Fist",                Type = "Progression", Address = 0x35B4},
        {ID = 61,  Name = "Proud Fang",               Type = "Progression", Address = 0x35B5},
        {ID = 62,  Name = "Skill and Crossbones",     Type = "Progression", Address = 0x35B6},
        {ID = 72,  Name = "Scimitar",                 Type = "Progression", Address = 0x35C0},
        {ID = 369, Name = "Membership Card",          Type = "Progression", Address = 0x3643},
        {ID = 375, Name = "Ice Cream",                Type = "Progression", Address = 0x3649},
        {ID = 73,  Name = "Way to the Dawn",          Type = "Progression", Address = 0x35C1},
        {ID = 74,  Name = "Identity Disk",            Type = "Progression", Address = 0x35C2},
        {ID = 32,  Name = "Torn Page",                Type = "Progression", Address = 0x3598},

        --Forms
        {ID = 26,  Name = "Valor Form",               Type = "Form", Address = 0x36C0, Bitmask = 1},
        {ID = 27,  Name = "Wisdom Form",              Type = "Form", Address = 0x36C0, Bitmask = 2},
        {ID = 563, Name = "Limit Form",               Type = "Form", Address = 0x36CA, Bitmask = 3},
        {ID = 31,  Name = "Master Form",              Type = "Form", Address = 0x36C0, Bitmask = 6},
        {ID = 29,  Name = "Final Form",               Type = "Form", Address = 0x36C0, Bitmask = 4},
        {ID = 30,  Name = "Anti Form",                Type = "Form", Address = 0x36C0, Bitmask = 5},

        --Magic
        {ID = 21, Name = "Fire Element",              Type = "Magic", Address = 0x3594},
        {ID = 22, Name = "Blizzard Element",          Type = "Magic", Address = 0x3595},
        {ID = 23, Name = "Thunder Element",           Type = "Magic", Address = 0x3596},
        {ID = 24, Name = "Cure Element",              Type = "Magic", Address = 0x3597},
        {ID = 87, Name = "Magnet Element",            Type = "Magic", Address = 0x35CF},
        {ID = 88, Name = "Reflect Element",           Type = "Magic", Address = 0x35D0},

        --Summons
        {ID = 159,Name = "Genie",                     Type = "Summon", Address = 0x36C4, Bitmask = 4},
        {ID = 160,Name = "Peter Pan",                 Type = "Summon", Address = 0x36C4, Bitmask = 5},
        {ID = 25, Name = "Stitch",                    Type = "Summon", Address = 0x36C0, Bitmask = 0},
        {ID = 383,Name = "Chicken Little",            Type = "Summon", Address = 0x36C0, Bitmask = 3},

        --Keyblades
        {ID = 42,  Name = "Oathkeeper",               Type = "Keyblade", Address = 0x35A2},
        {ID = 43,  Name = "Oblivion",                 Type = "Keyblade", Address = 0x35A3},
        {ID = 480, Name = "Star Seeker",              Type = "Keyblade", Address = 0x367B},
        {ID = 481, Name = "Hidden Dragon",            Type = "Keyblade", Address = 0x367C},
        {ID = 484, Name = "Hero's Crest",             Type = "Keyblade", Address = 0x367F},
        {ID = 485, Name = "Monochrome",               Type = "Keyblade", Address = 0x3680},
        {ID = 486, Name = "Follow the Wind",          Type = "Keyblade", Address = 0x3681},
        {ID = 487, Name = "Circle of Life",           Type = "Keyblade", Address = 0x3682},
        {ID = 488, Name = "Photon Debugger",          Type = "Keyblade", Address = 0x3683},
        {ID = 489, Name = "Gull Wing",                Type = "Keyblade", Address = 0x3684},
        {ID = 490, Name = "Rumbling Rose",            Type = "Keyblade", Address = 0x3685},
        {ID = 491, Name = "Guardian Soul",            Type = "Keyblade", Address = 0x3686},
        {ID = 492, Name = "Wishing Lamp",             Type = "Keyblade", Address = 0x3687},
        {ID = 493, Name = "Decisive Pumpkin",         Type = "Keyblade", Address = 0x3688},
        {ID = 494, Name = "Sleeping Lion",            Type = "Keyblade", Address = 0x3689},
        {ID = 495, Name = "Sweet Memories",           Type = "Keyblade", Address = 0x368A},
        {ID = 496, Name = "Mysterious Abyss",         Type = "Keyblade", Address = 0x368B},
        {ID = 543, Name = "Two Become One",           Type = "Keyblade", Address = 0x3698},
        {ID = 497, Name = "Fatal Crest",              Type = "Keyblade", Address = 0x368C},
        {ID = 498, Name = "Bond of Flame",            Type = "Keyblade", Address = 0x368D},
        {ID = 499, Name = "Fenrir",                   Type = "Keyblade", Address = 0x368E},
        {ID = 500, Name = "Ultima Weapon",            Type = "Keyblade", Address = 0x368F},
        {ID = 544, Name = "Winner's Proof",           Type = "Keyblade", Address = 0x3699},
        {ID = 71,  Name = "Pureblood",                Type = "Keyblade", Address = 0x35BF},

        --Staves
        {ID = 546, Name = "Centurion+",               Type = "Staff", Address = 0x369B},
        {ID = 150, Name = "Meteor Staff",             Type = "Staff", Address = 0x35F1},
        {ID = 155, Name = "Nobody Lance",             Type = "Staff", Address = 0x35F6},
        {ID = 549, Name = "Precious Mushroom",        Type = "Staff", Address = 0x369E},
        {ID = 550, Name = "Precious Mushroom+",       Type = "Staff", Address = 0x369F},
        {ID = 551, Name = "Premium Mushroom",         Type = "Staff", Address = 0x36A0},
        {ID = 154, Name = "Rising Dragon",            Type = "Staff", Address = 0x35F5},
        {ID = 503, Name = "Save The Queen+",          Type = "Staff", Address = 0x3692},
        {ID = 156, Name = "Shaman's Relic",           Type = "Staff", Address = 0x35F7},

        --Shields
        {ID = 146, Name = "Akashic Record",           Type = "Shield", Address = 0x35ED},
        {ID = 553, Name = "Frozen Pride+",            Type = "Shield", Address = 0x36A2},
        {ID = 145, Name = "Genji Shield",             Type = "Shield", Address = 0x35EC},
        {ID = 556, Name = "Majestic Mushroom",        Type = "Shield", Address = 0x36A5},
        {ID = 557, Name = "Majestic Mushroom+",       Type = "Shield", Address = 0x36A6},
        {ID = 147, Name = "Nobody Guard",             Type = "Shield", Address = 0x35EE},
        {ID = 141, Name = "Ogre Shield",              Type = "Shield", Address = 0x35E8},
        {ID = 504, Name = "Save The King+",           Type = "Shield", Address = 0x3693},
        {ID = 558, Name = "Ultimate Mushroom",        Type = "Shield", Address = 0x36A7},

        --Accessories
        {ID = 8,   Name = "Ability Ring",             Type = "Accessories", Address = 0x3587},
        {ID = 9,   Name = "Engineer's Ring",          Type = "Accessories", Address = 0x3588},
        {ID = 10,  Name = "Technician's Ring",        Type = "Accessories", Address = 0x3589},
        {ID = 38,  Name = "Skill Ring",               Type = "Accessories", Address = 0x359F},
        {ID = 39,  Name = "Skillful Ring",            Type = "Accessories", Address = 0x35A0},
        {ID = 11,  Name = "Expert's Ring",            Type = "Accessories", Address = 0x358A},
        {ID = 34,  Name = "Master's Ring",            Type = "Accessories", Address = 0x359B},
        {ID = 52,  Name = "Cosmic Ring",              Type = "Accessories", Address = 0x35AD},
        {ID = 599, Name = "Executive's Ring",         Type = "Accessories", Address = 0x36B5},
        {ID = 12,  Name = "Sardonyx Ring",            Type = "Accessories", Address = 0x358B},
        {ID = 13,  Name = "Tourmaline Ring",          Type = "Accessories", Address = 0x358C},
        {ID = 14,  Name = "Aquamarine Ring",          Type = "Accessories", Address = 0x358D},
        {ID = 15,  Name = "Garnet Ring",              Type = "Accessories", Address = 0x358E},
        {ID = 16,  Name = "Diamond Ring",             Type = "Accessories", Address = 0x358F},
        {ID = 17,  Name = "Silver Ring",              Type = "Accessories", Address = 0x3590},
        {ID = 18,  Name = "Gold Ring",                Type = "Accessories", Address = 0x3591},
        {ID = 19,  Name = "Platinum Ring",            Type = "Accessories", Address = 0x3592},
        {ID = 20,  Name = "Mythril Ring",             Type = "Accessories", Address = 0x3593},
        {ID = 28,  Name = "Orichalcum Ring",          Type = "Accessories", Address = 0x359A},
        {ID = 40,  Name = "Soldier Earring",          Type = "Accessories", Address = 0x35A6},
        {ID = 46,  Name = "Fencer Earring",           Type = "Accessories", Address = 0x35A7},
        {ID = 47,  Name = "Mage Earring",             Type = "Accessories", Address = 0x35A8},
        {ID = 48,  Name = "Slayer Earring",           Type = "Accessories", Address = 0x35AC},
        {ID = 53,  Name = "Medal",                    Type = "Accessories", Address = 0x35B0},
        {ID = 35,  Name = "Moon Amulet",              Type = "Accessories", Address = 0x359C},
        {ID = 36,  Name = "Star Charm",               Type = "Accessories", Address = 0x359E},
        {ID = 56,  Name = "Cosmic Arts",              Type = "Accessories", Address = 0x35B1},
        {ID = 57,  Name = "Shadow Archive",           Type = "Accessories", Address = 0x35B2},
        {ID = 58,  Name = "Shadow Archive+",          Type = "Accessories", Address = 0x35B7},
        {ID = 64,  Name = "Full Bloom",               Type = "Accessories", Address = 0x35B9},
        {ID = 66,  Name = "Full Bloom+",              Type = "Accessories", Address = 0x35BB},
        {ID = 65,  Name = "Draw Ring",                Type = "Accessories", Address = 0x35BA},
        {ID = 63,  Name = "Lucky Ring",               Type = "Accessories", Address = 0x35B8},

        --Armor
        {ID = 67,  Name = "Elven Bandana",            Type = "Armor", Address = 0x35BC},
        {ID = 68,  Name = "Divine Bandana",           Type = "Armor", Address = 0x35BD},
        {ID = 78,  Name = "Protect Belt",             Type = "Armor", Address = 0x35C7},
        {ID = 79,  Name = "Gaia Belt",                Type = "Armor", Address = 0x35CA},
        {ID = 69,  Name = "Power Band",               Type = "Armor", Address = 0x35BE},
        {ID = 70,  Name = "Buster Band",              Type = "Armor", Address = 0x35C6},
        {ID = 111, Name = "Cosmic Belt",              Type = "Armor", Address = 0x35D1},
        {ID = 173, Name = "Fire Bangle",              Type = "Armor", Address = 0x35D7},
        {ID = 174, Name = "Fira Bangle",              Type = "Armor", Address = 0x35D8},
        {ID = 197, Name = "Firaga Bangle",            Type = "Armor", Address = 0x35D9},
        {ID = 284, Name = "Firagun Bangle",           Type = "Armor", Address = 0x35DA},
        {ID = 286, Name = "Blizzard Armlet",          Type = "Armor", Address = 0x35DC},
        {ID = 287, Name = "Blizzara Armlet",          Type = "Armor", Address = 0x35DD},
        {ID = 288, Name = "Blizzaga Armlet",          Type = "Armor", Address = 0x35DE},
        {ID = 289, Name = "Blizzagun Armlet",         Type = "Armor", Address = 0x35DF},
        {ID = 291, Name = "Thunder Trinket",          Type = "Armor", Address = 0x35E2},
        {ID = 292, Name = "Thundara Trinket",         Type = "Armor", Address = 0x35E3},
        {ID = 293, Name = "Thundaga Trinket",         Type = "Armor", Address = 0x35E4},
        {ID = 294, Name = "Thundagun Trinket",        Type = "Armor", Address = 0x35E5},
        {ID = 132, Name = "Shock Charm",              Type = "Armor", Address = 0x35D2},
        {ID = 133, Name = "Shock Charm+",             Type = "Armor", Address = 0x35D3},
        {ID = 296, Name = "Shadow Anklet",            Type = "Armor", Address = 0x35F9},
        {ID = 297, Name = "Dark Anklet",              Type = "Armor", Address = 0x35FB},
        {ID = 298, Name = "Midnight Anklet",          Type = "Armor", Address = 0x35FC},
        {ID = 299, Name = "Chaos Anklet",             Type = "Armor", Address = 0x35FD},
        {ID = 305, Name = "Champion Belt",            Type = "Armor", Address = 0x3603},
        {ID = 301, Name = "Abas Chain",               Type = "Armor", Address = 0x35FF},
        {ID = 302, Name = "Aegis Chain",              Type = "Armor", Address = 0x3600},
        {ID = 303, Name = "Acrisius",                 Type = "Armor", Address = 0x3601},
        {ID = 307, Name = "Acrisius+",                Type = "Armor", Address = 0x3605},
        {ID = 308, Name = "Cosmic Chain",             Type = "Armor", Address = 0x3606},
        {ID = 306, Name = "Petite Ribbon",            Type = "Armor", Address = 0x3604},
        {ID = 304, Name = "Ribbon",                   Type = "Armor", Address = 0x3602},
        {ID = 157, Name = "Grand Ribbon",             Type = "Armor", Address = 0x35D4},

        --Useful
        {ID = 535, Name = "Mickey Munny Pouch",       Type = "Useful", Address = 0x3695},
        {ID = 362, Name = "Olette Munny Pouch",       Type = "Useful", Address = 0x363C},
        {ID = 537, Name = "Hades Cup Trophy",         Type = "Useful", Address = 0x3696},
        {ID = 462, Name = "Unknown Disk",             Type = "Useful", Address = 0x365F},
        {ID = 370, Name = "Olympus Stone",            Type = "Useful", Address = 0x3644},
        {ID = 112, Name = "Max HP Up",                Type = "Useful", Address = 0x3671},  --470 is DUMMY 23, 112 is Encampment Area Map
        {ID = 113, Name = "Max MP Up",                Type = "Useful", Address = 0x3672},  --471 is DUMMY 24, 113 is Village Area Map
        {ID = 114, Name = "Drive Gauge Up",           Type = "Useful", Address = 0x3673},  --472 is DUMMY 25, 114 is Cornerstone Hill Map
        {ID = 116, Name = "Armor Slot Up",            Type = "Useful", Address = 0x3674},  --473 is DUMMY 26, 116 is Lilliput Map
        {ID = 117, Name = "Accessory Slot Up",        Type = "Useful", Address = 0x3675},  --474 is DUMMY 27, 117 is Building Site Map
        {ID = 118, Name = "Item Slot Up",             Type = "Useful", Address = 0x3660},  --463 is DUMMY 16, 118 is Mickey’s House Map

        --Boosts
        {ID = 253, Name = "Power Boost",              Type = "Boost", Address = 0x359D},  --276, 0x3666, market place map
        {ID = 586, Name = "Magic Boost",              Type = "Boost", Address = 0x35E0},  --277, 0x3667, dark rememberance map
        {ID = 590, Name = "Defense Boost",            Type = "Boost", Address = 0x35F8},  --278, 0x3668, depths of remembrance map
        {ID = 532, Name = "AP Boost",                 Type = "Boost", Address = 0x35FE},  --279, 0x3669, mansion map

        --Consumable
        {ID = 127, Name = "Potion",                   Type = "Consumable", Address = 0x36B8},  --1, 0x3580, piglets house map
        {ID = 126, Name = "Hi-Potion",                Type = "Consumable", Address = 0x36B9},  --2, 0x03581, rabbits house map
        {ID = 128, Name = "Ether",                    Type = "Consumable", Address = 0x36BA},  --3, 0x3582, kangas house map
        {ID = 129, Name = "Elixir",                   Type = "Consumable", Address = 0x36BB},  --4, 0x3583, spooky cave map
        {ID = 124, Name = "Megalixir",                Type = "Consumable", Address = 0x36BC},  --7, 0x3586, starry hill map
        {ID = 512, Name = "Tent",                     Type = "Consumable", Address = 0x36BD},  --131,0x35E1, savannah map
        {ID = 252, Name = "Drive Recovery",           Type = "Consumable", Address = 0x36BE},  --274,0x3664, pride rock map
        {ID = 511, Name = "High Drive Recovery",      Type = "Consumable", Address = 0x36BF},  --275,0x3665, oasis map

        --Wincon
        {ID = 367, Name = "Lucky Emblem",             Type = "Wincon", Address = 0x3641}, --letter item
        {ID = 461, Name = "Bounty",                   Type = "Wincon", Address = 0x365E}, --Dummy 14
    }
  return items
end

function ItemDefs:DefineAbilities()
    abilities = {
        --Movement
        {ID = 94,  Name = "High Jump",             Ability = "Sora", Type = "Ability", Address = 0x05E},
        {ID = 98,  Name = "Quick Run",             Ability = "Sora", Type = "Ability", Address = 0x062},
        {ID = 564, Name = "Dodge Roll",            Ability = "Sora", Type = "Ability", Address = 0x234},
        {ID = 102, Name = "Aerial Dodge",          Ability = "Sora", Type = "Ability", Address = 0x066},
        {ID = 106, Name = "Glide",                 Ability = "Sora", Type = "Ability", Address = 0x06A},

        --Support Abilities
        {ID = 138, Name = "Scan",                  Ability = "Sora", Type = "Ability", Address = 0x08A},
        {ID = 158, Name = "Aerial Recovery",       Ability = "Sora", Type = "Ability", Address = 0x09E},
        {ID = 539, Name = "Combo Master",          Ability = "Sora", Type = "Ability", Address = 0x21B},
        {ID = 162, Name = "Combo Plus",            Ability = "Sora", Type = "Ability", Address = 0x0A2},
        {ID = 163, Name = "Air Combo Plus",        Ability = "Sora", Type = "Ability", Address = 0x0A3},
        {ID = 390, Name = "Combo Boost",           Ability = "Sora", Type = "Ability", Address = 0x186},
        {ID = 391, Name = "Air Combo Boost",       Ability = "Sora", Type = "Ability", Address = 0x187},
        {ID = 392, Name = "Reaction Boost",        Ability = "Sora", Type = "Ability", Address = 0x188},
        {ID = 393, Name = "Finishing Plus",        Ability = "Sora", Type = "Ability", Address = 0x189},
        {ID = 394, Name = "Negative Combo",        Ability = "Sora", Type = "Ability", Address = 0x18A},
        {ID = 395, Name = "Berserk Charge",        Ability = "Sora", Type = "Ability", Address = 0x18B},
        {ID = 396, Name = "Damage Drive",          Ability = "Sora", Type = "Ability", Address = 0x18C},
        {ID = 397, Name = "Drive Boost",           Ability = "Sora", Type = "Ability", Address = 0x18D},
        {ID = 398, Name = "Form Boost",            Ability = "Sora", Type = "Ability", Address = 0x18E},
        {ID = 399, Name = "Summon Boost",          Ability = "Sora", Type = "Ability", Address = 0x18F},
        {ID = 401, Name = "Experience Boost",      Ability = "Sora", Type = "Ability", Address = 0x191},
        {ID = 405, Name = "Draw",                  Ability = "Sora", Type = "Ability", Address = 0x195},
        {ID = 406, Name = "Jackpot",               Ability = "Sora", Type = "Ability", Address = 0x196},
        {ID = 407, Name = "Lucky Lucky",           Ability = "Sora", Type = "Ability", Address = 0x197},
        {ID = 540, Name = "Drive Converter",       Ability = "Sora", Type = "Ability", Address = 0x21C},
        {ID = 408, Name = "Fire Boost",            Ability = "Sora", Type = "Ability", Address = 0x198},
        {ID = 409, Name = "Blizzard Boost",        Ability = "Sora", Type = "Ability", Address = 0x199},
        {ID = 410, Name = "Thunder Boost",         Ability = "Sora", Type = "Ability", Address = 0x19A},
        {ID = 411, Name = "Item Boost",            Ability = "Sora", Type = "Ability", Address = 0x19B},
        {ID = 412, Name = "MP Rage",               Ability = "Sora", Type = "Ability", Address = 0x19C},
        {ID = 413, Name = "MP Haste",              Ability = "Sora", Type = "Ability", Address = 0x19D},
        {ID = 421, Name = "MP Hastera",            Ability = "Sora", Type = "Ability", Address = 0x1A5},
        {ID = 422, Name = "MP Hastega",            Ability = "Sora", Type = "Ability", Address = 0x1A6},
        {ID = 414, Name = "Defender",              Ability = "Sora", Type = "Ability", Address = 0x19E},
        {ID = 542, Name = "Damage Control",        Ability = "Sora", Type = "Ability", Address = 0x21E},
        {ID = 541, Name = "Light & Darkness",      Ability = "Sora", Type = "Ability", Address = 0x21D},
        {ID = 403, Name = "Magic Lock-On",         Ability = "Sora", Type = "Ability", Address = 0x193},
        {ID = 402, Name = "Leaf Bracer",           Ability = "Sora", Type = "Ability", Address = 0x192},
        {ID = 400, Name = "Combination Boost",     Ability = "Sora", Type = "Ability", Address = 0x190},
        {ID = 416, Name = "Once More",             Ability = "Sora", Type = "Ability", Address = 0x1A0},
        {ID = 415, Name = "Second Chance",         Ability = "Sora", Type = "Ability", Address = 0x19F},
        {ID = 404, Name = "No Experience",         Ability = "Sora", Type = "Ability", Address = 0x194},

        --Action Abilities
        {ID = 82,  Name = "Guard",                 Ability = "Sora", Type = "Ability", Address = 0x052},
        {ID = 137, Name = "Upper Slash",           Ability = "Sora", Type = "Ability", Address = 0x089},
        {ID = 271, Name = "Horizontal Slash",      Ability = "Sora", Type = "Ability", Address = 0x10F},
        {ID = 267, Name = "Finishing Leap",        Ability = "Sora", Type = "Ability", Address = 0x10B},
        {ID = 273, Name = "Retaliating Slash",     Ability = "Sora", Type = "Ability", Address = 0x111},
        {ID = 262, Name = "Slapshot",              Ability = "Sora", Type = "Ability", Address = 0x106},
        {ID = 263, Name = "Dodge Slash",           Ability = "Sora", Type = "Ability", Address = 0x107},
        {ID = 559, Name = "Flash Step",            Ability = "Sora", Type = "Ability", Address = 0x22F},
        {ID = 264, Name = "Slide Dash",            Ability = "Sora", Type = "Ability", Address = 0x108},
        {ID = 562, Name = "Vicinity Break",        Ability = "Sora", Type = "Ability", Address = 0x232},
        {ID = 265, Name = "Guard Break",           Ability = "Sora", Type = "Ability", Address = 0x109},
        {ID = 266, Name = "Explosion",             Ability = "Sora", Type = "Ability", Address = 0x10A},
        {ID = 269, Name = "Aerial Sweep",          Ability = "Sora", Type = "Ability", Address = 0x10D},
        {ID = 560, Name = "Aerial Dive",           Ability = "Sora", Type = "Ability", Address = 0x230},
        {ID = 270, Name = "Aerial Spiral",         Ability = "Sora", Type = "Ability", Address = 0x10E},
        {ID = 272, Name = "Aerial Finish",         Ability = "Sora", Type = "Ability", Address = 0x110},
        {ID = 561, Name = "Magnet Burst",          Ability = "Sora", Type = "Ability", Address = 0x231},
        {ID = 268, Name = "Counterguard",          Ability = "Sora", Type = "Ability", Address = 0x10C},
        {ID = 385, Name = "Auto Valor",            Ability = "Sora", Type = "Ability", Address = 0x181},
        {ID = 386, Name = "Auto Wisdom",           Ability = "Sora", Type = "Ability", Address = 0x182},
        {ID = 568, Name = "Auto Limit",            Ability = "Sora", Type = "Ability", Address = 0x238},
        {ID = 387, Name = "Auto Master",           Ability = "Sora", Type = "Ability", Address = 0x183},
        {ID = 388, Name = "Auto Final",            Ability = "Sora", Type = "Ability", Address = 0x184},
        {ID = 389, Name = "Auto Summon",           Ability = "Sora", Type = "Ability", Address = 0x185},
        {ID = 198, Name = "Trinity Limit",         Ability = "Sora", Type = "Ability", Address = 0x0C6},

        --Donald Abilities
        {ID = 165, Name = "Donald Fire",           Ability = "Donald", Type = "Ability", Address = 0x0A5},
        {ID = 166, Name = "Donald Blizzard",       Ability = "Donald", Type = "Ability", Address = 0x0A6},
        {ID = 167, Name = "Donald Thunder",        Ability = "Donald", Type = "Ability", Address = 0x0A7},
        {ID = 168, Name = "Donald Cure",           Ability = "Donald", Type = "Ability", Address = 0x0A8},
        {ID = 199, Name = "Fantasia",              Ability = "Donald", Type = "Ability", Address = 0x0C7},
        {ID = 200, Name = "Flare Force",           Ability = "Donald", Type = "Ability", Address = 0x0C8},
        {ID = 412, Name = "Donald MP Rage",        Ability = "Donald", Type = "Ability", Address = 0x19C},
        {ID = 406, Name = "Donald Jackpot",        Ability = "Donald", Type = "Ability", Address = 0x196},
        {ID = 407, Name = "Donald Lucky Lucky",    Ability = "Donald", Type = "Ability", Address = 0x197},
        {ID = 408, Name = "Donald Fire Boost",     Ability = "Donald", Type = "Ability", Address = 0x198},
        {ID = 409, Name = "Donald Blizzard Boost", Ability = "Donald", Type = "Ability", Address = 0x199},
        {ID = 410, Name = "Donald Thunder Boost",  Ability = "Donald", Type = "Ability", Address = 0x19A},
        {ID = 413, Name = "Donald MP Haste",       Ability = "Donald", Type = "Ability", Address = 0x19D},
        {ID = 421, Name = "Donald MP Hastera",     Ability = "Donald", Type = "Ability", Address = 0x1A5},
        {ID = 422, Name = "Donald MP Hastega",     Ability = "Donald", Type = "Ability", Address = 0x1A6},
        {ID = 417, Name = "Donald Auto Limit",     Ability = "Donald", Type = "Ability", Address = 0x1A1},
        {ID = 419, Name = "Donald Hyper Healing",  Ability = "Donald", Type = "Ability", Address = 0x1A3},
        {ID = 420, Name = "Donald Auto Healing",   Ability = "Donald", Type = "Ability", Address = 0x1A4},
        {ID = 411, Name = "Donald Item Boost",     Ability = "Donald", Type = "Ability", Address = 0x19B},
        {ID = 542, Name = "Donald Damage Control", Ability = "Donald", Type = "Ability", Address = 0x21E},
        {ID = 405, Name = "Donald Draw",           Ability = "Donald", Type = "Ability", Address = 0x195},

        --Goofy Abilites
        {ID = 423, Name = "Goofy Tornado",         Ability = "Goofy", Type = "Ability", Address = 0x1A7},
        {ID = 425, Name = "Goofy Turbo",           Ability = "Goofy", Type = "Ability", Address = 0x1A9},
        {ID = 429, Name = "Goofy Bash",            Ability = "Goofy", Type = "Ability", Address = 0x1AD},
        {ID = 201, Name = "Tornado Fusion",        Ability = "Goofy", Type = "Ability", Address = 0x0C9},
        {ID = 202, Name = "Teamwork",              Ability = "Goofy", Type = "Ability", Address = 0x0CA},
        {ID = 405, Name = "Goofy Draw",            Ability = "Goofy", Type = "Ability", Address = 0x195},
        {ID = 406, Name = "Goofy Jackpot",         Ability = "Goofy", Type = "Ability", Address = 0x196},
        {ID = 407, Name = "Goofy Lucky Lucky",     Ability = "Goofy", Type = "Ability", Address = 0x197},
        {ID = 411, Name = "Goofy Item Boost",      Ability = "Goofy", Type = "Ability", Address = 0x19B},
        {ID = 412, Name = "Goofy MP Rage",         Ability = "Goofy", Type = "Ability", Address = 0x19C},
        {ID = 414, Name = "Goofy Defender",        Ability = "Goofy", Type = "Ability", Address = 0x19E},
        {ID = 542, Name = "Goofy Damage Control",  Ability = "Goofy", Type = "Ability", Address = 0x21E},
        {ID = 417, Name = "Goofy Auto Limit",      Ability = "Goofy", Type = "Ability", Address = 0x1A1},
        {ID = 415, Name = "Goofy Second Chance",   Ability = "Goofy", Type = "Ability", Address = 0x19F},
        {ID = 416, Name = "Goofy Once More",       Ability = "Goofy", Type = "Ability", Address = 0x1A0},
        {ID = 418, Name = "Goofy Auto Change",     Ability = "Goofy", Type = "Ability", Address = 0x1A2},
        {ID = 419, Name = "Goofy Hyper Healing",   Ability = "Goofy", Type = "Ability", Address = 0x1A3},
        {ID = 420, Name = "Goofy Auto Healing",    Ability = "Goofy", Type = "Ability", Address = 0x1A4},
        {ID = 413, Name = "Goofy MP Haste",        Ability = "Goofy", Type = "Ability", Address = 0x19D},
        {ID = 421, Name = "Goofy MP Hastera",      Ability = "Goofy", Type = "Ability", Address = 0x1A5},
        {ID = 422, Name = "Goofy MP Hastega",      Ability = "Goofy", Type = "Ability", Address = 0x1A6},
        {ID = 596, Name = "Goofy Protect",         Ability = "Goofy", Type = "Ability", Address = 0x254},
        {ID = 597, Name = "Goofy Protectra",       Ability = "Goofy", Type = "Ability", Address = 0x255},
        {ID = 598, Name = "Goofy Protectga",       Ability = "Goofy", Type = "Ability", Address = 0x256},
    }
    return abilities
end

function ItemDefs:SellableItems()
    SellableItems = {
        --Keyblades
        {ID = 42,  Name = "Oathkeeper",               Type = "Keyblade", Address = 0x35A2},
        {ID = 43,  Name = "Oblivion",                 Type = "Keyblade", Address = 0x35A3},
        {ID = 480, Name = "Star Seeker",              Type = "Keyblade", Address = 0x367B},
        {ID = 481, Name = "Hidden Dragon",            Type = "Keyblade", Address = 0x367C},
        {ID = 484, Name = "Hero's Crest",             Type = "Keyblade", Address = 0x367F},
        {ID = 485, Name = "Monochrome",               Type = "Keyblade", Address = 0x3680},
        {ID = 486, Name = "Follow the Wind",          Type = "Keyblade", Address = 0x3681},
        {ID = 487, Name = "Circle of Life",           Type = "Keyblade", Address = 0x3682},
        {ID = 488, Name = "Photon Debugger",          Type = "Keyblade", Address = 0x3683},
        {ID = 489, Name = "Gull Wing",                Type = "Keyblade", Address = 0x3684},
        {ID = 490, Name = "Rumbling Rose",            Type = "Keyblade", Address = 0x3685},
        {ID = 491, Name = "Guardian Soul",            Type = "Keyblade", Address = 0x3686},
        {ID = 492, Name = "Wishing Lamp",             Type = "Keyblade", Address = 0x3687},
        {ID = 493, Name = "Decisive Pumpkin",         Type = "Keyblade", Address = 0x3688},
        {ID = 494, Name = "Sleeping Lion",            Type = "Keyblade", Address = 0x3689},
        {ID = 495, Name = "Sweet Memories",           Type = "Keyblade", Address = 0x368A},
        {ID = 496, Name = "Mysterious Abyss",         Type = "Keyblade", Address = 0x368B},
        {ID = 543, Name = "Two Become One",           Type = "Keyblade", Address = 0x3698},
        {ID = 497, Name = "Fatal Crest",              Type = "Keyblade", Address = 0x368C},
        {ID = 498, Name = "Bond of Flame",            Type = "Keyblade", Address = 0x368D},
        {ID = 499, Name = "Fenrir",                   Type = "Keyblade", Address = 0x368E},
        {ID = 500, Name = "Ultima Weapon",            Type = "Keyblade", Address = 0x368F},
        {ID = 544, Name = "Winner's Proof",           Type = "Keyblade", Address = 0x3699},
        {ID = 71,  Name = "Pureblood",                Type = "Keyblade", Address = 0x35BF},

        --Staves
        {ID = 546, Name = "Centurion+",               Type = "Staff", Address = 0x369B},
        {ID = 150, Name = "Meteor Staff",             Type = "Staff", Address = 0x35F1},
        {ID = 155, Name = "Nobody Lance",             Type = "Staff", Address = 0x35F6},
        {ID = 549, Name = "Precious Mushroom",        Type = "Staff", Address = 0x369E},
        {ID = 550, Name = "Precious Mushroom+",       Type = "Staff", Address = 0x369F},
        {ID = 551, Name = "Premium Mushroom",         Type = "Staff", Address = 0x36A0},
        {ID = 154, Name = "Rising Dragon",            Type = "Staff", Address = 0x35F5},
        {ID = 503, Name = "Save The Queen+",          Type = "Staff", Address = 0x3692},
        {ID = 156, Name = "Shaman's Relic",           Type = "Staff", Address = 0x35F7},

        --Shields
        {ID = 146, Name = "Akashic Record",           Type = "Shield", Address = 0x35ED},
        {ID = 553, Name = "Frozen Pride+",            Type = "Shield", Address = 0x36A2},
        {ID = 145, Name = "Genji Shield",             Type = "Shield", Address = 0x35EC},
        {ID = 556, Name = "Majestic Mushroom",        Type = "Shield", Address = 0x36A5},
        {ID = 557, Name = "Majestic Mushroom+",       Type = "Shield", Address = 0x36A6},
        {ID = 147, Name = "Nobody Guard",             Type = "Shield", Address = 0x35EE},
        {ID = 141, Name = "Ogre Shield",              Type = "Shield", Address = 0x35E8},
        {ID = 504, Name = "Save The King+",           Type = "Shield", Address = 0x3693},
        {ID = 558, Name = "Ultimate Mushroom",        Type = "Shield", Address = 0x36A7},

        --Accessories
        {ID = 8,   Name = "Ability Ring",             Type = "Accessories", Address = 0x3587},
        {ID = 9,   Name = "Engineer's Ring",          Type = "Accessories", Address = 0x3588},
        {ID = 10,  Name = "Technician's Ring",        Type = "Accessories", Address = 0x3589},
        {ID = 38,  Name = "Skill Ring",               Type = "Accessories", Address = 0x359F},
        {ID = 39,  Name = "Skillful Ring",            Type = "Accessories", Address = 0x35A0},
        {ID = 11,  Name = "Expert's Ring",            Type = "Accessories", Address = 0x358A},
        {ID = 34,  Name = "Master's Ring",            Type = "Accessories", Address = 0x359B},
        {ID = 52,  Name = "Cosmic Ring",              Type = "Accessories", Address = 0x35AD},
        {ID = 599, Name = "Executive's Ring",         Type = "Accessories", Address = 0x36B5},
        {ID = 12,  Name = "Sardonyx Ring",            Type = "Accessories", Address = 0x358B},
        {ID = 13,  Name = "Tourmaline Ring",          Type = "Accessories", Address = 0x358C},
        {ID = 14,  Name = "Aquamarine Ring",          Type = "Accessories", Address = 0x358D},
        {ID = 15,  Name = "Garnet Ring",              Type = "Accessories", Address = 0x358E},
        {ID = 16,  Name = "Diamond Ring",             Type = "Accessories", Address = 0x358F},
        {ID = 17,  Name = "Silver Ring",              Type = "Accessories", Address = 0x3590},
        {ID = 18,  Name = "Gold Ring",                Type = "Accessories", Address = 0x3591},
        {ID = 19,  Name = "Platinum Ring",            Type = "Accessories", Address = 0x3592},
        {ID = 20,  Name = "Mythril Ring",             Type = "Accessories", Address = 0x3593},
        {ID = 28,  Name = "Orichalcum Ring",          Type = "Accessories", Address = 0x359A},
        {ID = 40,  Name = "Soldier Earring",          Type = "Accessories", Address = 0x35A6},
        {ID = 46,  Name = "Fencer Earring",           Type = "Accessories", Address = 0x35A7},
        {ID = 47,  Name = "Mage Earring",             Type = "Accessories", Address = 0x35A8},
        {ID = 48,  Name = "Slayer Earring",           Type = "Accessories", Address = 0x35AC},
        {ID = 53,  Name = "Medal",                    Type = "Accessories", Address = 0x35B0},
        {ID = 35,  Name = "Moon Amulet",              Type = "Accessories", Address = 0x359C},
        {ID = 36,  Name = "Star Charm",               Type = "Accessories", Address = 0x359E},
        {ID = 56,  Name = "Cosmic Arts",              Type = "Accessories", Address = 0x35B1},
        {ID = 57,  Name = "Shadow Archive",           Type = "Accessories", Address = 0x35B2},
        {ID = 58,  Name = "Shadow Archive+",          Type = "Accessories", Address = 0x35B7},
        {ID = 64,  Name = "Full Bloom",               Type = "Accessories", Address = 0x35B9},
        {ID = 66,  Name = "Full Bloom+",              Type = "Accessories", Address = 0x35BB},
        {ID = 65,  Name = "Draw Ring",                Type = "Accessories", Address = 0x35BA},
        {ID = 63,  Name = "Lucky Ring",               Type = "Accessories", Address = 0x35B8},

        --Armor
        {ID = 67,  Name = "Elven Bandana",            Type = "Armor", Address = 0x35BC},
        {ID = 68,  Name = "Divine Bandana",           Type = "Armor", Address = 0x35BD},
        {ID = 78,  Name = "Protect Belt",             Type = "Armor", Address = 0x35C7},
        {ID = 79,  Name = "Gaia Belt",                Type = "Armor", Address = 0x35CA},
        {ID = 69,  Name = "Power Band",               Type = "Armor", Address = 0x35BE},
        {ID = 70,  Name = "Buster Band",              Type = "Armor", Address = 0x35C6},
        {ID = 111, Name = "Cosmic Belt",              Type = "Armor", Address = 0x35D1},
        {ID = 173, Name = "Fire Bangle",              Type = "Armor", Address = 0x35D7},
        {ID = 174, Name = "Fira Bangle",              Type = "Armor", Address = 0x35D8},
        {ID = 197, Name = "Firaga Bangle",            Type = "Armor", Address = 0x35D9},
        {ID = 284, Name = "Firagun Bangle",           Type = "Armor", Address = 0x35DA},
        {ID = 286, Name = "Blizzard Armlet",          Type = "Armor", Address = 0x35DC},
        {ID = 287, Name = "Blizzara Armlet",          Type = "Armor", Address = 0x35DD},
        {ID = 288, Name = "Blizzaga Armlet",          Type = "Armor", Address = 0x35DE},
        {ID = 289, Name = "Blizzagun Armlet",         Type = "Armor", Address = 0x35DF},
        {ID = 291, Name = "Thunder Trinket",          Type = "Armor", Address = 0x35E2},
        {ID = 292, Name = "Thundara Trinket",         Type = "Armor", Address = 0x35E3},
        {ID = 293, Name = "Thundaga Trinket",         Type = "Armor", Address = 0x35E4},
        {ID = 294, Name = "Thundagun Trinket",        Type = "Armor", Address = 0x35E5},
        {ID = 132, Name = "Shock Charm",              Type = "Armor", Address = 0x35D2},
        {ID = 133, Name = "Shock Charm+",             Type = "Armor", Address = 0x35D3},
        {ID = 296, Name = "Shadow Anklet",            Type = "Armor", Address = 0x35F9},
        {ID = 297, Name = "Dark Anklet",              Type = "Armor", Address = 0x35FB},
        {ID = 298, Name = "Midnight Anklet",          Type = "Armor", Address = 0x35FC},
        {ID = 299, Name = "Chaos Anklet",             Type = "Armor", Address = 0x35FD},
        {ID = 305, Name = "Champion Belt",            Type = "Armor", Address = 0x3603},
        {ID = 301, Name = "Abas Chain",               Type = "Armor", Address = 0x35FF},
        {ID = 302, Name = "Aegis Chain",              Type = "Armor", Address = 0x3600},
        {ID = 303, Name = "Acrisius",                 Type = "Armor", Address = 0x3601},
        {ID = 307, Name = "Acrisius+",                Type = "Armor", Address = 0x3605},
        {ID = 308, Name = "Cosmic Chain",             Type = "Armor", Address = 0x3606},
        {ID = 306, Name = "Petite Ribbon",            Type = "Armor", Address = 0x3604},
        {ID = 304, Name = "Ribbon",                   Type = "Armor", Address = 0x3602},
        {ID = 157, Name = "Grand Ribbon",             Type = "Armor", Address = 0x35D4},
    }
end

return ItemDefs