local LocationDefs = {}

function LocationDefs:DefineWorldEvents()
    Worlds = {
        LoD_Checks = {
	        [1245648] = {Name = "(LoD) Bamboo Grove Dark Shard",          Address = 0x23AC, BitIndex = 1, Chest = true},
	        [1245649] = {Name = "(LoD) Bamboo Grove Ether",               Address = 0x23D9, BitIndex = 7, Chest = true},
	        [1245650] = {Name = "(LoD) Bamboo Grove Mythril Shard",       Address = 0x23DA, BitIndex = 0, Chest = true},
	        [1245651] = {Name = "(LoD) Bamboo Grove Encampment Area Map", Address = 0x1D94, BitIndex = 6, Chest = false},
	        [1245652] = {Name = "(LoD) Mission 3",                        Address = 0x1D96, BitIndex = 0, Chest = false},
	        [1245653] = {Name = "(LoD) Checkpoint Hi-Potion",             Address = 0x23AD, BitIndex = 1, Chest = true},
	        [1245654] = {Name = "(LoD) Checkpoint Mythril Shard",         Address = 0x23AD, BitIndex = 2, Chest = true},
	        [1245655] = {Name = "(LoD) Mountain Trail Lightning Shard",   Address = 0x23AD, BitIndex = 3, Chest = true},
	        [1245656] = {Name = "(LoD) Mountain Trail Recovery Recipe",   Address = 0x23AD, BitIndex = 4, Chest = true},
	        [1245657] = {Name = "(LoD) Mountain Trail Ether",             Address = 0x23AD, BitIndex = 5, Chest = true},
	        [1245658] = {Name = "(LoD) Mountain Trail Mythril Shard",     Address = 0x23AD, BitIndex = 6, Chest = true},
	        [1245659] = {Name = "(LoD) Village Cave Area Map",            Address = 0x1D96, BitIndex = 6, Chest = false},
	        [1245660] = {Name = "(LoD) Village Cave Dark Shard",          Address = 0x23AE, BitIndex = 0, Chest = true},
	        [1245661] = {Name = "(LoD) Village Cave AP Boost",            Address = 0x23AD, BitIndex = 7, Chest = true},
	        [1245662] = {Name = "(LoD) Village Cave Bonus: Sora Slot 1",  Address = 0x3709, BitIndex = 3, Chest = false},
	        [1245663] = {Name = "(LoD) Ridge Frost Shard",                Address = 0x23AE, BitIndex = 1, Chest = true},
	        [1245664] = {Name = "(LoD) Ridge AP Boost",                   Address = 0x23AE, BitIndex = 2, Chest = true},
	        [1245665] = {Name = "(LoD) Shan-Yu Bonus: Sora Slot 1",       Address = 0x3705, BitIndex = 1, Chest = false},
	        [1245666] = {Name = "(LoD) Shan-Yu Bonus: Sora Slot 2",       Address = 0x3705, BitIndex = 1, Chest = false},
	        [1245877] = {Name = "(LoD) Shan-Yu Bonus: Goofy Slot 1",      Address = 0x3705, BitIndex = 1, Chest = false},
	        [1245667] = {Name = "(LoD) Hidden Dragon",                    Address = 0x1D92, BitIndex = 2, Chest = false},
	        [1245668] = {Name = "(LoD2) Throne Room Torn Pages",          Address = 0x23AE, BitIndex = 3, Chest = true},
	        [1245669] = {Name = "(LoD2) Throne Room Palace Map",          Address = 0x23AE, BitIndex = 4, Chest = true},
	        [1245670] = {Name = "(LoD2) Throne Room AP Boost",            Address = 0x23AE, BitIndex = 5, Chest = true},
	        [1245671] = {Name = "(LoD2) Throne Room Queen Recipe",        Address = 0x23AE, BitIndex = 6, Chest = true},
	        [1245672] = {Name = "(LoD2) Throne Room AP Boost 2",          Address = 0x23AE, BitIndex = 7, Chest = true},
	        [1245673] = {Name = "(LoD2) Throne Room Ogre Shield",         Address = 0x23AF, BitIndex = 0, Chest = true},
	        [1245674] = {Name = "(LoD2) Throne Room Mythril Crystal",     Address = 0x23AF, BitIndex = 1, Chest = true},
	        [1245675] = {Name = "(LoD2) Throne Room Orichalcum",          Address = 0x23AF, BitIndex = 2, Chest = true},
	        [1245676] = {Name = "(LoD2) Storm Rider Bonus: Sora Slot 1",  Address = 0x3705, BitIndex = 2, Chest = false},
	        [1245878] = {Name = "(LoD2) Storm Rider Bonus: Goofy Slot 1", Address = 0x3705, BitIndex = 2, Chest = false},
        },

	    AG_Checks = {
	        [1245612] = {Name = "(AG) Agrabah Map",                                 Address = 0x1D74, BitIndex = 4, Chest = false},
            [1245613] = {Name = "(AG) Agrabah Dark Shard",                          Address = 0x23AF, BitIndex = 3, Chest = true},
            [1245614] = {Name = "(AG) Agrabah Mythril Shard",                       Address = 0x23AF, BitIndex = 4, Chest = true},
            [1245615] = {Name = "(AG) Agrabah Hi-Potion",                           Address = 0x23AF, BitIndex = 5, Chest = true},
            [1245616] = {Name = "(AG) Agrabah AP Boost",                            Address = 0x23AF, BitIndex = 6, Chest = true},
            [1245617] = {Name = "(AG) Agrabah Mythril Stone",                       Address = 0x23AF, BitIndex = 7, Chest = true},
            [1245618] = {Name = "(AG) Agrabah Mythril Shard 2",                     Address = 0x23B0, BitIndex = 0, Chest = true},
            [1245619] = {Name = "(AG) Agrabah Serenity Shard",                      Address = 0x23DA, BitIndex = 3, Chest = true},
            [1245620] = {Name = "(AG) Bazaar Mythril Gem",                          Address = 0x23B0, BitIndex = 1, Chest = true},
            [1245621] = {Name = "(AG) Bazaar Power Shard",                          Address = 0x23B0, BitIndex = 2, Chest = true},
            [1245622] = {Name = "(AG) Bazaar Hi-Potion",                            Address = 0x23B0, BitIndex = 3, Chest = true},
            [1245623] = {Name = "(AG) Bazaar AP Boost",                             Address = 0x23B0, BitIndex = 4, Chest = true},
            [1245624] = {Name = "(AG) Bazaar Mythril Shard",                        Address = 0x23B0, BitIndex = 5, Chest = true},
            [1245625] = {Name = "(AG) Palace Walls Skill Ring",                     Address = 0x23B0, BitIndex = 6, Chest = true},
            [1245626] = {Name = "(AG) Palace Walls Mythril Stone",                  Address = 0x23DB, BitIndex = 5, Chest = true},
            [1245627] = {Name = "(AG) Cave Entrance Power Stone",                   Address = 0x23B0, BitIndex = 7, Chest = true},
            [1245628] = {Name = "(AG) Cave Entrance Mythril Shard",                 Address = 0x23B1, BitIndex = 0, Chest = true},
            [1245629] = {Name = "(AG) Valley of Stone Mythril Stone",               Address = 0x23B1, BitIndex = 2, Chest = true},
            [1245630] = {Name = "(AG) Valley of Stone AP Boost",                    Address = 0x23B1, BitIndex = 3, Chest = true},
            [1245631] = {Name = "(AG) Valley of Stone Mythril Shard",               Address = 0x23B1, BitIndex = 4, Chest = true},
            [1245632] = {Name = "(AG) Valley of Stone Hi-Potion",                   Address = 0x23B1, BitIndex = 5, Chest = true},
            [1245633] = {Name = "(AG) Abu Escort Bonus: Sora Slot 1",               Address = 0x3709, BitIndex = 2, Chest = false},
            [1245866] = {Name = "(AG) Abu Escort Bonus: Donald Slot 1",             Address = 0x3709, BitIndex = 2, Chest = false},
            [1245634] = {Name = "(AG) Chasm of Challenges Cave of Wonders Map",     Address = 0x23D8, BitIndex = 7, Chest = true},
            [1245635] = {Name = "(AG) Chasm of Challenges AP Boost",                Address = 0x23B1, BitIndex = 6, Chest = true},
            [1245636] = {Name = "(AG) Treasure Room",                               Address = 0x3709, BitIndex = 6, Chest = false},
            [1245881] = {Name = "(AG) Treasure Room Heartless Bonus: Goofy Slot 1", Address = 0x3709, BitIndex = 6, Chest = false},
            [1245637] = {Name = "(AG) Treasure Room AP Boost",                      Address = 0x23DA, BitIndex = 4, Chest = true},
            [1245638] = {Name = "(AG) Treasure Room Serenity Gem",                  Address = 0x23DA, BitIndex = 5, Chest = true},
            [1245639] = {Name = "(AG) Elemental Lords Bonus: Sora Slot 1",          Address = 0x3708, BitIndex = 5, Chest = false},
            [1245640] = {Name = "(AG) Lamp Charm",                                  Address = 0x1D72, BitIndex = 4, Chest = false},
            [1245641] = {Name = "(AG2) Ruined Chamber Torn Pages",                  Address = 0x23B1, BitIndex = 1, Chest = true},
            [1245642] = {Name = "(AG2) Ruined Chamber Ruins Map",                   Address = 0x23D8, BitIndex = 6, Chest = true},
            [1245643] = {Name = "(AG2) Genie Jafar",                                Address = 0x3705, BitIndex = 7, Chest = false},
            [1245644] = {Name = "(AG2) Wishing Lamp",                               Address = 0x1D77, BitIndex = 3, Chest = false},
        },

        DC_Checks = {
            [1245582] = {Name = "(DC) Courtyard Mythril Shard",                                         Address = 0x23B4, BitIndex = 1, Chest = true},
            [1245583] = {Name = "(DC) Courtyard Star Recipe",                                           Address = 0x23B4, BitIndex = 2, Chest = true},
            [1245584] = {Name = "(DC) Courtyard AP Boost",                                              Address = 0x23B4, BitIndex = 3, Chest = true},
            [1245585] = {Name = "(DC) Courtyard Mythril Stone",                                         Address = 0x23B4, BitIndex = 4, Chest = true},
            [1245586] = {Name = "(DC) Courtyard Blazing Stone",                                         Address = 0x23B4, BitIndex = 5, Chest = true},
            [1245587] = {Name = "(DC) Courtyard Blazing Shard",                                         Address = 0x23B4, BitIndex = 6, Chest = true},
            [1245588] = {Name = "(DC) Courtyard Mythril Shard 2",                                       Address = 0x23B4, BitIndex = 7, Chest = true},
            [1245589] = {Name = "(DC) Library Torn Pages",                                              Address = 0x23B4, BitIndex = 0, Chest = true},
            [1245590] = {Name = "(DC) Disney Castle Map",                                               Address = 0x1E10, BitIndex = 4, Chest = false},
            [1245591] = {Name = "(DC) Minnie Escort Bonus: Sora Slot 1",                                Address = 0x3708, BitIndex = 6, Chest = false},
            [1245592] = {Name = "(DC) Minnie Escort Bonus: Sora Slot 2",                                Address = 0x3708, BitIndex = 6, Chest = false},
            [1245609] = {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Bonus: Sora Slot 1",  Address = 0x370C, BitIndex = 6, Chest = false},
            [1245610] = {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Proof of Connection", Address = 0x370C, BitIndex = 6, Chest = false},
            [1245611] = {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Manifest Illusion",   Address = 0x370C, BitIndex = 6, Chest = false},
        },

        TR_Checks = {
            [1245593] = {Name = "(TR) Cornerstone Hill Map",            Address = 0x23B2, BitIndex = 0, Chest = true},
            [1245594] = {Name = "(TR) Cornerstone Hill Frost Shard",    Address = 0x23B2, BitIndex = 1, Chest = true},
            [1245595] = {Name = "(TR) Pier Mythril Shard",              Address = 0x23B2, BitIndex = 3, Chest = true},
            [1245596] = {Name = "(TR) Pier Hi-Potion",                  Address = 0x23B2, BitIndex = 4, Chest = true},
            [1245597] = {Name = "(TR) Waterway Mythril Stone",          Address = 0x23B2, BitIndex = 5, Chest = true},
            [1245598] = {Name = "(TR) Waterway AP Boost",               Address = 0x23B2, BitIndex = 6, Chest = true},
            [1245599] = {Name = "(TR) Waterway Frost Stone",            Address = 0x23B2, BitIndex = 7, Chest = false},
            [1245600] = {Name = "(TR) Window of Time Map",              Address = 0x1E32, BitIndex = 4, Chest = false},
            [1245601] = {Name = "(TR) Boat Pete Bonus: Sora Slot 1",    Address = 0x3706, BitIndex = 0, Chest = false},
            [1245840] = {Name = "(TR) Boat Pete Bonus: Donald Slot 1",  Address = 0x3706, BitIndex = 0, Chest = false},
            [1245841] = {Name = "(TR) Boat Pete Bonus: Donald Slot 2",  Address = 0x3706, BitIndex = 0, Chest = false},
            [1245602] = {Name = "(TR) Future Pete Bonus: Sora Slot 1",  Address = 0x3706, BitIndex = 1, Chest = false},
            [1245603] = {Name = "(TR) Future Pete Bonus: Sora Slot 2",  Address = 0x3706, BitIndex = 1, Chest = false},
            [1245876] = {Name = "(TR) Future Pete Bonus: Goofy Slot 1", Address = 0x3706, BitIndex = 1, Chest = false},
            [1245604] = {Name = "(TR) Monochrome",                      Address = 0x1E33, BitIndex = 2, Chest = false},
            [1245605] = {Name = "(TR) Wisdom Form",                     Address = 0x1E33, BitIndex = 2, Chest = false},
        },

        Pooh_Checks = {
            [1245558] = {Name = "(100Acre) Pooh's House 100 Acre Wood Map", Address = 0x23C9, BitIndex = 7, Chest = true},
            [1245559] = {Name = "(100Acre) Pooh's House AP Boost",          Address = 0x23B5, BitIndex = 4, Chest = true},
            [1245560] = {Name = "(100Acre) Pooh's House Mythril Stone",     Address = 0x23B5, BitIndex = 5, Chest = true},
            [1245561] = {Name = "(100Acre) Piglet's House Defense Boost",   Address = 0x23B6, BitIndex = 4, Chest = true},
            [1245562] = {Name = "(100Acre) Piglet's House AP Boost",        Address = 0x23B6, BitIndex = 2, Chest = true},
            [1245563] = {Name = "(100Acre) Piglet's House Mythril Gem",     Address = 0x23B6, BitIndex = 3, Chest = true},
            [1245564] = {Name = "(100Acre) Rabbit's House Draw Ring",       Address = 0x23CA, BitIndex = 0, Chest = true},
            [1245565] = {Name = "(100Acre) Rabbit's House Mythril Crystal", Address = 0x23B5, BitIndex = 7, Chest = true},
            [1245566] = {Name = "(100Acre) Rabbit's House AP Boost",        Address = 0x23B6, BitIndex = 0, Chest = true},
            [1245567] = {Name = "(100Acre) Kanga's House Magic Boost",      Address = 0x23B6, BitIndex = 7, Chest = true},
            [1245568] = {Name = "(100Acre) Kanga's House AP Boost",         Address = 0x23B6, BitIndex = 5, Chest = true},
            [1245569] = {Name = "(100Acre) Kanga's House Orichalcum",       Address = 0x23B6, BitIndex = 6, Chest = true},
            [1245570] = {Name = "(100Acre) Spooky Cave Mythril Gem",        Address = 0x23B7, BitIndex = 1, Chest = true},
            [1245571] = {Name = "(100Acre) Spooky Cave AP Boost",           Address = 0x23B7, BitIndex = 2, Chest = true},
            [1245572] = {Name = "(100Acre) Spooky Cave Orichalcum",         Address = 0x23B7, BitIndex = 3, Chest = false},
            [1245573] = {Name = "(100Acre) Spooky Cave Guard Recipe",       Address = 0x23B7, BitIndex = 4, Chest = true},
            [1245574] = {Name = "(100Acre) Spooky Cave Mythril Crystal",    Address = 0x23B7, BitIndex = 6, Chest = true},
            [1245575] = {Name = "(100Acre) Spooky Cave AP Boost 2",         Address = 0x23B7, BitIndex = 7, Chest = true},
            [1245576] = {Name = "(100Acre) Sweet Memories",                 Address = 0x1DB4, BitIndex = 6, Chest = false},
            [1245577] = {Name = "(100Acre) Spooky Cave Map",                Address = 0x1DB4, BitIndex = 6, Chest = false},
            [1245578] = {Name = "(100Acre) Starry Hill Cosmic Ring",        Address = 0x23C9, BitIndex = 6, Chest = true},
            [1245579] = {Name = "(100Acre) Starry Hill Style Recipe",       Address = 0x23B5, BitIndex = 1, Chest = true},
            [1245580] = {Name = "(100Acre) Starry Hill Cure Element",       Address = 0x1DB5, BitIndex = 5, Chest = false},
            [1245581] = {Name = "(100Acre) Starry Hill Orichalcum+",        Address = 0x1DB5, BitIndex = 5, Chest = false},
        },

        OC_Checks = {
            [1245512] = {Name = "(OC) Passage Mythril Shard",           Address = 0x23B9, BitIndex = 6, Chest = true},
            [1245513] = {Name = "(OC) Passage Mythril Stone",           Address = 0x23B9, BitIndex = 7, Chest = true},
            [1245514] = {Name = "(OC) Passage Ether",                   Address = 0x23BA, BitIndex = 0, Chest = true},
            [1245515] = {Name = "(OC) Passage AP Boost",                Address = 0x23BA, BitIndex = 1, Chest = true},
            [1245516] = {Name = "(OC) Passage Hi-Potion",               Address = 0x23BA, BitIndex = 2, Chest = true},
            [1245517] = {Name = "(OC) Inner Chamber Underworld Map",    Address = 0x23B8, BitIndex = 4, Chest = true},
            [1245518] = {Name = "(OC) Inner Chamber Mythril Shard",     Address = 0x23B8, BitIndex = 3, Chest = true},
            [1245519] = {Name = "(OC) Cerberus Bonus: Sora Slot 1",     Address = 0x3704, BitIndex = 5, Chest = false},
            [1245520] = {Name = "(OC) Coliseum Map",                    Address = 0x1D5A, BitIndex = 4, Chest = false},
            [1245521] = {Name = "(OC) Urns Bonus: Sora Slot 1",         Address = 0x370B, BitIndex = 1, Chest = false},
            [1245522] = {Name = "(OC) Underworld Entrance Power Boost", Address = 0x23B8, BitIndex = 0, Chest = false},
            [1245523] = {Name = "(OC) Caverns Entrance Lucid Shard",    Address = 0x23B8, BitIndex = 5, Chest = true},
            [1245524] = {Name = "(OC) Caverns Entrance AP Boost",       Address = 0x23B8, BitIndex = 6, Chest = true},
            [1245525] = {Name = "(OC) Caverns Entrance Mythril Shard",  Address = 0x23DA, BitIndex = 6, Chest = true},
            [1245526] = {Name = "(OC) The Lost Road Bright Shard",      Address = 0x23BA, BitIndex = 3, Chest = true},
            [1245527] = {Name = "(OC) The Lost Road Ether",             Address = 0x23BA, BitIndex = 4, Chest = true},
            [1245528] = {Name = "(OC) The Lost Road Mythril Shard",     Address = 0x23BA, BitIndex = 5, Chest = true},
            [1245529] = {Name = "(OC) The Lost Road Mythril Stone",     Address = 0x23BA, BitIndex = 6, Chest = true},
            [1245530] = {Name = "(OC) Atrium Lucid Stone",              Address = 0x23BA, BitIndex = 7, Chest = true},
            [1245531] = {Name = "(OC) Atrium AP Boost",                 Address = 0x23BB, BitIndex = 0, Chest = true},
            [1245532] = {Name = "(OC) Demyx Bonus: Sora Slot 1",        Address = 0x370B, BitIndex = 2, Chest = false},
            [1245839] = {Name = "(OC) Demyx Bonus: Donald Slot 1",      Address = 0x370B, BitIndex = 2, Chest = false},
            [1245533] = {Name = "(OC) Secret Ansem Report 5 (Demyx)",   Address = 0x1D5B, BitIndex = 3, Chest = false},
            [1245534] = {Name = "(OC) Olympus Stone",                   Address = 0x1D5B, BitIndex = 3, Chest = false},
            [1245535] = {Name = "(OC) The Lock Caverns Map",            Address = 0x23B9, BitIndex = 4, Chest = true},
            [1245536] = {Name = "(OC) The Lock Mythril Shard",          Address = 0x23B9, BitIndex = 0, Chest = true},
            [1245537] = {Name = "(OC) The Lock AP Boost",               Address = 0x23B9, BitIndex = 2, Chest = true},
            [1245538] = {Name = "(OC) Pete OC Bonus: Sora Slot 1",      Address = 0x3704, BitIndex = 6, Chest = false},
            [1245875] = {Name = "(OC) Pete Bonus: Goofy Slot 1",        Address = 0x3704, BitIndex = 6, Chest = false},
            [1245539] = {Name = "(OC) Hydra Bonus: Sora Slot 1",        Address = 0x3704, BitIndex = 7, Chest = false},
            [1245540] = {Name = "(OC) Hydra Bonus: Sora Slot 2",        Address = 0x3704, BitIndex = 7, Chest = false},
            [1245541] = {Name = "(OC) Hero's Crest",                    Address = 0x1D55, BitIndex = 7, Chest = false},
            [1245542] = {Name = "(OC2) Auron's Statue",                 Address = 0x1D5F, BitIndex = 2, Chest = false},
            [1245543] = {Name = "(OC2) Hades Bonus: Sora Slot 1",       Address = 0x3705, BitIndex = 0, Chest = false},
            [1245544] = {Name = "(OC2) Hades Bonus: Sora Slot 2",       Address = 0x3705, BitIndex = 0, Chest = false},
            [1245545] = {Name = "(OC2) Guardian Soul",                  Address = 0x1D56, BitIndex = 5, Chest = false},
            [1245549] = {Name = "Protect Belt Pain and Panic Cup",      Address = 0x1D57, BitIndex = 6, Chest = false},
            [1245550] = {Name = "Serenity Gem Pain and Panic Cup",      Address = 0x1D57, BitIndex = 6, Chest = false},
            [1245551] = {Name = "Rising Dragon Cerberus Cup",           Address = 0x1D58, BitIndex = 0, Chest = false},
            [1245552] = {Name = "Serenity Crystal Cerberus Cup",        Address = 0x1D58, BitIndex = 0, Chest = false},
            [1245553] = {Name = "Genji Shield Titan Cup",               Address = 0x1D58, BitIndex = 1, Chest = false},
            [1245554] = {Name = "Skillful Ring Titan Cup",              Address = 0x1D58, BitIndex = 1, Chest = false},
            [1245555] = {Name = "Fatal Crest Goddess of Fate Cup",      Address = 0x1D58, BitIndex = 4, Chest = false},
            [1245556] = {Name = "Orichalcum+ Goddess of Fate Cup",      Address = 0x1D58, BitIndex = 4, Chest = false},
            [1245557] = {Name = "Hades Cup Trophy Paradox Cups",        Address = 0x1D5A, BitIndex = 1, Chest = false},
        },

        BC_Checks = {
            [1245480] = {Name = "(BC) Courtyard AP Boost",                  Address = 0x23BB, BitIndex = 5, Chest = true},
            [1245481] = {Name = "(BC) Courtyard Hi-Potion",                 Address = 0x23BB, BitIndex = 6, Chest = true},
            [1245482] = {Name = "(BC) Courtyard Mythril Shard",             Address = 0x23DA, BitIndex = 7, Chest = true},
            [1245483] = {Name = "(BC) Belle's Room Castle Map",             Address = 0x23BB, BitIndex = 2, Chest = true},
            [1245484] = {Name = "(BC) Belle's Room Mega-Recipe",            Address = 0x23BB, BitIndex = 3, Chest = true},
            [1245485] = {Name = "(BC) The East Wing Mythril Shard",         Address = 0x23BB, BitIndex = 7, Chest = true},
            [1245486] = {Name = "(BC) The East Wing Tent",                  Address = 0x23BC, BitIndex = 0, Chest = true},
            [1245487] = {Name = "(BC) The West Hall Hi-Potion",             Address = 0x23BC, BitIndex = 1, Chest = true},
            [1245488] = {Name = "(BC) The West Hall Power Shard",           Address = 0x23BC, BitIndex = 3, Chest = true},
            [1245489] = {Name = "(BC) The West Hall AP Boost Post Dungeon", Address = 0x23BC, BitIndex = 5, Chest = true},
            [1245490] = {Name = "(BC) The West Hall Bright Stone",          Address = 0x23DB, BitIndex = 0, Chest = true},
            [1245491] = {Name = "(BC) The West Hall Mythril Shard",         Address = 0x23BC, BitIndex = 2, Chest = true},
            [1245498] = {Name = "(BC) The West Hall Mythril Shard 2",       Address = 0x23BC, BitIndex = 4, Chest = true},
            [1245492] = {Name = "(BC) Thresholder Bonus: Sora Slot 1",      Address = 0x3704, BitIndex = 2, Chest = false},
            [1245848] = {Name = "(BC) Thresholder Bonus: Donald Slot 1",    Address = 0x3704, BitIndex = 2, Chest = false},
            [1245493] = {Name = "(BC) Dungeon Basement Map",                Address = 0x23BD, BitIndex = 0, Chest = true},
            [1245494] = {Name = "(BC) Dungeon AP Boost",                    Address = 0x23BD, BitIndex = 1, Chest = true},
            [1245495] = {Name = "(BC) Secret Passage Mythril Shard",        Address = 0x23BD, BitIndex = 2, Chest = true},
            [1245496] = {Name = "(BC) Secret Passage Hi-Potion",            Address = 0x23BD, BitIndex = 5, Chest = true},
            [1245497] = {Name = "(BC) Secret Passage Lucid Shard",          Address = 0x23BD, BitIndex = 3, Chest = true},
            [1245499] = {Name = "(BC) The West Wing Mythril Shard",         Address = 0x23BC, BitIndex = 6, Chest = true},
            [1245500] = {Name = "(BC) The West Wing Tent",                  Address = 0x23BC, BitIndex = 7, Chest = true},
            [1245501] = {Name = "(BC) Beast Bonus: Sora Slot 1",            Address = 0x3705, BitIndex = 4, Chest = false},
            [1245879] = {Name = "(BC) Beast Bonus: Goofy Slot 1",           Address = 0x3705, BitIndex = 4, Chest = false},
            [1245502] = {Name = "(BC) The Beast's Room Blazing Shard",      Address = 0x23BB, BitIndex = 4, Chest = true},
            [1245503] = {Name = "(BC) Dark Thorn Bonus: Sora Slot 1",       Address = 0x3704, BitIndex = 3, Chest = false},
            [1245504] = {Name = "(BC) Dark Thorn Bonus: Sora Slot 2",       Address = 0x3704, BitIndex = 3, Chest = false},
            [1245505] = {Name = "(BC) Dark Thorn Cure Element",             Address = 0x1D32, BitIndex = 5, Chest = false},
            [1245506] = {Name = "(BC2) Rumbling Rose",                      Address = 0x1D39, BitIndex = 0, Chest = false},
            [1245507] = {Name = "(BC2) Castle Walls Map",                   Address = 0x1D39, BitIndex = 0, Chest = false},
            [1245508] = {Name = "(BC2) Xaldin Bonus: Sora Slot 1",          Address = 0x3704, BitIndex = 4, Chest = false},
            [1245509] = {Name = "(BC2) Xaldin Bonus: Sora Slot 2",          Address = 0x3704, BitIndex = 4, Chest = false},
            [1245849] = {Name = "(BC2) Xaldin Bonus: Donald Slot 1",        Address = 0x3704, BitIndex = 4, Chest = false},
            [1245510] = {Name = "(BC2) Secret Ansem Report 4 (Xaldin)",     Address = 0x1D31, BitIndex = 2, Chest = false},
            [1245511] = {Name = "(Post BC2: Ballroom) Data Xaldin",         Address = 0x1D34, BitIndex = 7, Chest = false},
        },

        SP_Checks = {
            [1245456] = {Name = "(SP) Pit Cell Area Map",                   Address = 0x23CA, BitIndex = 2, Chest = true},
            [1245457] = {Name = "(SP) Pit Cell Mythril Crystal",            Address = 0x23BD, BitIndex = 6, Chest = true},
            [1245458] = {Name = "(SP) Canyon Dark Crystal",                 Address = 0x23BE, BitIndex = 1, Chest = true},
            [1245459] = {Name = "(SP) Canyon Mythril Stone",                Address = 0x23BE, BitIndex = 2, Chest = true},
            [1245460] = {Name = "(SP) Canyon Mythril Gem",                  Address = 0x23BE, BitIndex = 3, Chest = true},
            [1245461] = {Name = "(SP) Canyon Frost Crystal",                Address = 0x23DB, BitIndex = 6, Chest = true},
            [1245462] = {Name = "(SP) Screens Bonus: Sora Slot 1",          Address = 0x3709, BitIndex = 5, Chest = false},
            [1245837] = {Name = "(SP) Screens Bonus: Donald Slot 1",        Address = 0x3709, BitIndex = 5, Chest = false},
            [1245463] = {Name = "(SP) Hallway Power Crystal",               Address = 0x23BE, BitIndex = 4, Chest = true},
            [1245464] = {Name = "(SP) Hallway AP Boost",                    Address = 0x23BE, BitIndex = 5, Chest = true},
            [1245465] = {Name = "(SP) Communications Room I/O Tower Map",   Address = 0x23BF, BitIndex = 1, Chest = true},
            [1245466] = {Name = "(SP) Communications Room Gaia Belt",       Address = 0x23DA, BitIndex = 1, Chest = true},
            [1245467] = {Name = "(SP) Hostile Program Bonus: Sora Slot 1",  Address = 0x3707, BitIndex = 7, Chest = false},
            [1245468] = {Name = "(SP) Hostile Program Bonus: Sora Slot 2",  Address = 0x3707, BitIndex = 7, Chest = false},
            [1245870] = {Name = "(SP) Hostile Program Bonus: Goofy Slot 1", Address = 0x3707, BitIndex = 7, Chest = false},
            [1245469] = {Name = "(SP) Photon Debugger",                     Address = 0x1EB2, BitIndex = 3, Chest = false},
            [1245470] = {Name = "(SP2) Solar Sailer",                       Address = 0x370B, BitIndex = 5, Chest = false},
            [1245844] = {Name = "(SP2) Solar Sailer Bonus: Donald Slot 1",  Address = 0x370B, BitIndex = 5, Chest = false},
            [1245471] = {Name = "(SP2) Central Computer Core AP Boost",     Address = 0x23BF, BitIndex = 4, Chest = true},
            [1245472] = {Name = "(SP2) Central Computer Core Orichalcum+",  Address = 0x23BF, BitIndex = 5, Chest = true},
            [1245473] = {Name = "(SP2) Central Computer Core Cosmic Arts",  Address = 0x23BF, BitIndex = 6, Chest = true},
            [1245474] = {Name = "(SP2) Central Computer Core Map",          Address = 0x23D9, BitIndex = 0, Chest = true},
            [1245475] = {Name = "(SP2) MCP Bonus: Sora Slot 1",             Address = 0x3708, BitIndex = 0, Chest = false},
            [1245476] = {Name = "(SP2) MCP Bonus: Sora Slot 2",             Address = 0x3708, BitIndex = 0, Chest = false},
        },

        HT_Checks = {
            [1245398] = {Name = "(HT) Graveyard Mythril Shard",                     Address = 0x23C0, BitIndex = 2, Chest = true},
            [1245399] = {Name = "(HT) Graveyard Serenity Gem",                      Address = 0x23C0, BitIndex = 3, Chest = true},
            [1245400] = {Name = "(HT) Finklestein's Lab Halloween Town Map",        Address = 0x23C0, BitIndex = 1, Chest = true},
            [1245401] = {Name = "(HT) Town Square Mythril Stone",                   Address = 0x23BF, BitIndex = 7, Chest = true},
            [1245402] = {Name = "(HT) Town Square Energy Shard",                    Address = 0x23C0, BitIndex = 0, Chest = true},
            [1245403] = {Name = "(HT) Hinterlands Lightning Shard",                 Address = 0x23C0, BitIndex = 4, Chest = true},
            [1245404] = {Name = "(HT) Hinterlands Mythril Stone",                   Address = 0x23C0, BitIndex = 5, Chest = true},
            [1245405] = {Name = "(HT) Hinterlands AP Boost",                        Address = 0x23C0, BitIndex = 6, Chest = true},
            [1245406] = {Name = "(HT) Candy Cane Lane Mega-Potion",                 Address = 0x23C1, BitIndex = 0, Chest = true},
            [1245407] = {Name = "(HT) Candy Cane Lane Mythril Gem",                 Address = 0x23C1, BitIndex = 1, Chest = true},
            [1245408] = {Name = "(HT) Candy Cane Lane Lightning Stone",             Address = 0x23C1, BitIndex = 2, Chest = true},
            [1245409] = {Name = "(HT) Candy Cane Lane Mythril Stone",               Address = 0x23C1, BitIndex = 3, Chest = true},
            [1245410] = {Name = "(HT) Santa's House Christmas Town Map",            Address = 0x23C1, BitIndex = 6, Chest = true},
            [1245411] = {Name = "(HT) Santa's House AP Boost",                      Address = 0x23C1, BitIndex = 4, Chest = true},
            [1245412] = {Name = "(HT) Prison Keeper Bonus: Sora Slot 1",            Address = 0x3706, BitIndex = 2, Chest = false},
            [1245842] = {Name = "(HT) Prison Keeper Bonus: Donald Slot 1",          Address = 0x3706, BitIndex = 2, Chest = false},
            [1245413] = {Name = "(HT) Oogie Boogie Bonus: Sora Slot 1",             Address = 0x3706, BitIndex = 3, Chest = false},
            [1245874] = {Name = "(HT) Oogie Boogie Bonus: Goofy Slot 1",            Address = 0x3706, BitIndex = 3, Chest = false},
            [1245414] = {Name = "(HT) Oogie Boogie Magnet Element",                 Address = 0x1E53, BitIndex = 2, Chest = false},
            [1245415] = {Name = "(HT2) Lock, Shock and Barrel Bonus: Sora Slot 1",  Address = 0x3709, BitIndex = 0, Chest = false},
            [1245873] = {Name = "(HT2) Lock, Shock and Barrel Bonus: Goofy Slot 1", Address = 0x3709, BitIndex = 0, Chest = false},
            [1245416] = {Name = "(HT2) Present",                                    Address = 0x1E55, BitIndex = 1, Chest = false},
            [1245417] = {Name = "(HT2) Decoy Presents",                             Address = 0x1E55, BitIndex = 4, Chest = false},
            [1245418] = {Name = "(HT2) Experiment Bonus: Sora Slot 1",              Address = 0x3706, BitIndex = 4, Chest = false},
            [1245845] = {Name = "(HT2) Experiment Bonus: Donald Slot 1",            Address = 0x3706, BitIndex = 4, Chest = false},
            [1245419] = {Name = "(HT2) Decisive Pumpkin",                           Address = 0x1E56, BitIndex = 0, Chest = false},
        },

        PR_Checks = {
            [1245423] = {Name = "(PR) Rampart Naval Map",                       Address = 0x23C2, BitIndex = 1, Chest = true},
            [1245424] = {Name = "(PR) Rampart Mythril Stone",                   Address = 0x23C2, BitIndex = 2, Chest = true},
            [1245425] = {Name = "(PR) Rampart Dark Shard",                      Address = 0x23C2, BitIndex = 3, Chest = true},
            [1245426] = {Name = "(PR) Town Dark Stone",                         Address = 0x23C2, BitIndex = 4, Chest = true},
            [1245427] = {Name = "(PR) Town AP Boost",                           Address = 0x23C2, BitIndex = 5, Chest = true},
            [1245428] = {Name = "(PR) Town Mythril Shard",                      Address = 0x23C2, BitIndex = 6, Chest = true},
            [1245429] = {Name = "(PR) Town Mythril Gem",                        Address = 0x23C2, BitIndex = 7, Chest = true},
            [1245430] = {Name = "(PR) Cave Mouth Bright Shard",                 Address = 0x23C3, BitIndex = 1, Chest = true},
            [1245431] = {Name = "(PR) Cave Mouth Mythril Shard",                Address = 0x23C3, BitIndex = 2, Chest = true},
            [1245432] = {Name = "(PR) Isla de Muerta Map",                      Address = 0x1E92, BitIndex = 4, Chest = false},
            [1245433] = {Name = "(PR) Boat Fight Bonus: Sora Slot 1",           Address = 0x370B, BitIndex = 6, Chest = false},
            [1245846] = {Name = "(PR) Boat Fight Bonus: Donald Slot 1",         Address = 0x370B, BitIndex = 6, Chest = false},
            [1245434] = {Name = "(PR) Interceptor Barrels Bonus: Sora Slot 1",  Address = 0x3708, BitIndex = 7, Chest = false},
            [1245880] = {Name = "(PR) Interceptor Barrels Bonus: Goofy Slot 1", Address = 0x3708, BitIndex = 7, Chest = false},
            [1245435] = {Name = "(PR) Powder Store AP Boost 1",                 Address = 0x23CA, BitIndex = 7, Chest = true},
            [1245436] = {Name = "(PR) Powder Store AP Boost 2",                 Address = 0x23CB, BitIndex = 0, Chest = true},
            [1245437] = {Name = "(PR) Moonlight Nook Mythril Shard",            Address = 0x23C3, BitIndex = 4, Chest = true},
            [1245438] = {Name = "(PR) Moonlight Nook Serenity Gem",             Address = 0x23C3, BitIndex = 5, Chest = true},
            [1245439] = {Name = "(PR) Moonlight Nook Power Stone",              Address = 0x23CB, BitIndex = 1, Chest = true},
            [1245440] = {Name = "(PR) Barbossa Bonus: Sora Slot 1",             Address = 0x3706, BitIndex = 5, Chest = false},
            [1245441] = {Name = "(PR) Barbossa Bonus: Sora Slot 2",             Address = 0x3706, BitIndex = 5, Chest = false},
            [1245867] = {Name = "(PR) Barbossa Bonus: Goofy Slot 1",            Address = 0x3706, BitIndex = 5, Chest = false},
            [1245868] = {Name = "(PR) Barbossa Bonus: Goofy Slot 2",            Address = 0x3706, BitIndex = 5, Chest = false},
            [1245442] = {Name = "(PR) Follow the Wind",                         Address = 0x1E93, BitIndex = 6, Chest = false},
            [1245443] = {Name = "(PR2) Grim Reaper 1 Bonus: Sora Slot 1",       Address = 0x370B, BitIndex = 3, Chest = false},
            [1245869] = {Name = "(PR2) Grim Reaper 1 Bonus: Goofy Slot 1",      Address = 0x370B, BitIndex = 3, Chest = false},
            [1245444] = {Name = "(PR2) Interceptor's Hold Feather Charm",       Address = 0x23C3, BitIndex = 3, Chest = true},
            [1245445] = {Name = "(PR2) Seadrift Keep AP Boost",                 Address = 0x23C3, BitIndex = 6, Chest = true},
            [1245446] = {Name = "(PR2) Seadrift Keep Orichalcum",               Address = 0x23C3, BitIndex = 7, Chest = true},
            [1245447] = {Name = "(PR2) Seadrift Keep Meteor Staff",             Address = 0x23CB, BitIndex = 2, Chest = true},
            [1245448] = {Name = "(PR2) Seadrift Row Serenity Gem",              Address = 0x23C4, BitIndex = 0, Chest = true},
            [1245449] = {Name = "(PR2) Seadrift Row King Recipe",               Address = 0x23C4, BitIndex = 1, Chest = true},
            [1245450] = {Name = "(PR2) Seadrift Row Mythril Crystal",           Address = 0x23CB, BitIndex = 3, Chest = true},
            [1245451] = {Name = "(PR2) Seadrift Row Cursed Medallion",          Address = 0x1E95, BitIndex = 2, Chest = false},
            [1245452] = {Name = "(PR2) Seadrift Row Ship Graveyard Map",        Address = 0x1E95, BitIndex = 2, Chest = false},
            [1245453] = {Name = "(PR2) Grim Reaper 2 Bonus: Sora Slot 1",       Address = 0x3706, BitIndex = 6, Chest = false},
            [1245850] = {Name = "(PR2) Grim Reaper 2 Bonus: Donald Slot 1",     Address = 0x3706, BitIndex = 6, Chest = false},
            [1245454] = {Name = "(PR2) Secret Ansem Report 6 (Grim Reaper 2)",  Address = 0x1E95, BitIndex = 7, Chest = false},
        },

        HB_Checks = {
            [1245334] = {Name = "(HB) Marketplace Map",                                                  Address = 0x1D17, BitIndex = 4, Chest = false},
            [1245335] = {Name = "(HB) Borough Drive Recovery",                                           Address = 0x23C6, BitIndex = 1, Chest = true},
            [1245336] = {Name = "(HB) Borough AP Boost",                                                 Address = 0x23C6, BitIndex = 2, Chest = true},
            [1245337] = {Name = "(HB) Borough Hi-Potion",                                                Address = 0x23C6, BitIndex = 3, Chest = true},
            [1245338] = {Name = "(HB) Borough Mythril Shard",                                            Address = 0x23C8, BitIndex = 7, Chest = true},
            [1245339] = {Name = "(HB) Borough Dark Shard",                                               Address = 0x23DB, BitIndex = 1, Chest = true},
            [1245340] = {Name = "(HB) Merlin's House Membership Card",                                   Address = 0x1D10, BitIndex = 6, Chest = false},
            [1245341] = {Name = "(HB) Merlin's House Blizzard Element",                                  Address = 0x1D10, BitIndex = 6, Chest = false},
            [1245342] = {Name = "(HB) Bailey Bonus: Sora Slot 1",                                        Address = 0x3709, BitIndex = 7, Chest = false},
            [1245343] = {Name = "(HB) Bailey Secret Ansem Report 7",                                     Address = 0x3709, BitIndex = 7, Chest = false},
            [1245344] = {Name = "(HB) Baseball Charm",                                                   Address = 0x3709, BitIndex = 7, Chest = false},
            [1245345] = {Name = "(HB2) Postern Castle Perimeter Map",                                    Address = 0x23C9, BitIndex = 4, Chest = true},
            [1245346] = {Name = "(HB2) Postern Mythril Gem",                                             Address = 0x23C5, BitIndex = 4, Chest = true},
            [1245347] = {Name = "(HB2) Postern AP Boost",                                                Address = 0x23C5, BitIndex = 5, Chest = true},
            [1245348] = {Name = "(HB2) Corridors Mythril Stone",                                         Address = 0x23C6, BitIndex = 7, Chest = true},
            [1245349] = {Name = "(HB2) Corridors Mythril Crystal",                                       Address = 0x23C7, BitIndex = 0, Chest = true},
            [1245350] = {Name = "(HB2) Corridors Dark Crystal",                                          Address = 0x23C7, BitIndex = 1, Chest = true},
            [1245351] = {Name = "(HB2) Corridors AP Boost",                                              Address = 0x23C9, BitIndex = 1, Chest = true},
            [1245352] = {Name = "(HB2) Ansem's Study Master Form",                                       Address = 0x1D12, BitIndex = 6, Chest = false},
            [1245353] = {Name = "(HB2) Ansem's Study Sleeping Lion",                                     Address = 0x1D12, BitIndex = 6, Chest = false},
            [1245354] = {Name = "(HB2) Ansem's Study Skill Recipe",                                      Address = 0x23C4, BitIndex = 7, Chest = true},
            [1245355] = {Name = "(HB2) Ansem's Study Ukulele Charm",                                     Address = 0x23C4, BitIndex = 6, Chest = true},
            [1245356] = {Name = "(HB2) Restoration Site Moon Recipe",                                    Address = 0x23C9, BitIndex = 3, Chest = true},
            [1245357] = {Name = "(HB2) Restoration Site AP Boost",                                       Address = 0x23DB, BitIndex = 2, Chest = true},
            [1245358] = {Name = "(HB2) Demyx Bonus: Sora Slot 1",                                        Address = 0x3707, BitIndex = 4, Chest = false},
            [1245359] = {Name = "(HB2) Demyx Bonus: Sora Slot 2",                                        Address = 0x3707, BitIndex = 4, Chest = false},
            [1245838] = {Name = "(HB2) Demyx Bonus: Donald Slot 1",                                      Address = 0x3707, BitIndex = 4, Chest = false},
            [1245360] = {Name = "(HB2) FF Fights Cure Element",                                          Address = 0x1D14, BitIndex = 6, Chest = false},
            [1245361] = {Name = "(HB2) Crystal Fissure Torn Pages",                                      Address = 0x23C4, BitIndex = 2, Chest = true},
            [1245362] = {Name = "(HB2) Crystal Fissure The Great Maw Map",                               Address = 0x23D9, BitIndex = 1, Chest = true},
            [1245363] = {Name = "(HB2) Crystal Fissure Energy Crystal",                                  Address = 0x23C4, BitIndex = 3, Chest = true},
            [1245364] = {Name = "(HB2) Crystal Fissure AP Boost",                                        Address = 0x23C4, BitIndex = 4, Chest = true},
            [1245365] = {Name = "(HB2) 1000 Heartless",                                                  Address = 0x370B, BitIndex = 4, Chest = false},
            [1245366] = {Name = "(HB2) 1000 Heartless Secret Ansem Report 1",                            Address = 0x1D19, BitIndex = 3, Chest = false},
            [1245367] = {Name = "(HB2) 1000 Heartless Ice Cream",                                        Address = 0x1D23, BitIndex = 0, Chest = false},
            [1245368] = {Name = "(HB2) 1000 Heartless Picture",                                          Address = 0x1D23, BitIndex = 0, Chest = false},
            [1245369] = {Name = "(HB2) Postern Gull Wing",                                               Address = 0x23D9, BitIndex = 3, Chest = true},
            [1245370] = {Name = "(HB2) Heartless Manufactory Cosmic Chain",                              Address = 0x23C9, BitIndex = 5, Chest = true},
            [1245371] = {Name = "Sephiroth Bonus: Sora Slot 1",                                          Address = 0x3708, BitIndex = 3, Chest = false},
            [1245372] = {Name = "Sephiroth Fenrir",                                                      Address = 0x1D1F, BitIndex = 7, Chest = false},
            [1245373] = {Name = "(HB2) Winner's Proof",                                                  Address = 0x1D27, BitIndex = 5, Chest = false},
            [1245374] = {Name = "(HB2) Proof of Peace",                                                  Address = 0x1D27, BitIndex = 5, Chest = false},
            [1245376] = {Name = "(CoR) Depths AP Boost",                                                 Address = 0x23DC, BitIndex = 2, Chest = true},
            [1245377] = {Name = "(CoR) Depths Power Crystal",                                            Address = 0x23DC, BitIndex = 3, Chest = true},
            [1245378] = {Name = "(CoR) Depths Frost Crystal",                                            Address = 0x23DC, BitIndex = 4, Chest = true},
            [1245379] = {Name = "(CoR) Depths Manifest Illusion",                                        Address = 0x23DC, BitIndex = 5, Chest = true},
            [1245380] = {Name = "(CoR) Depths AP Boost 2",                                               Address = 0x23DC, BitIndex = 6, Chest = true},
            [1245381] = {Name = "(CoR) Mineshaft Lower Level Depths of Remembrance Map",                 Address = 0x23DE, BitIndex = 4, Chest = true},
            [1245382] = {Name = "(CoR) Mineshaft Lower Level AP Boost",                                  Address = 0x23DE, BitIndex = 2, Chest = true},
            [1245383] = {Name = "(CoR) Depths Upper Level Remembrance Gem",                              Address = 0x23DC, BitIndex = 7, Chest = true},
            [1245384] = {Name = "(CoR) Mining Area Serenity Gem",                                        Address = 0x23DD, BitIndex = 0, Chest = true},
            [1245385] = {Name = "(CoR) Mining Area AP Boost",                                            Address = 0x23DD, BitIndex = 1, Chest = true},
            [1245386] = {Name = "(CoR) Mining Area Serenity Crystal",                                    Address = 0x23DD, BitIndex = 2, Chest = true},
            [1245387] = {Name = "(CoR) Mining Area Manifest Illusion",                                   Address = 0x23DD, BitIndex = 3, Chest = true},
            [1245388] = {Name = "(CoR) Mining Area Serenity Gem 2",                                      Address = 0x23DD, BitIndex = 4, Chest = true},
            [1245389] = {Name = "(CoR) Mining Area Dark Remembrance Map",                                Address = 0x23DD, BitIndex = 5, Chest = true},
            [1245390] = {Name = "(CoR) Mineshaft Mid Level Power Boost",                                 Address = 0x23DE, BitIndex = 5, Chest = true},
            [1245391] = {Name = "(CoR) Engine Chamber Serenity Crystal",                                 Address = 0x23DD, BitIndex = 6, Chest = true},
            [1245392] = {Name = "(CoR) Engine Chamber Remembrance Crystal",                              Address = 0x23DD, BitIndex = 7, Chest = true},
            [1245393] = {Name = "(CoR) Engine Chamber AP Boost",                                         Address = 0x23DE, BitIndex = 0, Chest = true},
            [1245394] = {Name = "(CoR) Engine Chamber Manifest Illusion",                                Address = 0x23DE, BitIndex = 1, Chest = true},
            [1245395] = {Name = "(CoR) Mineshaft Upper Level Magic Boost",                               Address = 0x23DE, BitIndex = 6, Chest = true},
            [1245396] = {Name = "(CoR) Mineshaft Upper Level AP Boost",                                  Address = 0x23DE, BitIndex = 3, Chest = true},
            [1245397] = {Name = "Transport to Remembrance",                                              Address = 0x370D, BitIndex = 0, Chest = false},
            [1245645] = {Name = "(Post AG2: Peddler's Shop) Lexaeus Bonus: Sora Slot 1",                 Address = 0x370C, BitIndex = 1, Chest = false},
            [1245646] = {Name = "(Post AG2: Peddler's Shop) AS Lexaeus",                                 Address = 0x370C, BitIndex = 1, Chest = false},
            [1245647] = {Name = "(Post AG2: Peddler's Shop) Data Lexaeus",                               Address = 0x370C, BitIndex = 1, Chest = false},
            [1245606] = {Name = "(Post TR:Hall of the Cornerstone) Marluxia Bonus: Sora Slot 1",         Address = 0x370C, BitIndex = 3, Chest = false},
            [1245607] = {Name = "(Post TR:Hall of the Cornerstone) AS Marluxia",                         Address = 0x370C, BitIndex = 3, Chest = false},
            [1245608] = {Name = "(Post TR:Hall of the Cornerstone) Data Marluxia",                       Address = 0x370C, BitIndex = 3, Chest = false},
            [1245546] = {Name = "(Post OC2: Cave of the Dead Inner Chamber) Zexion Bonus: Sora Slot 1",  Address = 0x370C, BitIndex = 2, Chest = false},
            [1245882] = {Name = "(Post OC2: Cave of the Dead Inner Chamber) Zexion Bonus: Goofy Slot 1", Address = 0x370C, BitIndex = 2, Chest = false},
            [1245547] = {Name = "(Post OC2: Cave of the Dead Inner Chamber) AS Zexion",                  Address = 0x370C, BitIndex = 2, Chest = false},
            [1245548] = {Name = "(Post OC2: Cave of the Dead Inner Chamber) Data Zexion",                Address = 0x370C, BitIndex = 2, Chest = false},
            [1245477] = {Name = "(Post SP2: Central Computer Core) Larxene Bonus: Sora Slot 1",          Address = 0x370C, BitIndex = 4, Chest = false},
            [1245478] = {Name = "(Post SP2: Central Computer Core) AS Larxene",                          Address = 0x370C, BitIndex = 4, Chest = false},
            [1245479] = {Name = "(Post SP2: Central Computer Core) Data Larxene",                        Address = 0x370C, BitIndex = 4, Chest = false},
            [1245420] = {Name = "(Post HT2: Yuletide Hill) Vexen Bonus: Sora Slot 1",                    Address = 0x370C, BitIndex = 0, Chest = false},
            [1245421] = {Name = "(Post HT2: Yuletide Hill) AS Vexen",                                    Address = 0x370C, BitIndex = 0, Chest = false},
            [1245422] = {Name = "(Post HT2: Yuletide Hill) Data Vexen",                                  Address = 0x370C, BitIndex = 0, Chest = false},
            [1245375] = {Name = "(Post HB2: Restoration Site) Data Demyx",                               Address = 0x1D26, BitIndex = 5, Chest = false},
            [1245806] = {Name = "Garden of Assemblage Map",                                              Address = 0x23DF, BitIndex = 1, Chest = true},
            [1245807] = {Name = "GoA Lost Illusion",                                                     Address = 0x23DF, BitIndex = 2, Chest = true},
            [1245808] = {Name = "Proof of Nonexistence Location",                                        Address = 0x23DF, BitIndex = 3, Chest = true},
            [1245812] = {Name = "Kingdom Key Slot",                                                      Address = 0x1D27, BitIndex = 3, Chest = false},
            [1245854] = {Name = "Mage's Staff Slot",                                                      Address = 0x1D27, BitIndex = 3, Chest = false},
            [1245891] = {Name = "Knight's Shield Slot",                                                  Address = 0x1D27, BitIndex = 3, Chest = false},
        },

        PL_Checks = {
            [1245301] = {Name = "(PL) Gorge Savannah Map",               Address = 0x23D9, BitIndex = 4, Chest = true},
            [1245302] = {Name = "(PL) Gorge Dark Gem",                   Address = 0x23CF, BitIndex = 0, Chest = true},
            [1245303] = {Name = "(PL) Gorge Mythril Stone",              Address = 0x23CF, BitIndex = 1, Chest = true},
            [1245304] = {Name = "(PL) Elephant Graveyard Frost Gem",     Address = 0x23CE, BitIndex = 5, Chest = true},
            [1245305] = {Name = "(PL) Elephant Graveyard Mythril Stone", Address = 0x23CE, BitIndex = 6, Chest = true},
            [1245306] = {Name = "(PL) Elephant Graveyard Bright Stone",  Address = 0x23CE, BitIndex = 7, Chest = true},
            [1245307] = {Name = "(PL) Elephant Graveyard AP Boost",      Address = 0x23DB, BitIndex = 3, Chest = true},
            [1245308] = {Name = "(PL) Elephant Graveyard Mythril Shard", Address = 0x23DB, BitIndex = 4, Chest = true},
            [1245309] = {Name = "(PL) Pride Rock Map",                   Address = 0x23D0, BitIndex = 3, Chest = true},
            [1245310] = {Name = "(PL) Pride Rock Mythril Stone",         Address = 0x23CD, BitIndex = 4, Chest = true},
            [1245311] = {Name = "(PL) Pride Rock Serenity Crystal",      Address = 0x23CD, BitIndex = 5, Chest = true},
            [1245312] = {Name = "(PL) Wildebeest Valley Energy Stone",   Address = 0x23CE, BitIndex = 0, Chest = true},
            [1245313] = {Name = "(PL) Wildebeest Valley AP Boost",       Address = 0x23CE, BitIndex = 1, Chest = true},
            [1245314] = {Name = "(PL) Wildebeest Valley Mythril Gem",    Address = 0x23CE, BitIndex = 2, Chest = true},
            [1245315] = {Name = "(PL) Wildebeest Valley Mythril Stone",  Address = 0x23CE, BitIndex = 3, Chest = true},
            [1245316] = {Name = "(PL) Wildebeest Valley Lucid Gem",      Address = 0x23CE, BitIndex = 4, Chest = true},
            [1245317] = {Name = "(PL) Wastelands Mythril Shard",         Address = 0x23CF, BitIndex = 2, Chest = true},
            [1245318] = {Name = "(PL) Wastelands Serenity Gem",          Address = 0x23CF, BitIndex = 3, Chest = true},
            [1245319] = {Name = "(PL) Wastelands Mythril Stone",         Address = 0x23CF, BitIndex = 4, Chest = true},
            [1245320] = {Name = "(PL) Jungle Serenity Gem",              Address = 0x23CF, BitIndex = 5, Chest = true},
            [1245321] = {Name = "(PL) Jungle Mythril Stone",             Address = 0x23CF, BitIndex = 6, Chest = true},
            [1245322] = {Name = "(PL) Jungle Serenity Crystal",          Address = 0x23CF, BitIndex = 7, Chest = true},
            [1245323] = {Name = "(PL) Oasis Map",                        Address = 0x23D0, BitIndex = 0, Chest = true},
            [1245324] = {Name = "(PL) Oasis Torn Pages",                 Address = 0x23D9, BitIndex = 5, Chest = true},
            [1245325] = {Name = "(PL) Oasis AP Boost",                   Address = 0x23D0, BitIndex = 1, Chest = true},
            [1245326] = {Name = "(PL) Circle of Life",                   Address = 0x1DD2, BitIndex = 1, Chest = false},
            [1245327] = {Name = "(PL) Hyenas 1 Bonus: Sora Slot 1",      Address = 0x370A, BitIndex = 1, Chest = false},
            [1245871] = {Name = "(PL) Hyenas 1 Bonus: Goofy Slot 1",     Address = 0x370A, BitIndex = 1, Chest = false},
            [1245328] = {Name = "(PL) Scar Bonus: Sora Slot 1",          Address = 0x3707, BitIndex = 5, Chest = false},
            [1245843] = {Name = "(PL) Scar Bonus: Donald Slot 1",        Address = 0x3707, BitIndex = 5, Chest = false},
            [1245329] = {Name = "(PL) Scar Fire Element",                Address = 0x1DD4, BitIndex = 7, Chest = false},
            [1245330] = {Name = "(PL2) Hyenas 2 Bonus: Sora Slot 1",     Address = 0x370A, BitIndex = 2, Chest = false},
            [1245872] = {Name = "(PL2) Hyenas 2 Bonus: Goofy Slot 1",    Address = 0x370A, BitIndex = 2, Chest = false},
            [1245331] = {Name = "(PL2) Groundshaker Bonus: Sora Slot 1", Address = 0x3707, BitIndex = 6, Chest = false},
            [1245332] = {Name = "(PL2) Groundshaker Bonus: Sora Slot 2", Address = 0x3707, BitIndex = 6, Chest = false},
        },

        TT_Checks = {
            [1245273] = {Name = "(STT) Twilight Town Map",                         Address = 0x1CD6, BitIndex = 3, Chest = false},
            [1245274] = {Name = "(STT) Munny Pouch Olette",                        Address = 0x1CD6, BitIndex = 5, Chest = false},
            [1245275] = {Name = "(STT) Station Dusks",                             Address = 0x370A, BitIndex = 6, Chest = false},
            [1245276] = {Name = "(STT) Station of Serenity Potion",                Address = 0x23CA, BitIndex = 1, Chest = true},
            [1245277] = {Name = "(STT) Station of Calling Potion",                 Address = 0x23D7, BitIndex = 1, Chest = true},
            [1245278] = {Name = "(STT) Twilight Thorn",                            Address = 0x3708, BitIndex = 1, Chest = false},
            [1245279] = {Name = "(STT) Axel 1",                                    Address = 0x370D, BitIndex = 1, Chest = false},
            [1245280] = {Name = "(STT) Junk Champion Belt",                        Address = 0x1CDC, BitIndex = 2, Chest = false},
            [1245281] = {Name = "(STT) Junk Medal",                                Address = 0x1CDC, BitIndex = 2, Chest = false},
            [1245282] = {Name = "(STT) The Struggle Trophy",                       Address = 0x1CDC, BitIndex = 2, Chest = false},
            [1245283] = {Name = "(STT) Central Station Potion 1",                  Address = 0x23D1, BitIndex = 5, Chest = true},
            [1245284] = {Name = "(STT) Central Station Hi-Potion",                 Address = 0x23D1, BitIndex = 6, Chest = true},
            [1245285] = {Name = "(STT) Central Station Potion 2",                  Address = 0x23D1, BitIndex = 7, Chest = true},
            [1245286] = {Name = "(STT) Sunset Terrace Ability Ring",               Address = 0x23D2, BitIndex = 3, Chest = true},
            [1245287] = {Name = "(STT) Sunset Terrace Hi-Potion",                  Address = 0x23D2, BitIndex = 4, Chest = true},
            [1245288] = {Name = "(STT) Sunset Terrace Potion 1",                   Address = 0x23D2, BitIndex = 5, Chest = true},
            [1245289] = {Name = "(STT) Sunset Terrace Potion 2",                   Address = 0x23D2, BitIndex = 6, Chest = true},
            [1245290] = {Name = "(STT) Mansion Foyer Hi-Potion",                   Address = 0x23D4, BitIndex = 2, Chest = true},
            [1245291] = {Name = "(STT) Mansion Foyer Potion 1",                    Address = 0x23D4, BitIndex = 3, Chest = true},
            [1245292] = {Name = "(STT) Mansion Foyer Potion 2",                    Address = 0x23D4, BitIndex = 4, Chest = true},
            [1245293] = {Name = "(STT) Mansion Dining Room Elven Bandanna",        Address = 0x23D5, BitIndex = 0, Chest = true},
            [1245294] = {Name = "(STT) Mansion Dining Room Potion",                Address = 0x23D5, BitIndex = 1, Chest = true},
            [1245295] = {Name = "(STT) Namine's Sketches",                         Address = 0x1CE0, BitIndex = 6, Chest = false},
            [1245296] = {Name = "(STT) Mansion Map",                               Address = 0x1CE0, BitIndex = 6, Chest = false},
            [1245297] = {Name = "(STT) Mansion Library Hi-Potion",                 Address = 0x23D5, BitIndex = 4, Chest = true},
            [1245298] = {Name = "(STT) Axel 2",                                    Address = 0x3708, BitIndex = 2, Chest = false},
            [1245299] = {Name = "(STT) Mansion Basement Corridor Hi-Potion",       Address = 0x23D6, BitIndex = 0, Chest = false},

            [1245221] = {Name = "(TT) Old Mansion Potion",                         Address = 0x23D4, BitIndex = 0, Chest = true},
            [1245222] = {Name = "(TT) Old Mansion Mythril Shard",                  Address = 0x23D4, BitIndex = 1, Chest = true},
            [1245223] = {Name = "(TT) The Woods Potion",                           Address = 0x23D3, BitIndex = 3, Chest = true},
            [1245224] = {Name = "(TT) The Woods Mythril Shard",                    Address = 0x23D3, BitIndex = 4, Chest = true},
            [1245225] = {Name = "(TT) The Woods Hi-Potion",                        Address = 0x23D3, BitIndex = 5, Chest = true},
            [1245226] = {Name = "(TT) Tram Common Hi-Potion",                      Address = 0x23D0, BitIndex = 5, Chest = true},
            [1245227] = {Name = "(TT) Tram Common AP Boost",                       Address = 0x23D0, BitIndex = 6, Chest = true},
            [1245228] = {Name = "(TT) Tram Common Tent",                           Address = 0x23D0, BitIndex = 7, Chest = true},
            [1245229] = {Name = "(TT) Tram Common Mythril Shard 1",                Address = 0x23D1, BitIndex = 0, Chest = true},
            [1245230] = {Name = "(TT) Tram Common Potion 1",                       Address = 0x23D1, BitIndex = 1, Chest = true},
            [1245231] = {Name = "(TT) Tram Common Mythril Shard 2",                Address = 0x23D1, BitIndex = 2, Chest = true},
            [1245232] = {Name = "(TT) Tram Common Potion 2",                       Address = 0x23D8, BitIndex = 5, Chest = true},
            [1245233] = {Name = "(TT) Station Plaza Secret Ansem Report 2",        Address = 0x1CE3, BitIndex = 3, Chest = false},
            [1245234] = {Name = "(TT) Munny Pouch Mickey",                         Address = 0x1CE3, BitIndex = 3, Chest = false},
            [1245235] = {Name = "(TT) Crystal Orb",                                Address = 0x1CE3, BitIndex = 3, Chest = false},
            [1245236] = {Name = "(TT) Central Station Tent",                       Address = 0x23D2, BitIndex = 0, Chest = true},
            [1245237] = {Name = "(TT) Central Station Hi-Potion",                  Address = 0x23D2, BitIndex = 1, Chest = true},
            [1245238] = {Name = "(TT) Central Station Mythril Shard",              Address = 0x23D2, BitIndex = 2, Chest = true},
            [1245239] = {Name = "(TT) The Tower Potion",                           Address = 0x23D6, BitIndex = 2, Chest = true},
            [1245240] = {Name = "(TT) The Tower Hi-Potion",                        Address = 0x23D6, BitIndex = 3, Chest = true},
            [1245241] = {Name = "(TT) The Tower Ether",                            Address = 0x23DB, BitIndex = 7, Chest = true},
            [1245242] = {Name = "(TT) Tower Entryway Ether",                       Address = 0x23D6, BitIndex = 4, Chest = true},
            [1245243] = {Name = "(TT) Tower Entryway Mythril Shard",               Address = 0x23D6, BitIndex = 5, Chest = true},
            [1245244] = {Name = "(TT) Sorcerer's Loft Tower Map",                  Address = 0x23D6, BitIndex = 6, Chest = true},
            [1245245] = {Name = "(TT) Tower Wardrobe Mythril Stone",               Address = 0x23D6, BitIndex = 7, Chest = true},
            [1245246] = {Name = "(TT) Star Seeker",                                Address = 0x1CE5, BitIndex = 2, Chest = false},
            [1245247] = {Name = "(TT) Valor Form",                                 Address = 0x1CE5, BitIndex = 2, Chest = false},
            [1245248] = {Name = "(TT2) Seifer's Trophy",                           Address = 0x1CE6, BitIndex = 4, Chest = false},
            [1245249] = {Name = "(TT2) Oathkeeper",                                Address = 0x1CE6, BitIndex = 7, Chest = false},
            [1245250] = {Name = "(TT2) Limit Form",                                Address = 0x1CE6, BitIndex = 7, Chest = false},
            [1245251] = {Name = "(TT3) Underground Concourse Mythril Gem",         Address = 0x23D8, BitIndex = 0, Chest = true},
            [1245253] = {Name = "(TT3) Underground Concourse Orichalcum",          Address = 0x23D8, BitIndex = 2, Chest = true},
            [1245252] = {Name = "(TT3) Underground Concourse AP Boost",            Address = 0x23D8, BitIndex = 1, Chest = true},
            [1245254] = {Name = "(TT3) Underground Concourse Mythril Crystal",     Address = 0x23D8, BitIndex = 3, Chest = true},
            [1245255] = {Name = "(TT3) Tunnelway Orichalcum",                      Address = 0x23D7, BitIndex = 6, Chest = true},
            [1245256] = {Name = "(TT3) Tunnelway Mythril Crystal",                 Address = 0x23D7, BitIndex = 7, Chest = true},
            [1245257] = {Name = "(TT3) Sunset Terrace Orichalcum+",                Address = 0x23D2, BitIndex = 7, Chest = true},
            [1245258] = {Name = "(TT3) Sunset Terrace Mythril Shard",              Address = 0x23D3, BitIndex = 0, Chest = true},
            [1245259] = {Name = "(TT3) Sunset Terrace Mythril Crystal",            Address = 0x23D3, BitIndex = 1, Chest = true},
            [1245260] = {Name = "(TT3) Sunset Terrace AP Boost",                   Address = 0x23D3, BitIndex = 2, Chest = true},
            [1245261] = {Name = "(TT3) Mansion Nobodies Bonus: Sora Slot 1",       Address = 0x370B, BitIndex = 0, Chest = false},
            [1245847] = {Name = "(TT3) Mansion Nobodies Bonus: Donald Slot 1",     Address = 0x370B, BitIndex = 0, Chest = false},
            [1245262] = {Name = "(TT3) Mansion Foyer Mythril Crystal",             Address = 0x23D4, BitIndex = 5, Chest = true},
            [1245263] = {Name = "(TT3) Mansion Foyer Mythril Stone",               Address = 0x23D4, BitIndex = 6, Chest = true},
            [1245264] = {Name = "(TT3) Mansion Foyer Serenity Crystal",            Address = 0x23D4, BitIndex = 7, Chest = true},
            [1245265] = {Name = "(TT3) Mansion Dining Room Mythril Crystal",       Address = 0x23D5, BitIndex = 2, Chest = true},
            [1245266] = {Name = "(TT3) Mansion Dining Room Mythril Stone",         Address = 0x23D5, BitIndex = 3, Chest = true},
            [1245267] = {Name = "(TT3) Mansion Library Orichalcum",                Address = 0x23D5, BitIndex = 5, Chest = true},
            [1245268] = {Name = "(TT3) Beam Secret Ansem Report 10",               Address = 0x1CE8, BitIndex = 3, Chest = false},
            [1245269] = {Name = "(TT3) Mansion Basement Corridor Ultimate Recipe", Address = 0x23D6, BitIndex = 1, Chest = true},
            [1245270] = {Name = "(TT3) Betwixt and Between",                       Address = 0x370B, BitIndex = 7, Chest = false},
            [1245271] = {Name = "(TT3) Betwixt and Between Bond of Flame",         Address = 0x1CE9, BitIndex = 1, Chest = false},
            [1245272] = {Name = "(Post TT3: Betwixt and Between) Data Axel",       Address = 0x1CEB, BitIndex = 4, Chest = false},
        },

        TWTNW_Checks = {
            [1245184] = {Name = "(TWTNW) Fragment Crossing Mythril Stone",              Address = 0x23CB, BitIndex = 4, Chest = true},
            [1245185] = {Name = "(TWTNW) Fragment Crossing Mythril Crystal",            Address = 0x23CB, BitIndex = 5, Chest = true},
            [1245186] = {Name = "(TWTNW) Fragment Crossing AP Boost",                   Address = 0x23CB, BitIndex = 6, Chest = true},
            [1245187] = {Name = "(TWTNW) Fragment Crossing Orichalcum",                 Address = 0x23CB, BitIndex = 7, Chest = true},
            [1245188] = {Name = "(TWTNW2) Roxas Bonus: Sora Slot 1",                    Address = 0x370C, BitIndex = 5, Chest = false},
            [1245189] = {Name = "(TWTNW2) Roxas Bonus: Sora Slot 2",                    Address = 0x370C, BitIndex = 5, Chest = false},
            [1245190] = {Name = "(TWTNW2) Roxas Secret Ansem Report 8",                 Address = 0x1ED1, BitIndex = 1, Chest = false},
            [1245191] = {Name = "(TWTNW2) Two Become One",                              Address = 0x1ED1, BitIndex = 1, Chest = false},
            [1245192] = {Name = "(TWTNW2) Memory's Skyscaper Mythril Crystal",          Address = 0x23CD, BitIndex = 3, Chest = true},
            [1245193] = {Name = "(TWTNW2) Memory's Skyscaper AP Boost",                 Address = 0x23DC, BitIndex = 0, Chest = true},
            [1245194] = {Name = "(TWTNW2) Memory's Skyscaper Mythril Stone",            Address = 0x23DC, BitIndex = 1, Chest = true},
            [1245195] = {Name = "(TWTNW2) The Brink of Despair Dark City Map",          Address = 0x23CA, BitIndex = 5, Chest = true},
            [1245196] = {Name = "(TWTNW2) The Brink of Despair Orichalcum+",            Address = 0x23DA, BitIndex = 2, Chest = true},
            [1245197] = {Name = "(TWTNW2) Nothing's Call Mythril Gem",                  Address = 0x23CC, BitIndex = 0, Chest = true},
            [1245198] = {Name = "(TWTNW2) Nothing's Call Orichalcum",                   Address = 0x23CC, BitIndex = 1, Chest = true},
            [1245199] = {Name = "(TWTNW2) Twilight's View Cosmic Belt",                 Address = 0x23CA, BitIndex = 6, Chest = true},
            [1245200] = {Name = "(TWTNW2) Xigbar Bonus: Sora Slot 1",                   Address = 0x3706, BitIndex = 7, Chest = false},
            [1245201] = {Name = "(TWTNW2) Xigbar Secret Ansem Report 3",                Address = 0x1ED2, BitIndex = 2, Chest = false},
            [1245202] = {Name = "(TWTNW2) Naught's Skyway Mythril Gem",                 Address = 0x23CC, BitIndex = 2, Chest = true},
            [1245203] = {Name = "(TWTNW2) Naught's Skyway Orichalcum",                  Address = 0x23CC, BitIndex = 3, Chest = true},
            [1245204] = {Name = "(TWTNW2) Naught's Skyway Mythril Crystal",             Address = 0x23CC, BitIndex = 4, Chest = true},
            [1245205] = {Name = "(TWTNW2) Oblivion",                                    Address = 0x1ED2, BitIndex = 4, Chest = false},
            [1245206] = {Name = "(TWTNW2) Castle That Never Was Map",                   Address = 0x1ED2, BitIndex = 4, Chest = false},
            [1245207] = {Name = "(TWTNW2) Luxord Bonus: Sora Slot 2",                   Address = 0x3707, BitIndex = 0, Chest = false},
            [1245208] = {Name = "(TWTNW2) Luxord Bonus: Sora Slot 1",                   Address = 0x3707, BitIndex = 0, Chest = false},
            [1245209] = {Name = "(TWTNW2) Luxord Secret Ansem Report 9",                Address = 0x1ED2, BitIndex = 7, Chest = false},
            [1245210] = {Name = "(TWTNW2) Saix Bonus: Sora Slot 1",                     Address = 0x3707, BitIndex = 1, Chest = false},
            [1245211] = {Name = "(TWTNW2) Saix Secret Ansem Report 12",                 Address = 0x1ED3, BitIndex = 2, Chest = false},
            [1245212] = {Name = "(TWTNW3) Secret Ansem Report 11 (Pre-Xemnas 1)",       Address = 0x1ED3, BitIndex = 6, Chest = false},
            [1245213] = {Name = "(TWTNW3) Ruin and Creation's Passage Mythril Stone",   Address = 0x23CC, BitIndex = 7, Chest = true},
            [1245214] = {Name = "(TWTNW3) Ruin and Creation's Passage AP Boost",        Address = 0x23CD, BitIndex = 0, Chest = true},
            [1245215] = {Name = "(TWTNW3) Ruin and Creation's Passage Mythril Crystal", Address = 0x23CD, BitIndex = 1, Chest = true},
            [1245216] = {Name = "(TWTNW3) Ruin and Creation's Passage Orichalcum",      Address = 0x23CD, BitIndex = 2, Chest = true},
            [1245217] = {Name = "(TWTNW3) Xemnas 1 Bonus: Sora Slot 1",                 Address = 0x3707, BitIndex = 2, Chest = false},
            [1245218] = {Name = "(TWTNW3) Xemnas 1 Bonus: Sora Slot 2",                 Address = 0x3707, BitIndex = 2, Chest = false},
            [1245219] = {Name = "(TWTNW3) Xemnas 1 Secret Ansem Report 13",             Address = 0x1ED4, BitIndex = 5, Chest = false},
            [1]       = {Name = "Final Xemnas",                                         Address = 0x1ED8, BitIndex = 1, Chest = false},
            [1245220] = {Name = "(Post TWTNW3: The Altar of Naught) Data Xemnas",       Address = 0x1EDA, BitIndex = 2, Chest = false},
            [1245677] = {Name = "(Post LoD2: Summit) Data Xigbar",                      Address = 0x1ED9, BitIndex = 7, Chest = false},
            [1245333] = {Name = "(Post PL2: Peak) Data Saix",                           Address = 0x1EDA, BitIndex = 0, Chest = false},
            [1245455] = {Name = "(Post PR2: Treasure Heap) Data Luxord",                Address = 0x1EDA, BitIndex = 1, Chest = false},
            [1245300] = {Name = "(Post STT: Mansion Pod Room) Data Roxas",              Address = 0x1ED9, BitIndex = 6, Chest = false},
        },

        AT_Checks = {
            [1245898] = {Name = "(AT) Undersea Kingdom Map",     Address = 0x1DF4, BitIndex = 2, Chest = false},
            [1245899] = {Name = "(AT) Mysterious Abyss",         Address = 0x1DF5, BitIndex = 3, Chest = false},
            [1245900] = {Name = "(AT) Musical Blizzard Element", Address = 0x1DF4, BitIndex = 1, Chest = false},
            [1245901] = {Name = "(AT) Musical Orichalcum+",      Address = 0x1DF4, BitIndex = 1, Chest = false},
        },
    }
    return Worlds
end

function LocationDefs:FormLevels()

    ValorForm ={
        [1245776] = {Name = "Valor level 2", Address = 0x32F6, BitIndex = 2},
        [1245777] = {Name = "Valor level 3", Address = 0x32F6, BitIndex = 3},
        [1245778] = {Name = "Valor level 4", Address = 0x32F6, BitIndex = 4},
        [1245779] = {Name = "Valor level 5", Address = 0x32F6, BitIndex = 5},
        [1245780] = {Name = "Valor level 6", Address = 0x32F6, BitIndex = 6},
        [1245781] = {Name = "Valor level 7", Address = 0x32F6, BitIndex = 7},
    }
    WisdomForm = {
        [1245782] = {Name = "Wisdom level 2", Address = 0x332E, BitIndex = 2},
        [1245783] = {Name = "Wisdom level 3", Address = 0x332E, BitIndex = 3},
        [1245784] = {Name = "Wisdom level 4", Address = 0x332E, BitIndex = 4},
        [1245785] = {Name = "Wisdom level 5", Address = 0x332E, BitIndex = 5},
        [1245786] = {Name = "Wisdom level 6", Address = 0x332E, BitIndex = 6},
        [1245787] = {Name = "Wisdom level 7", Address = 0x332E, BitIndex = 7},
    }
    LimitForm = {
        [1245788] = {Name = "Limit level 2", Address = 0x3366, BitIndex = 2},
        [1245789] = {Name = "Limit level 3", Address = 0x3366, BitIndex = 3},
        [1245790] = {Name = "Limit level 4", Address = 0x3366, BitIndex = 4},
        [1245791] = {Name = "Limit level 5", Address = 0x3366, BitIndex = 5},
        [1245792] = {Name = "Limit level 6", Address = 0x3366, BitIndex = 6},
        [1245793] = {Name = "Limit level 7", Address = 0x3366, BitIndex = 7},
    }
    MasterForm = {
        [1245794] = {Name = "Master level 2", Address = 0x339E, BitIndex = 2},
        [1245795] = {Name = "Master level 3", Address = 0x339E, BitIndex = 3},
        [1245796] = {Name = "Master level 4", Address = 0x339E, BitIndex = 4},
        [1245797] = {Name = "Master level 5", Address = 0x339E, BitIndex = 5},
        [1245798] = {Name = "Master level 6", Address = 0x339E, BitIndex = 6},
        [1245799] = {Name = "Master level 7", Address = 0x339E, BitIndex = 7},
    }
    FinalForm = {
        [1245800] = {Name = "Final level 2", Address = 0x33D6, BitIndex = 2},
        [1245801] = {Name = "Final level 3", Address = 0x33D6, BitIndex = 3},
        [1245802] = {Name = "Final level 4", Address = 0x33D6, BitIndex = 4},
        [1245803] = {Name = "Final level 5", Address = 0x33D6, BitIndex = 5},
        [1245804] = {Name = "Final level 6", Address = 0x33D6, BitIndex = 6},
        [1245805] = {Name = "Final level 7", Address = 0x33D6, BitIndex = 7},
    }
    SummonLevels = {
        [1245902] = {Name = "Summon level 2", Address = 0x3526, BitIndex = 2},
        [1245903] = {Name = "Summon level 3", Address = 0x3526, BitIndex = 3},
        [1245904] = {Name = "Summon level 4", Address = 0x3526, BitIndex = 4},
        [1245905] = {Name = "Summon level 5", Address = 0x3526, BitIndex = 5},
        [1245906] = {Name = "Summon level 6", Address = 0x3526, BitIndex = 6},
        [1245907] = {Name = "Summon level 7", Address = 0x3526, BitIndex = 7},
    }
end

function LocationDefs:WeaponSlots()

    WeaponAbilities = {
        [1245883] = {Name = "Adamant Shield Slot",     Address = 0x35E6, BitIndex = 1},
        [1245884] = {Name = "Akashic Record Slot",     Address = 0x35ED, BitIndex = 1},
        [1245885] = {Name = "Chain Gear Slot",         Address = 0x35E7, BitIndex = 1},
        [1245886] = {Name = "Dream Cloud Slot",        Address = 0x35EA, BitIndex = 1},
        [1245887] = {Name = "Falling Star Slot",       Address = 0x35E9, BitIndex = 1},
        [1245888] = {Name = "Frozen Pride+ Slot",      Address = 0x36A2, BitIndex = 1},
        [1245889] = {Name = "Genji Shield Slot",       Address = 0x35EC, BitIndex = 1},
        [1245890] = {Name = "Knight Defender Slot",    Address = 0x35EB, BitIndex = 1},
        [1245892] = {Name = "Majestic Mushroom Slot",  Address = 0x36A5, BitIndex = 1},
        [1245893] = {Name = "Majestic Mushroom+ Slot", Address = 0x36A6, BitIndex = 1},
        [1245894] = {Name = "Nobody Guard Slot",       Address = 0x35EE, BitIndex = 1},
        [1245895] = {Name = "Ogre Shield Slot",        Address = 0x35E8, BitIndex = 1},
        [1245896] = {Name = "Save The King+ Slot",     Address = 0x3693, BitIndex = 1},
        [1245897] = {Name = "Ultimate Mushroom Slot",  Address = 0x36A7, BitIndex = 1},
        [1245851] = {Name = "Comet Staff Slot",        Address = 0x35F2, BitIndex = 1},
        [1245852] = {Name = "Hammer Staff Slot",       Address = 0x35EF, BitIndex = 1},
        [1245853] = {Name = "Lord's Broom Slot",       Address = 0x35F3, BitIndex = 1},
        [1245855] = {Name = "Meteor Staff Slot",       Address = 0x35F1, BitIndex = 1},
        [1245856] = {Name = "Nobody Lance Slot",       Address = 0x35F6, BitIndex = 1},
        [1245857] = {Name = "Precious Mushroom Slot",  Address = 0x369E, BitIndex = 1},
        [1245858] = {Name = "Precious Mushroom+ Slot", Address = 0x369F, BitIndex = 1},
        [1245859] = {Name = "Premium Mushroom Slot",   Address = 0x36A0, BitIndex = 1},
        [1245860] = {Name = "Rising Dragon Slot",      Address = 0x35F5, BitIndex = 1},
        [1245861] = {Name = "Save The Queen+ Slot",    Address = 0x3692, BitIndex = 1},
        [1245862] = {Name = "Shaman's Relic Slot",     Address = 0x35F7, BitIndex = 1},
        [1245863] = {Name = "Victory Bell Slot",       Address = 0x35F0, BitIndex = 1},
        [1245864] = {Name = "Wisdom Wand Slot",        Address = 0x35F4, BitIndex = 1},
        [1245865] = {Name = "Centurion+ Slot",         Address = 0x369B, BitIndex = 1},
        [1245813] = {Name = "Oathkeeper Slot",         Address = 0x35A2, BitIndex = 1},
        [1245814] = {Name = "Oblivion Slot",           Address = 0x35A3, BitIndex = 1},
        [1245815] = {Name = "Star Seeker Slot",        Address = 0x367B, BitIndex = 1},
        [1245816] = {Name = "Hidden Dragon Slot",      Address = 0x367C, BitIndex = 1},
        [1245817] = {Name = "Hero's Crest Slot",       Address = 0x367F, BitIndex = 1},
        [1245818] = {Name = "Monochrome Slot",         Address = 0x3680, BitIndex = 1},
        [1245819] = {Name = "Follow the Wind Slot",    Address = 0x3681, BitIndex = 1},
        [1245820] = {Name = "Circle of Life Slot",     Address = 0x3682, BitIndex = 1},
        [1245821] = {Name = "Photon Debugger Slot",    Address = 0x3683, BitIndex = 1},
        [1245822] = {Name = "Gull Wing Slot",          Address = 0x3684, BitIndex = 1},
        [1245823] = {Name = "Rumbling Rose Slot",      Address = 0x3685, BitIndex = 1},
        [1245824] = {Name = "Guardian Soul Slot",      Address = 0x3686, BitIndex = 1},
        [1245825] = {Name = "Wishing Lamp Slot",       Address = 0x3687, BitIndex = 1},
        [1245826] = {Name = "Decisive Pumpkin Slot",   Address = 0x3688, BitIndex = 1},
        [1245829] = {Name = "Sleeping Lion Slot",      Address = 0x3689, BitIndex = 1},
        [1245827] = {Name = "Sweet Memories Slot",     Address = 0x368A, BitIndex = 1},
        [1245828] = {Name = "Mysterious Abyss Slot",   Address = 0x368B, BitIndex = 1},
        [1245831] = {Name = "Two Become One Slot",     Address = 0x3698, BitIndex = 1},
        [1245832] = {Name = "Fatal Crest Slot",        Address = 0x368C, BitIndex = 1},
        [1245830] = {Name = "Bond of Flame Slot",      Address = 0x368D, BitIndex = 1},
        [1245833] = {Name = "Fenrir Slot",             Address = 0x368E, BitIndex = 1},
        [1245834] = {Name = "Ultima Weapon Slot",      Address = 0x368F, BitIndex = 1},
        [1245835] = {Name = "Winner's Proof Slot",     Address = 0x3699, BitIndex = 1},
        [1245836] = {Name = "Pureblood Slot",          Address = 0x35BF, BitIndex = 1},
    }

    FormWeaponAbilities = {
        --Form Keyblade Abilities
        [1245809] = {Name = "FAKE Slot",            Address = 0x36C0, BitIndex = 1},
        [1245810] = {Name = "Detection Saber Slot", Address = 0x36C0, BitIndex = 6},
        [1245811] = {Name = "Edge of Ultima Slot",  Address = 0x36C0, BitIndex = 4},
    }
 end

function LocationDefs:TornPageLocks()
    PoohProgress = {
        {Name = "Torn Page 1", Address = 0x1DB7, BitIndex = 4}, -- --Scenario_1_start
        {Name = "Torn Page 2", Address = 0x1DB7, BitIndex = 7}, -- --Scenario_2_start
        {Name = "Torn Page 3", Address = 0x1DB8, BitIndex = 2}, -- --Scenario_3_start
        {Name = "Torn Page 4", Address = 0x1DB8, BitIndex = 4}, -- --Scenario_4_start
        {Name = "Torn Page 5", Address = 0x1DB8, BitIndex = 7}, -- --Scenario_5_start
    }
end

return LocationDefs