local LocationDefs = {}

function LocationDefs:DefineWorldEvents()
    Worlds = {
        LoD_Checks = {
	        {Name = "(LoD) Bamboo Grove Dark Shard",          Address = 0x23AC, BitIndex = 1, Chest = true},
	        {Name = "(LoD) Bamboo Grove Ether",               Address = 0x23D9, BitIndex = 7, Chest = true},
	        {Name = "(LoD) Bamboo Grove Mythril Shard",       Address = 0x23DA, BitIndex = 0, Chest = true},
	        {Name = "(LoD) Bamboo Grove Encampment Area Map", Address = 0x1D94, BitIndex = 6, Chest = false},
	        {Name = "(LoD) Mission 3",                        Address = 0x1D96, BitIndex = 0, Chest = false},
	        {Name = "(LoD) Checkpoint Hi-Potion",             Address = 0x23AD, BitIndex = 1, Chest = true},
	        {Name = "(LoD) Checkpoint Mythril Shard",         Address = 0x23AD, BitIndex = 2, Chest = true},
	        {Name = "(LoD) Mountain Trail Lightning Shard",   Address = 0x23AD, BitIndex = 3, Chest = true},
	        {Name = "(LoD) Mountain Trail Recovery Recipe",   Address = 0x23AD, BitIndex = 4, Chest = true},
	        {Name = "(LoD) Mountain Trail Ether",             Address = 0x23AD, BitIndex = 5, Chest = true},
	        {Name = "(LoD) Mountain Trail Mythril Shard",     Address = 0x23AD, BitIndex = 6, Chest = true},
	        {Name = "(LoD) Village Cave Area Map",            Address = 0x1D96, BitIndex = 6, Chest = false},
	        {Name = "(LoD) Village Cave AP Boost",            Address = 0x23AE, BitIndex = 0, Chest = true},
	        {Name = "(LoD) Village Cave Dark Shard",          Address = 0x23AD, BitIndex = 7, Chest = true},
	        {Name = "(LoD) Village Cave Bonus: Sora Slot 1",  Address = 0x3709, BitIndex = 3, Chest = false},
	        {Name = "(LoD) Ridge Frost Shard",                Address = 0x23AE, BitIndex = 1, Chest = true},
	        {Name = "(LoD) Ridge AP Boost",                   Address = 0x23AE, BitIndex = 2, Chest = true},
	        {Name = "(LoD) Shan-Yu Bonus: Sora Slot 1",       Address = 0x3705, BitIndex = 1, Chest = false},
	        {Name = "(LoD) Shan-Yu Bonus: Sora Slot 2",       Address = 0x3705, BitIndex = 1, Chest = false},
	        {Name = "(LoD) Shan-Yu Bonus: Goofy Slot 1",      Address = 0x3705, BitIndex = 1, Chest = false},
	        {Name = "(LoD) Hidden Dragon",                    Address = 0x1D92, BitIndex = 2, Chest = false},
	        {Name = "(LoD2) Throne Room Torn Pages",          Address = 0x23AE, BitIndex = 3, Chest = true},
	        {Name = "(LoD2) Throne Room Palace Map",          Address = 0x23AE, BitIndex = 4, Chest = true},
	        {Name = "(LoD2) Throne Room AP Boost",            Address = 0x23AE, BitIndex = 5, Chest = true},
	        {Name = "(LoD2) Throne Room Queen Recipe",        Address = 0x23AE, BitIndex = 6, Chest = true},
	        {Name = "(LoD2) Throne Room AP Boost 2",          Address = 0x23AE, BitIndex = 7, Chest = true},
	        {Name = "(LoD2) Throne Room Ogre Shield",         Address = 0x23AF, BitIndex = 0, Chest = true},
	        {Name = "(LoD2) Throne Room Mythril Crystal",     Address = 0x23AF, BitIndex = 1, Chest = true},
	        {Name = "(LoD2) Throne Room Orichalcum",          Address = 0x23AF, BitIndex = 2, Chest = true},
	        {Name = "(LoD2) Storm Rider Bonus: Sora Slot 1",  Address = 0x3705, BitIndex = 2, Chest = false},
	        {Name = "(LoD2) Storm Rider Bonus: Goofy Slot 1", Address = 0x3705, BitIndex = 2, Chest = false},
        },

	    AG_Checks = {
	        {Name = "(AG) Agrabah Map",                                 Address = 0x1D74, BitIndex = 4, Chest = false},
            {Name = "(AG) Agrabah Dark Shard",                          Address = 0x23AF, BitIndex = 3, Chest = true},
            {Name = "(AG) Agrabah Mythril Shard",                       Address = 0x23AF, BitIndex = 4, Chest = true},
            {Name = "(AG) Agrabah Hi-Potion",                           Address = 0x23AF, BitIndex = 5, Chest = true},
            {Name = "(AG) Agrabah AP Boost",                            Address = 0x23AF, BitIndex = 6, Chest = true},
            {Name = "(AG) Agrabah Mythril Stone",                       Address = 0x23AF, BitIndex = 7, Chest = true},
            {Name = "(AG) Agrabah Mythril Shard 2",                     Address = 0x23B0, BitIndex = 0, Chest = true},
            {Name = "(AG) Agrabah Serenity Shard",                      Address = 0x23DA, BitIndex = 3, Chest = true},
            {Name = "(AG) Bazaar Mythril Gem",                          Address = 0x23B0, BitIndex = 1, Chest = true},
            {Name = "(AG) Bazaar Power Shard",                          Address = 0x23B0, BitIndex = 2, Chest = true},
            {Name = "(AG) Bazaar Hi-Potion",                            Address = 0x23B0, BitIndex = 3, Chest = true},
            {Name = "(AG) Bazaar AP Boost",                             Address = 0x23B0, BitIndex = 4, Chest = true},
            {Name = "(AG) Bazaar Mythril Shard",                        Address = 0x23B0, BitIndex = 5, Chest = true},
            {Name = "(AG) Palace Walls Skill Ring",                     Address = 0x23B0, BitIndex = 6, Chest = true},
            {Name = "(AG) Palace Walls Mythril Stone",                  Address = 0x23DB, BitIndex = 5, Chest = true},
            {Name = "(AG) Cave Entrance Power Stone",                   Address = 0x23B0, BitIndex = 7, Chest = true},
            {Name = "(AG) Cave Entrance Mythril Shard",                 Address = 0x23B1, BitIndex = 0, Chest = true},
            {Name = "(AG) Valley of Stone Mythril Stone",               Address = 0x23B1, BitIndex = 2, Chest = true},
            {Name = "(AG) Valley of Stone AP Boost",                    Address = 0x23B1, BitIndex = 3, Chest = true},
            {Name = "(AG) Valley of Stone Mythril Shard",               Address = 0x23B1, BitIndex = 4, Chest = true},
            {Name = "(AG) Valley of Stone Hi-Potion",                   Address = 0x23B1, BitIndex = 5, Chest = true},
            {Name = "(AG) Abu Escort Bonus: Sora Slot 1",               Address = 0x3709, BitIndex = 2, Chest = false},
            {Name = "(AG) Abu Escort Bonus: Donald Slot 1",             Address = 0x3709, BitIndex = 2, Chest = false},
            {Name = "(AG) Chasm of Challenges Cave of Wonders Map",     Address = 0x23D8, BitIndex = 7, Chest = true},
            {Name = "(AG) Chasm of Challenges AP Boost",                Address = 0x23B1, BitIndex = 6, Chest = true},
            {Name = "(AG) Treasure Room",                               Address = 0x3709, BitIndex = 6, Chest = false},
            {Name = "(AG) Treasure Room Heartless Bonus: Goofy Slot 1", Address = 0x3709, BitIndex = 6, Chest = false},
            {Name = "(AG) Treasure Room AP Boost",                      Address = 0x23DA, BitIndex = 4, Chest = true},
            {Name = "(AG) Treasure Room Serenity Gem",                  Address = 0x23DA, BitIndex = 5, Chest = true},
            {Name = "(AG) Elemental Lords Bonus: Sora Slot 1",          Address = 0x3708, BitIndex = 5, Chest = false},
            {Name = "(AG) Lamp Charm",                                  Address = 0x1D72, BitIndex = 4, Chest = false},
            {Name = "(AG2) Ruined Chamber Torn Pages",                  Address = 0x23B1, BitIndex = 1, Chest = true},
            {Name = "(AG2) Ruined Chamber Ruins Map",                   Address = 0x23D8, BitIndex = 6, Chest = true},
            {Name = "(AG2) Genie Jafar",                                Address = 0x3705, BitIndex = 7, Chest = false},
            {Name = "(AG2) Wishing Lamp",                               Address = 0x1D77, BitIndex = 3, Chest = false},
        },

        DC_Checks = {
            {Name = "(DC) Courtyard Mythril Shard",                                         Address = 0x23B4, BitIndex = 1, Chest = true},
            {Name = "(DC) Courtyard Star Recipe",                                           Address = 0x23B4, BitIndex = 2, Chest = true},
            {Name = "(DC) Courtyard AP Boost",                                              Address = 0x23B4, BitIndex = 3, Chest = true},
            {Name = "(DC) Courtyard Mythril Stone",                                         Address = 0x23B4, BitIndex = 4, Chest = true},
            {Name = "(DC) Courtyard Blazing Stone",                                         Address = 0x23B4, BitIndex = 5, Chest = true},
            {Name = "(DC) Courtyard Blazing Shard",                                         Address = 0x23B4, BitIndex = 6, Chest = true},
            {Name = "(DC) Courtyard Mythril Shard 2",                                       Address = 0x23B4, BitIndex = 7, Chest = true},
            {Name = "(DC) Library Torn Pages",                                              Address = 0x23B4, BitIndex = 0, Chest = true},
            {Name = "(DC) Disney Castle Map",                                               Address = 0x1E10, BitIndex = 4, Chest = false},
            {Name = "(DC) Minnie Escort Bonus: Sora Slot 1",                                Address = 0x3708, BitIndex = 6, Chest = false},
            {Name = "(DC) Minnie Escort Bonus: Sora Slot 2",                                Address = 0x3708, BitIndex = 6, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Bonus: Sora Slot 1",  Address = 0x370C, BitIndex = 6, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Proof of Connection", Address = 0x370C, BitIndex = 6, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) Lingering Will Manifest Illusion",   Address = 0x370C, BitIndex = 6, Chest = false},
        },

        TR_Checks = {
            {Name = "(TR) Cornerstone Hill Map",            Address = 0x23B2, BitIndex = 0, Chest = true},
            {Name = "(TR) Cornerstone Hill Frost Shard",    Address = 0x23B2, BitIndex = 1, Chest = true},
            {Name = "(TR) Pier Mythril Shard",              Address = 0x23B2, BitIndex = 3, Chest = true},
            {Name = "(TR) Pier Hi-Potion",                  Address = 0x23B2, BitIndex = 4, Chest = true},
            {Name = "(TR) Waterway Mythril Stone",          Address = 0x23B2, BitIndex = 5, Chest = true},
            {Name = "(TR) Waterway AP Boost",               Address = 0x23B2, BitIndex = 6, Chest = true},
            {Name = "(TR) Waterway Frost Stone",            Address = 0x23B2, BitIndex = 7, Chest = false},
            {Name = "(TR) Window of Time Map",              Address = 0x1E32, BitIndex = 4, Chest = false},
            {Name = "(TR) Boat Pete Bonus: Sora Slot 1",    Address = 0x3706, BitIndex = 0, Chest = false},
            {Name = "(TR) Boat Pete Bonus: Donald Slot 1",  Address = 0x3706, BitIndex = 0, Chest = false},
            {Name = "(TR) Boat Pete Bonus: Donald Slot 2",  Address = 0x3706, BitIndex = 0, Chest = false},
            {Name = "(TR) Future Pete Bonus: Sora Slot 1",  Address = 0x3706, BitIndex = 1, Chest = false},
            {Name = "(TR) Future Pete Bonus: Sora Slot 2",  Address = 0x3706, BitIndex = 1, Chest = false},
            {Name = "(TR) Future Pete Bonus: Goofy Slot 1", Address = 0x3706, BitIndex = 1, Chest = false},
            {Name = "(TR) Monochrome",                      Address = 0x1E33, BitIndex = 2, Chest = false},
            {Name = "(TR) Wisdom Form",                     Address = 0x1E33, BitIndex = 2, Chest = false},
        },

        Pooh_Checks = {
            {Name = "(100Acre) Pooh's House 100 Acre Wood Map", Address = 0x23C9, BitIndex = 7, Chest = true},
            {Name = "(100Acre) Pooh's House AP Boost",          Address = 0x23B5, BitIndex = 4, Chest = true},
            {Name = "(100Acre) Pooh's House Mythril Stone",     Address = 0x23B5, BitIndex = 5, Chest = true},
            {Name = "(100Acre) Piglet's House Defense Boost",   Address = 0x23B6, BitIndex = 4, Chest = true},
            {Name = "(100Acre) Piglet's House AP Boost",        Address = 0x23B6, BitIndex = 2, Chest = true},
            {Name = "(100Acre) Piglet's House Mythril Gem",     Address = 0x23B6, BitIndex = 3, Chest = true},
            {Name = "(100Acre) Rabbit's House Draw Ring",       Address = 0x23CA, BitIndex = 0, Chest = true},
            {Name = "(100Acre) Rabbit's House Mythril Crystal", Address = 0x23B5, BitIndex = 7, Chest = true},
            {Name = "(100Acre) Rabbit's House AP Boost",        Address = 0x23B6, BitIndex = 0, Chest = true},
            {Name = "(100Acre) Kanga's House Magic Boost",      Address = 0x23B6, BitIndex = 7, Chest = true},
            {Name = "(100Acre) Kanga's House AP Boost",         Address = 0x23B6, BitIndex = 5, Chest = true},
            {Name = "(100Acre) Kanga's House Orichalcum",       Address = 0x23B6, BitIndex = 6, Chest = true},
            {Name = "(100Acre) Spooky Cave Mythril Gem",        Address = 0x23B7, BitIndex = 1, Chest = true},
            {Name = "(100Acre) Spooky Cave AP Boost",           Address = 0x23B7, BitIndex = 2, Chest = true},
            {Name = "(100Acre) Spooky Cave Orichalcum",         Address = 0x23B7, BitIndex = 3, Chest = false},
            {Name = "(100Acre) Spooky Cave Guard Recipe",       Address = 0x23B7, BitIndex = 4, Chest = true},
            {Name = "(100Acre) Spooky Cave Mythril Crystal",    Address = 0x23B7, BitIndex = 6, Chest = true},
            {Name = "(100Acre) Spooky Cave AP Boost 2",         Address = 0x23B7, BitIndex = 7, Chest = true},
            {Name = "(100Acre) Sweet Memories",                 Address = 0x1DB4, BitIndex = 6, Chest = false},
            {Name = "(100Acre) Spooky Cave Map",                Address = 0x1DB4, BitIndex = 6, Chest = false},
            {Name = "(100Acre) Starry Hill Cosmic Ring",        Address = 0x23C9, BitIndex = 6, Chest = true},
            {Name = "(100Acre) Starry Hill Style Recipe",       Address = 0x23B5, BitIndex = 1, Chest = true},
            {Name = "(100Acre) Starry Hill Cure Element",       Address = 0x1DB5, BitIndex = 5, Chest = false},
            {Name = "(100Acre) Starry Hill Orichalcum+",        Address = 0x1DB5, BitIndex = 5, Chest = false},
        },

        OC_Checks = {
            {Name = "(OC) Passage Mythril Shard",           Address = 0x23B9, BitIndex = 6, Chest = true},
            {Name = "(OC) Passage Mythril Stone",           Address = 0x23B9, BitIndex = 7, Chest = true},
            {Name = "(OC) Passage Ether",                   Address = 0x23BA, BitIndex = 0, Chest = true},
            {Name = "(OC) Passage AP Boost",                Address = 0x23BA, BitIndex = 1, Chest = true},
            {Name = "(OC) Passage Hi-Potion",               Address = 0x23BA, BitIndex = 2, Chest = true},
            {Name = "(OC) Inner Chamber Underworld Map",    Address = 0x23B8, BitIndex = 4, Chest = true},
            {Name = "(OC) Inner Chamber Mythril Shard",     Address = 0x23B8, BitIndex = 3, Chest = true},
            {Name = "(OC) Cerberus Bonus: Sora Slot 1",     Address = 0x3704, BitIndex = 5, Chest = false},
            {Name = "(OC) Coliseum Map",                    Address = 0x1D5A, BitIndex = 4, Chest = false},
            {Name = "(OC) Urns Bonus: Sora Slot 1",         Address = 0x370B, BitIndex = 1, Chest = false},
            {Name = "(OC) Underworld Entrance Power Boost", Address = 0x23B8, BitIndex = 0, Chest = false},
            {Name = "(OC) Caverns Entrance Lucid Shard",    Address = 0x23B8, BitIndex = 5, Chest = true},
            {Name = "(OC) Caverns Entrance AP Boost",       Address = 0x23B8, BitIndex = 6, Chest = true},
            {Name = "(OC) Caverns Entrance Mythril Shard",  Address = 0x23DA, BitIndex = 6, Chest = true},
            {Name = "(OC) The Lost Road Bright Shard",      Address = 0x23BA, BitIndex = 3, Chest = true},
            {Name = "(OC) The Lost Road Ether",             Address = 0x23BA, BitIndex = 4, Chest = true},
            {Name = "(OC) The Lost Road Mythril Shard",     Address = 0x23BA, BitIndex = 5, Chest = true},
            {Name = "(OC) The Lost Road Mythril Stone",     Address = 0x23BA, BitIndex = 6, Chest = true},
            {Name = "(OC) Atrium Lucid Stone",              Address = 0x23BA, BitIndex = 7, Chest = true},
            {Name = "(OC) Atrium AP Boost",                 Address = 0x23BB, BitIndex = 0, Chest = true},
            {Name = "(OC) Demyx Bonus: Sora Slot 1",        Address = 0x370B, BitIndex = 2, Chest = false},
            {Name = "(OC) Demyx Bonus: Donald Slot 1",      Address = 0x370B, BitIndex = 2, Chest = false},
            {Name = "(OC) Secret Ansem Report 5 (Demyx)",   Address = 0x1D5B, BitIndex = 3, Chest = false},
            {Name = "(OC) Olympus Stone",                   Address = 0x1D5B, BitIndex = 3, Chest = false},
            {Name = "(OC) The Lock Caverns Map",            Address = 0x23B9, BitIndex = 4, Chest = true},
            {Name = "(OC) The Lock Mythril Shard",          Address = 0x23B9, BitIndex = 0, Chest = true},
            {Name = "(OC) The Lock AP Boost",               Address = 0x23B9, BitIndex = 2, Chest = true},
            {Name = "(OC) Pete OC Bonus: Sora Slot 1",      Address = 0x3704, BitIndex = 6, Chest = false},
            {Name = "(OC) Pete Bonus: Goofy Slot 1",        Address = 0x3704, BitIndex = 6, Chest = false},
            {Name = "(OC) Hydra Bonus: Sora Slot 1",        Address = 0x3704, BitIndex = 7, Chest = false},
            {Name = "(OC) Hydra Bonus: Sora Slot 2",        Address = 0x3704, BitIndex = 7, Chest = false},
            {Name = "(OC) Hero's Crest",                    Address = 0x1D55, BitIndex = 7, Chest = false},
            {Name = "(OC2) Auron's Statue",                 Address = 0x1D5F, BitIndex = 2, Chest = false},
            {Name = "(OC2) Hades Bonus: Sora Slot 1",       Address = 0x3705, BitIndex = 0, Chest = false},
            {Name = "(OC2) Hades Bonus: Sora Slot 2",       Address = 0x3705, BitIndex = 0, Chest = false},
            {Name = "(OC2) Guardian Soul",                  Address = 0x1D56, BitIndex = 5, Chest = false},
            {Name = "Protect Belt Pain and Panic Cup",      Address = 0x1D57, BitIndex = 6, Chest = false},
            {Name = "Serenity Gem Pain and Panic Cup",      Address = 0x1D57, BitIndex = 6, Chest = false},
            {Name = "Rising Dragon Cerberus Cup",           Address = 0x1D58, BitIndex = 0, Chest = false},
            {Name = "Serenity Crystal Cerberus Cup",        Address = 0x1D58, BitIndex = 0, Chest = false},
            {Name = "Genji Shield Titan Cup",               Address = 0x1D58, BitIndex = 1, Chest = false},
            {Name = "Skillful Ring Titan Cup",              Address = 0x1D58, BitIndex = 1, Chest = false},
            {Name = "Fatal Crest Goddess of Fate Cup",      Address = 0x1D58, BitIndex = 4, Chest = false},
            {Name = "Orichalcum+ Goddess of Fate Cup",      Address = 0x1D58, BitIndex = 4, Chest = false},
            {Name = "Hades Cup Trophy Paradox Cups",        Address = 0x1D5A, BitIndex = 1, Chest = false},
        },

        BC_Checks = {
            {Name = "(BC) Courtyard AP Boost",                  Address = 0x23BB, BitIndex = 5, Chest = true},
            {Name = "(BC) Courtyard Hi-Potion",                 Address = 0x23BB, BitIndex = 6, Chest = true},
            {Name = "(BC) Courtyard Mythril Shard",             Address = 0x23DA, BitIndex = 7, Chest = true},
            {Name = "(BC) Belle's Room Castle Map",             Address = 0x23BB, BitIndex = 2, Chest = true},
            {Name = "(BC) Belle's Room Mega-Recipe",            Address = 0x23BB, BitIndex = 3, Chest = true},
            {Name = "(BC) The East Wing Mythril Shard",         Address = 0x23BB, BitIndex = 7, Chest = true},
            {Name = "(BC) The East Wing Tent",                  Address = 0x23BC, BitIndex = 0, Chest = true},
            {Name = "(BC) The West Hall Hi-Potion",             Address = 0x23BC, BitIndex = 1, Chest = true},
            {Name = "(BC) The West Hall Power Shard",           Address = 0x23BC, BitIndex = 3, Chest = true},
            {Name = "(BC) The West Hall Mythril Shard 2",       Address = 0x23BC, BitIndex = 5, Chest = true},
            {Name = "(BC) The West Hall Bright Stone",          Address = 0x23DB, BitIndex = 0, Chest = true},
            {Name = "(BC) The West Hall Mythril Shard",         Address = 0x23BC, BitIndex = 2, Chest = true},
            {Name = "(BC) Thresholder Bonus: Sora Slot 1",      Address = 0x23BC, BitIndex = 4, Chest = false},
            {Name = "(BC) Thresholder Bonus: Donald Slot 1",    Address = 0x3704, BitIndex = 2, Chest = false},
            {Name = "(BC) Dungeon Basement Map",                Address = 0x3704, BitIndex = 2, Chest = true},
            {Name = "(BC) Dungeon AP Boost",                    Address = 0x23BD, BitIndex = 0, Chest = true},
            {Name = "(BC) Secret Passage Mythril Shard",        Address = 0x23BD, BitIndex = 1, Chest = true},
            {Name = "(BC) Secret Passage Hi-Potion",            Address = 0x23BD, BitIndex = 2, Chest = true},
            {Name = "(BC) Secret Passage Lucid Shard",          Address = 0x23BD, BitIndex = 5, Chest = true},
            {Name = "(BC) The West Hall AP Boost Post Dungeon", Address = 0x23BD, BitIndex = 3, Chest = true},
            {Name = "(BC) The West Wing Mythril Shard",         Address = 0x23BC, BitIndex = 6, Chest = true},
            {Name = "(BC) The West Wing Tent",                  Address = 0x23BC, BitIndex = 7, Chest = true},
            {Name = "(BC) Beast Bonus: Sora Slot 1",            Address = 0x3705, BitIndex = 4, Chest = false},
            {Name = "(BC) Beast Bonus: Goofy Slot 1",           Address = 0x3705, BitIndex = 4, Chest = false},
            {Name = "(BC) The Beast's Room Blazing Shard",      Address = 0x23BB, BitIndex = 4, Chest = true},
            {Name = "(BC) Dark Thorn Bonus: Sora Slot 1",       Address = 0x3704, BitIndex = 3, Chest = false},
            {Name = "(BC) Dark Thorn Bonus: Sora Slot 2",       Address = 0x3704, BitIndex = 3, Chest = false},
            {Name = "(BC) Dark Thorn Cure Element",             Address = 0x1D32, BitIndex = 5, Chest = false},
            {Name = "(BC2) Rumbling Rose",                      Address = 0x1D39, BitIndex = 0, Chest = false},
            {Name = "(BC2) Castle Walls Map",                   Address = 0x1D39, BitIndex = 0, Chest = false},
            {Name = "(BC2) Xaldin Bonus: Sora Slot 1",          Address = 0x3704, BitIndex = 4, Chest = false},
            {Name = "(BC2) Xaldin Bonus: Sora Slot 2",          Address = 0x3704, BitIndex = 4, Chest = false},
            {Name = "(BC2) Xaldin Bonus: Donald Slot 1",        Address = 0x3704, BitIndex = 4, Chest = false},
            {Name = "(BC2) Secret Ansem Report 4 (Xaldin)",     Address = 0x1D31, BitIndex = 2, Chest = false},
            {Name = "(Post BC2: Ballroom) Data Xaldin",         Address = 0x1D34, BitIndex = 7, Chest = false},
        },

        SP_Checks = {
            {Name = "(SP) Pit Cell Area Map",                   Address = 0x23CA, BitIndex = 2, Chest = true},
            {Name = "(SP) Pit Cell Mythril Crystal",            Address = 0x23BD, BitIndex = 6, Chest = true},
            {Name = "(SP) Canyon Dark Crystal",                 Address = 0x23BE, BitIndex = 1, Chest = true},
            {Name = "(SP) Canyon Mythril Stone",                Address = 0x23BE, BitIndex = 2, Chest = true},
            {Name = "(SP) Canyon Mythril Gem",                  Address = 0x23BE, BitIndex = 3, Chest = true},
            {Name = "(SP) Canyon Frost Crystal",                Address = 0x23DB, BitIndex = 6, Chest = true},
            {Name = "(SP) Screens Bonus: Sora Slot 1",          Address = 0x3709, BitIndex = 5, Chest = false},
            {Name = "(SP) Screens Bonus: Donald Slot 1",        Address = 0x3709, BitIndex = 5, Chest = false},
            {Name = "(SP) Hallway Power Crystal",               Address = 0x23BE, BitIndex = 4, Chest = true},
            {Name = "(SP) Hallway AP Boost",                    Address = 0x23BE, BitIndex = 5, Chest = true},
            {Name = "(SP) Communications Room I/O Tower Map",   Address = 0x23BF, BitIndex = 1, Chest = true},
            {Name = "(SP) Communications Room Gaia Belt",       Address = 0x23DA, BitIndex = 1, Chest = true},
            {Name = "(SP) Hostile Program Bonus: Sora Slot 1",  Address = 0x3707, BitIndex = 7, Chest = false},
            {Name = "(SP) Hostile Program Bonus: Sora Slot 2",  Address = 0x3707, BitIndex = 7, Chest = false},
            {Name = "(SP) Hostile Program Bonus: Goofy Slot 1", Address = 0x3707, BitIndex = 7, Chest = false},
            {Name = "(SP) Photon Debugger",                     Address = 0x1EB2, BitIndex = 3, Chest = false},
            {Name = "(SP2) Solar Sailer",                       Address = 0x370B, BitIndex = 5, Chest = false},
            {Name = "(SP2) Solar Sailer Bonus: Donald Slot 1",  Address = 0x370B, BitIndex = 5, Chest = false},
            {Name = "(SP2) Central Computer Core AP Boost",     Address = 0x23BF, BitIndex = 4, Chest = true},
            {Name = "(SP2) Central Computer Core Orichalcum+",  Address = 0x23BF, BitIndex = 5, Chest = true},
            {Name = "(SP2) Central Computer Core Cosmic Arts",  Address = 0x23BF, BitIndex = 6, Chest = true},
            {Name = "(SP2) Central Computer Core Map",          Address = 0x23D9, BitIndex = 0, Chest = true},
            {Name = "(SP2) MCP Bonus: Sora Slot 1",             Address = 0x3708, BitIndex = 0, Chest = false},
            {Name = "(SP2) MCP Bonus: Sora Slot 2",             Address = 0x3708, BitIndex = 0, Chest = false},
        },

        HT_Checks = {
            {Name = "(HT) Graveyard Mythril Shard",                     Address = 0x23C0, BitIndex = 2, Chest = true},
            {Name = "(HT) Graveyard Serenity Gem",                      Address = 0x23C0, BitIndex = 3, Chest = true},
            {Name = "(HT) Finklestein's Lab Halloween Town Map",        Address = 0x23C0, BitIndex = 1, Chest = true},
            {Name = "(HT) Town Square Mythril Stone",                   Address = 0x23BF, BitIndex = 7, Chest = true},
            {Name = "(HT) Town Square Energy Shard",                    Address = 0x23C0, BitIndex = 0, Chest = true},
            {Name = "(HT) Hinterlands Lightning Shard",                 Address = 0x23C0, BitIndex = 4, Chest = true},
            {Name = "(HT) Hinterlands Mythril Stone",                   Address = 0x23C0, BitIndex = 5, Chest = true},
            {Name = "(HT) Hinterlands AP Boost",                        Address = 0x23C0, BitIndex = 6, Chest = true},
            {Name = "(HT) Candy Cane Lane Mega-Potion",                 Address = 0x23C1, BitIndex = 0, Chest = true},
            {Name = "(HT) Candy Cane Lane Mythril Gem",                 Address = 0x23C1, BitIndex = 1, Chest = true},
            {Name = "(HT) Candy Cane Lane Lightning Stone",             Address = 0x23C1, BitIndex = 2, Chest = true},
            {Name = "(HT) Candy Cane Lane Mythril Stone",               Address = 0x23C1, BitIndex = 3, Chest = true},
            {Name = "(HT) Santa's House Christmas Town Map",            Address = 0x23C1, BitIndex = 6, Chest = true},
            {Name = "(HT) Santa's House AP Boost",                      Address = 0x23C1, BitIndex = 4, Chest = true},
            {Name = "(HT) Prison Keeper Bonus: Sora Slot 1",            Address = 0x3706, BitIndex = 2, Chest = false},
            {Name = "(HT) Prison Keeper Bonus: Donald Slot 1",          Address = 0x3706, BitIndex = 2, Chest = false},
            {Name = "(HT) Oogie Boogie Bonus: Sora Slot 1",             Address = 0x3706, BitIndex = 3, Chest = false},
            {Name = "(HT) Oogie Boogie Bonus: Goofy Slot 1",            Address = 0x3706, BitIndex = 3, Chest = false},
            {Name = "(HT) Oogie Boogie Magnet Element",                 Address = 0x1E53, BitIndex = 2, Chest = false},
            {Name = "(HT2) Lock, Shock and Barrel Bonus: Sora Slot 1",  Address = 0x3709, BitIndex = 0, Chest = false},
            {Name = "(HT2) Lock, Shock and Barrel Bonus: Goofy Slot 1", Address = 0x3709, BitIndex = 0, Chest = false},
            {Name = "(HT2) Present",                                    Address = 0x1E55, BitIndex = 1, Chest = false},
            {Name = "(HT2) Decoy Presents",                             Address = 0x1E55, BitIndex = 4, Chest = false},
            {Name = "(HT2) Experiment Bonus: Sora Slot 1",              Address = 0x3706, BitIndex = 4, Chest = false},
            {Name = "(HT2) Experiment Bonus: Donald Slot 1",            Address = 0x3706, BitIndex = 4, Chest = false},
            {Name = "(HT2) Decisive Pumpkin",                           Address = 0x1E56, BitIndex = 0, Chest = false},
        },

        PR_Checks = {
            {Name = "(PR) Rampart Naval Map",                       Address = 0x23C2, BitIndex = 1, Chest = true},
            {Name = "(PR) Rampart Mythril Stone",                   Address = 0x23C2, BitIndex = 2, Chest = true},
            {Name = "(PR) Rampart Dark Shard",                      Address = 0x23C2, BitIndex = 3, Chest = true},
            {Name = "(PR) Town Dark Stone",                         Address = 0x23C2, BitIndex = 4, Chest = true},
            {Name = "(PR) Town AP Boost",                           Address = 0x23C2, BitIndex = 5, Chest = true},
            {Name = "(PR) Town Mythril Shard",                      Address = 0x23C2, BitIndex = 6, Chest = true},
            {Name = "(PR) Town Mythril Gem",                        Address = 0x23C2, BitIndex = 7, Chest = true},
            {Name = "(PR) Cave Mouth Bright Shard",                 Address = 0x23C3, BitIndex = 1, Chest = true},
            {Name = "(PR) Cave Mouth Mythril Shard",                Address = 0x23C3, BitIndex = 2, Chest = true},
            {Name = "(PR) Isla de Muerta Map",                      Address = 0x1E92, BitIndex = 4, Chest = false},
            {Name = "(PR) Boat Fight Bonus: Sora Slot 1",           Address = 0x370B, BitIndex = 6, Chest = false},
            {Name = "(PR) Boat Fight Bonus: Donald Slot 1",         Address = 0x370B, BitIndex = 6, Chest = false},
            {Name = "(PR) Interceptor Barrels Bonus: Sora Slot 1",  Address = 0x3708, BitIndex = 7, Chest = false},
            {Name = "(PR) Interceptor Barrels Bonus: Goofy Slot 1", Address = 0x3708, BitIndex = 7, Chest = false},
            {Name = "(PR) Powder Store AP Boost 1",                 Address = 0x23CA, BitIndex = 7, Chest = true},
            {Name = "(PR) Powder Store AP Boost 2",                 Address = 0x23CB, BitIndex = 0, Chest = true},
            {Name = "(PR) Moonlight Nook Mythril Shard",            Address = 0x23C3, BitIndex = 4, Chest = true},
            {Name = "(PR) Moonlight Nook Serenity Gem",             Address = 0x23C3, BitIndex = 5, Chest = true},
            {Name = "(PR) Moonlight Nook Power Stone",              Address = 0x23CB, BitIndex = 1, Chest = true},
            {Name = "(PR) Barbossa Bonus: Sora Slot 1",             Address = 0x3706, BitIndex = 5, Chest = false},
            {Name = "(PR) Barbossa Bonus: Sora Slot 2",             Address = 0x3706, BitIndex = 5, Chest = false},
            {Name = "(PR) Barbossa Bonus: Goofy Slot 1",            Address = 0x3706, BitIndex = 5, Chest = false},
            {Name = "(PR) Barbossa Bonus: Goofy Slot 2",            Address = 0x3706, BitIndex = 5, Chest = false},
            {Name = "(PR) Follow the Wind",                         Address = 0x1E93, BitIndex = 6, Chest = false},
            {Name = "(PR2) Grim Reaper 1 Bonus: Sora Slot 1",       Address = 0x370B, BitIndex = 3, Chest = false},
            {Name = "(PR2) Grim Reaper 1 Bonus: Goofy Slot 1",      Address = 0x370B, BitIndex = 3, Chest = false},
            {Name = "(PR2) Interceptor's Hold Feather Charm",       Address = 0x23C3, BitIndex = 3, Chest = true},
            {Name = "(PR2) Seadrift Keep AP Boost",                 Address = 0x23C3, BitIndex = 6, Chest = true},
            {Name = "(PR2) Seadrift Keep Orichalcum",               Address = 0x23C3, BitIndex = 7, Chest = true},
            {Name = "(PR2) Seadrift Keep Meteor Staff",             Address = 0x23CB, BitIndex = 2, Chest = true},
            {Name = "(PR2) Seadrift Row Serenity Gem",              Address = 0x23C4, BitIndex = 0, Chest = true},
            {Name = "(PR2) Seadrift Row King Recipe",               Address = 0x23C4, BitIndex = 1, Chest = true},
            {Name = "(PR2) Seadrift Row Mythril Crystal",           Address = 0x23CB, BitIndex = 3, Chest = true},
            {Name = "(PR2) Seadrift Row Cursed Medallion",          Address = 0x1E95, BitIndex = 2, Chest = false},
            {Name = "(PR2) Seadrift Row Ship Graveyard Map",        Address = 0x1E95, BitIndex = 2, Chest = false},
            {Name = "(PR2) Grim Reaper 2 Bonus: Sora Slot 1",       Address = 0x3706, BitIndex = 6, Chest = false},
            {Name = "(PR2) Grim Reaper 2 Bonus: Donald Slot 1",     Address = 0x3706, BitIndex = 6, Chest = false},
            {Name = "(PR2) Secret Ansem Report 6 (Grim Reaper 2)",  Address = 0x1E95, BitIndex = 7, Chest = false},
        },

        HB_Checks = {
            {Name = "(HB) Marketplace Map",                                                  Address = 0x1D17, BitIndex = 4, Chest = false},
            {Name = "(HB) Borough Drive Recovery",                                           Address = 0x23C6, BitIndex = 1, Chest = true},
            {Name = "(HB) Borough AP Boost",                                                 Address = 0x23C6, BitIndex = 2, Chest = true},
            {Name = "(HB) Borough Hi-Potion",                                                Address = 0x23C6, BitIndex = 3, Chest = true},
            {Name = "(HB) Borough Mythril Shard",                                            Address = 0x23C8, BitIndex = 7, Chest = true},
            {Name = "(HB) Borough Dark Shard",                                               Address = 0x23DB, BitIndex = 1, Chest = true},
            {Name = "(HB) Merlin's House Membership Card",                                   Address = 0x1D10, BitIndex = 6, Chest = false},
            {Name = "(HB) Merlin's House Blizzard Element",                                  Address = 0x1D10, BitIndex = 6, Chest = false},
            {Name = "(HB) Bailey Bonus: Sora Slot 1",                                        Address = 0x3709, BitIndex = 7, Chest = false},
            {Name = "(HB) Bailey Secret Ansem Report 7",                                     Address = 0x3709, BitIndex = 7, Chest = false},
            {Name = "(HB) Baseball Charm",                                                   Address = 0x3709, BitIndex = 7, Chest = false},
            {Name = "(HB2) Postern Castle Perimeter Map",                                    Address = 0x23C9, BitIndex = 4, Chest = true},
            {Name = "(HB2) Postern Mythril Gem",                                             Address = 0x23C5, BitIndex = 4, Chest = true},
            {Name = "(HB2) Postern AP Boost",                                                Address = 0x23C5, BitIndex = 5, Chest = true},
            {Name = "(HB2) Corridors Mythril Stone",                                         Address = 0x23C6, BitIndex = 7, Chest = true},
            {Name = "(HB2) Corridors Mythril Crystal",                                       Address = 0x23C7, BitIndex = 0, Chest = true},
            {Name = "(HB2) Corridors Dark Crystal",                                          Address = 0x23C7, BitIndex = 1, Chest = true},
            {Name = "(HB2) Corridors AP Boost",                                              Address = 0x23C9, BitIndex = 1, Chest = true},
            {Name = "(HB2) Ansem's Study Master Form",                                       Address = 0x1D12, BitIndex = 6, Chest = false},
            {Name = "(HB2) Ansem's Study Sleeping Lion",                                     Address = 0x1D12, BitIndex = 6, Chest = false},
            {Name = "(HB2) Ansem's Study Skill Recipe",                                      Address = 0x23C4, BitIndex = 7, Chest = true},
            {Name = "(HB2) Ansem's Study Ukulele Charm",                                     Address = 0x23C4, BitIndex = 6, Chest = true},
            {Name = "(HB2) Restoration Site Moon Recipe",                                    Address = 0x23C9, BitIndex = 3, Chest = true},
            {Name = "(HB2) Restoration Site AP Boost",                                       Address = 0x23DB, BitIndex = 2, Chest = true},
            {Name = "(HB2) Demyx Bonus: Sora Slot 1",                                        Address = 0x3707, BitIndex = 4, Chest = false},
            {Name = "(HB2) Demyx Bonus: Sora Slot 2",                                        Address = 0x3707, BitIndex = 4, Chest = false},
            {Name = "(HB2) Demyx Bonus: Donald Slot 1",                                      Address = 0x3707, BitIndex = 4, Chest = false},
            {Name = "(HB2) FF Fights Cure Element",                                          Address = 0x1D14, BitIndex = 6, Chest = false},
            {Name = "(HB2) Crystal Fissure Torn Pages",                                      Address = 0x23C4, BitIndex = 2, Chest = true},
            {Name = "(HB2) Crystal Fissure The Great Maw Map",                               Address = 0x23D9, BitIndex = 1, Chest = true},
            {Name = "(HB2) Crystal Fissure Energy Crystal",                                  Address = 0x23C4, BitIndex = 3, Chest = true},
            {Name = "(HB2) Crystal Fissure AP Boost",                                        Address = 0x23C4, BitIndex = 4, Chest = true},
            {Name = "(HB2) 1000 Heartless",                                                  Address = 0x370B, BitIndex = 4, Chest = false},
            {Name = "(HB2) 1000 Heartless Secret Ansem Report 1",                            Address = 0x1D19, BitIndex = 3, Chest = false},
            {Name = "(HB2) 1000 Heartless Ice Cream",                                        Address = 0x1D23, BitIndex = 0, Chest = false},
            {Name = "(HB2) 1000 Heartless Picture",                                          Address = 0x1D23, BitIndex = 0, Chest = false},
            {Name = "(HB2) Postern Gull Wing",                                               Address = 0x23D9, BitIndex = 3, Chest = true},
            {Name = "(HB2) Heartless Manufactory Cosmic Chain",                              Address = 0x23C9, BitIndex = 5, Chest = true},
            {Name = "Sephiroth Bonus: Sora Slot 1",                                          Address = 0x3708, BitIndex = 3, Chest = false},
            {Name = "Sephiroth Fenrir",                                                      Address = 0x1D1F, BitIndex = 7, Chest = false},
            {Name = "(HB2) Winner's Proof",                                                  Address = 0x1D27, BitIndex = 5, Chest = false},
            {Name = "(HB2) Proof of Peace",                                                  Address = 0x1D27, BitIndex = 5, Chest = false},
            {Name = "(CoR) Depths AP Boost",                                                 Address = 0x23DC, BitIndex = 2, Chest = true},
            {Name = "(CoR) Depths Power Crystal",                                            Address = 0x23DC, BitIndex = 3, Chest = true},
            {Name = "(CoR) Depths Frost Crystal",                                            Address = 0x23DC, BitIndex = 4, Chest = true},
            {Name = "(CoR) Depths Manifest Illusion",                                        Address = 0x23DC, BitIndex = 5, Chest = true},
            {Name = "(CoR) Depths AP Boost 2",                                               Address = 0x23DC, BitIndex = 6, Chest = true},
            {Name = "(CoR) Mineshaft Lower Level Depths of Remembrance Map",                 Address = 0x23DE, BitIndex = 4, Chest = true},
            {Name = "(CoR) Mineshaft Lower Level AP Boost",                                  Address = 0x23DE, BitIndex = 2, Chest = true},
            {Name = "(CoR) Depths Upper Level Remembrance Gem",                              Address = 0x23DC, BitIndex = 7, Chest = true},
            {Name = "(CoR) Mining Area Serenity Gem",                                        Address = 0x23DD, BitIndex = 0, Chest = true},
            {Name = "(CoR) Mining Area AP Boost",                                            Address = 0x23DD, BitIndex = 1, Chest = true},
            {Name = "(CoR) Mining Area Serenity Crystal",                                    Address = 0x23DD, BitIndex = 2, Chest = true},
            {Name = "(CoR) Mining Area Manifest Illusion",                                   Address = 0x23DD, BitIndex = 3, Chest = true},
            {Name = "(CoR) Mining Area Serenity Gem 2",                                      Address = 0x23DD, BitIndex = 4, Chest = true},
            {Name = "(CoR) Mining Area Dark Remembrance Map",                                Address = 0x23DD, BitIndex = 5, Chest = true},
            {Name = "(CoR) Mineshaft Mid Level Power Boost",                                 Address = 0x23DE, BitIndex = 5, Chest = true},
            {Name = "(CoR) Engine Chamber Serenity Crystal",                                 Address = 0x23DD, BitIndex = 6, Chest = true},
            {Name = "(CoR) Engine Chamber Remembrance Crystal",                              Address = 0x23DD, BitIndex = 7, Chest = true},
            {Name = "(CoR) Engine Chamber AP Boost",                                         Address = 0x23DE, BitIndex = 0, Chest = true},
            {Name = "(CoR) Engine Chamber Manifest Illusion",                                Address = 0x23DE, BitIndex = 1, Chest = true},
            {Name = "(CoR) Mineshaft Upper Level Magic Boost",                               Address = 0x23DE, BitIndex = 6, Chest = true},
            {Name = "(CoR) Mineshaft Upper Level AP Boost",                                  Address = 0x23DE, BitIndex = 3, Chest = true},
            {Name = "Transport to Remembrance",                                              Address = 0x370D, BitIndex = 0, Chest = false},
            {Name = "(Post AG2: Peddler's Shop) Lexaeus Bonus: Sora Slot 1",                 Address = 0x370C, BitIndex = 1, Chest = false},
            {Name = "(Post AG2: Peddler's Shop) AS Lexaeus",                                 Address = 0x370C, BitIndex = 1, Chest = false},
            {Name = "(Post AG2: Peddler's Shop) Data Lexaeus",                               Address = 0x370C, BitIndex = 1, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) Marluxia Bonus: Sora Slot 1",         Address = 0x370C, BitIndex = 3, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) AS Marluxia",                         Address = 0x370C, BitIndex = 3, Chest = false},
            {Name = "(Post TR:Hall of the Cornerstone) Data Marluxia",                       Address = 0x370C, BitIndex = 3, Chest = false},
            {Name = "(Post OC2: Cave of the Dead Inner Chamber) Zexion Bonus: Sora Slot 1",  Address = 0x370C, BitIndex = 2, Chest = false},
            {Name = "(Post OC2: Cave of the Dead Inner Chamber) Zexion Bonus: Goofy Slot 1", Address = 0x370C, BitIndex = 2, Chest = false},
            {Name = "(Post OC2: Cave of the Dead Inner Chamber) AS Zexion",                  Address = 0x370C, BitIndex = 2, Chest = false},
            {Name = "(Post OC2: Cave of the Dead Inner Chamber) Data Zexion",                Address = 0x370C, BitIndex = 2, Chest = false},
            {Name = "(Post SP2: Central Computer Core) Larxene Bonus: Sora Slot 1",          Address = 0x370C, BitIndex = 4, Chest = false},
            {Name = "(Post SP2: Central Computer Core) AS Larxene",                          Address = 0x370C, BitIndex = 4, Chest = false},
            {Name = "(Post SP2: Central Computer Core) Data Larxene",                        Address = 0x370C, BitIndex = 4, Chest = false},
            {Name = "(Post HT2: Yuletide Hill) Vexen Bonus: Sora Slot 1",                    Address = 0x370C, BitIndex = 0, Chest = false},
            {Name = "(Post HT2: Yuletide Hill) AS Vexen",                                    Address = 0x370C, BitIndex = 0, Chest = false},
            {Name = "(Post HT2: Yuletide Hill) Data Vexen",                                  Address = 0x370C, BitIndex = 0, Chest = false},
            {Name = "(Post HB2: Restoration Site) Data Demyx",                               Address = 0x1D26, BitIndex = 5, Chest = false},
            {Name = "Garden of Assemblage Map",                                              Address = 0x23DF, BitIndex = 1, Chest = true},
            {Name = "GoA Lost Illusion",                                                     Address = 0x23DF, BitIndex = 2, Chest = true},
            {Name = "Proof of Nonexistence Location",                                        Address = 0x23DF, BitIndex = 3, Chest = true},
            {Name = "Kingdom Key Slot",                                                      Address = 0x1D27, BitIndex = 3, Chest = false},
            {Name = "Mages Staff Slot",                                                      Address = 0x1D27, BitIndex = 3, Chest = false},
            {Name = "Knight's Shield Slot",                                                  Address = 0x1D27, BitIndex = 3, Chest = false},
        },

        PL_Checks = {
            {Name = "(PL) Gorge Savannah Map",               Address = 0x23D9, BitIndex = 4, Chest = true},
            {Name = "(PL) Gorge Dark Gem",                   Address = 0x23CF, BitIndex = 0, Chest = true},
            {Name = "(PL) Gorge Mythril Stone",              Address = 0x23CF, BitIndex = 1, Chest = true},
            {Name = "(PL) Elephant Graveyard Frost Gem",     Address = 0x23CE, BitIndex = 5, Chest = true},
            {Name = "(PL) Elephant Graveyard Mythril Stone", Address = 0x23CE, BitIndex = 6, Chest = true},
            {Name = "(PL) Elephant Graveyard Bright Stone",  Address = 0x23CE, BitIndex = 7, Chest = true},
            {Name = "(PL) Elephant Graveyard AP Boost",      Address = 0x23DB, BitIndex = 3, Chest = true},
            {Name = "(PL) Elephant Graveyard Mythril Shard", Address = 0x23DB, BitIndex = 4, Chest = true},
            {Name = "(PL) Pride Rock Map",                   Address = 0x23D0, BitIndex = 3, Chest = true},
            {Name = "(PL) Pride Rock Mythril Stone",         Address = 0x23CD, BitIndex = 4, Chest = true},
            {Name = "(PL) Pride Rock Serenity Crystal",      Address = 0x23CD, BitIndex = 5, Chest = true},
            {Name = "(PL) Wildebeest Valley Energy Stone",   Address = 0x23CE, BitIndex = 0, Chest = true},
            {Name = "(PL) Wildebeest Valley AP Boost",       Address = 0x23CE, BitIndex = 1, Chest = true},
            {Name = "(PL) Wildebeest Valley Mythril Gem",    Address = 0x23CE, BitIndex = 2, Chest = true},
            {Name = "(PL) Wildebeest Valley Mythril Stone",  Address = 0x23CE, BitIndex = 3, Chest = true},
            {Name = "(PL) Wildebeest Valley Lucid Gem",      Address = 0x23CE, BitIndex = 4, Chest = true},
            {Name = "(PL) Wastelands Mythril Shard",         Address = 0x23CF, BitIndex = 2, Chest = true},
            {Name = "(PL) Wastelands Serenity Gem",          Address = 0x23CF, BitIndex = 3, Chest = true},
            {Name = "(PL) Wastelands Mythril Stone",         Address = 0x23CF, BitIndex = 4, Chest = true},
            {Name = "(PL) Jungle Serenity Gem",              Address = 0x23CF, BitIndex = 5, Chest = true},
            {Name = "(PL) Jungle Mythril Stone",             Address = 0x23CF, BitIndex = 6, Chest = true},
            {Name = "(PL) Jungle Serenity Crystal",          Address = 0x23CF, BitIndex = 7, Chest = true},
            {Name = "(PL) Oasis Map",                        Address = 0x23D0, BitIndex = 0, Chest = true},
            {Name = "(PL) Oasis Torn Pages",                 Address = 0x23D9, BitIndex = 5, Chest = true},
            {Name = "(PL) Oasis AP Boost",                   Address = 0x23D0, BitIndex = 1, Chest = true},
            {Name = "(PL) Circle of Life",                   Address = 0x1DD2, BitIndex = 1, Chest = false},
            {Name = "(PL) Hyenas 1 Bonus: Sora Slot 1",      Address = 0x370A, BitIndex = 1, Chest = false},
            {Name = "(PL) Hyenas 1 Bonus: Goofy Slot 1",     Address = 0x370A, BitIndex = 1, Chest = false},
            {Name = "(PL) Scar Bonus: Sora Slot 1",          Address = 0x3707, BitIndex = 5, Chest = false},
            {Name = "(PL) Scar Bonus: Donald Slot 1",        Address = 0x3707, BitIndex = 5, Chest = false},
            {Name = "(PL) Scar Fire Element",                Address = 0x1DD4, BitIndex = 7, Chest = false},
            {Name = "(PL2) Hyenas 2 Bonus: Sora Slot 1",     Address = 0x370A, BitIndex = 2, Chest = false},
            {Name = "(PL2) Hyenas 2 Bonus: Goofy Slot 1",    Address = 0x370A, BitIndex = 2, Chest = false},
            {Name = "(PL2) Groundshaker Bonus: Sora Slot 1", Address = 0x3707, BitIndex = 6, Chest = false},
            {Name = "(PL2) Groundshaker Bonus: Sora Slot 2", Address = 0x3707, BitIndex = 6, Chest = false},
        },

        TT_Checks = {
            {Name = "(STT) Twilight Town Map",                         Address = 0x1CD6, BitIndex = 3, Chest = false},
            {Name = "(STT) Munny Pouch Olette",                        Address = 0x1CD6, BitIndex = 5, Chest = false},
            {Name = "(STT) Station Dusks",                             Address = 0x370A, BitIndex = 6, Chest = false},
            {Name = "(STT) Station of Serenity Potion",                Address = 0x23CA, BitIndex = 1, Chest = true},
            {Name = "(STT) Station of Calling Potion",                 Address = 0x23D7, BitIndex = 1, Chest = true},
            {Name = "(STT) Twilight Thorn",                            Address = 0x3708, BitIndex = 1, Chest = false},
            {Name = "(STT) Axel 1",                                    Address = 0x370D, BitIndex = 1, Chest = false},
            {Name = "(STT) Junk Champion Belt",                        Address = 0x1CDC, BitIndex = 2, Chest = false},
            {Name = "(STT) Junk Medal",                                Address = 0x1CDC, BitIndex = 2, Chest = false},
            {Name = "(STT) The Struggle Trophy",                       Address = 0x1CDC, BitIndex = 2, Chest = false},
            {Name = "(STT) Central Station Potion 1",                  Address = 0x23D1, BitIndex = 5, Chest = true},
            {Name = "(STT) Central Station Hi-Potion",                 Address = 0x23D1, BitIndex = 6, Chest = true},
            {Name = "(STT) Central Station Potion 2",                  Address = 0x23D1, BitIndex = 7, Chest = true},
            {Name = "(STT) Sunset Terrace Ability Ring",               Address = 0x23D2, BitIndex = 3, Chest = true},
            {Name = "(STT) Sunset Terrace Hi-Potion",                  Address = 0x23D2, BitIndex = 4, Chest = true},
            {Name = "(STT) Sunset Terrace Potion 1",                   Address = 0x23D2, BitIndex = 5, Chest = true},
            {Name = "(STT) Sunset Terrace Potion 2",                   Address = 0x23D2, BitIndex = 6, Chest = true},
            {Name = "(STT) Mansion Foyer Hi-Potion",                   Address = 0x23D4, BitIndex = 2, Chest = true},
            {Name = "(STT) Mansion Foyer Potion 1",                    Address = 0x23D4, BitIndex = 3, Chest = true},
            {Name = "(STT) Mansion Foyer Potion 2",                    Address = 0x23D4, BitIndex = 4, Chest = true},
            {Name = "(STT) Mansion Dining Room Elven Bandanna",        Address = 0x23D5, BitIndex = 0, Chest = true},
            {Name = "(STT) Mansion Dining Room Potion",                Address = 0x23D5, BitIndex = 1, Chest = true},
            {Name = "(STT) Namine's Sketches",                         Address = 0x1CE0, BitIndex = 6, Chest = false},
            {Name = "(STT) Mansion Map",                               Address = 0x1CE0, BitIndex = 6, Chest = false},
            {Name = "(STT) Mansion Library Hi-Potion",                 Address = 0x23D5, BitIndex = 4, Chest = true},
            {Name = "(STT) Axel 2",                                    Address = 0x3708, BitIndex = 2, Chest = false},
            {Name = "(STT) Mansion Basement Corridor Hi-Potion",       Address = 0x23D6, BitIndex = 0, Chest = false},
            {Name = "(TT) Old Mansion Potion",                         Address = 0x23D4, BitIndex = 0, Chest = true},
            {Name = "(TT) Old Mansion Mythril Shard",                  Address = 0x23D4, BitIndex = 1, Chest = true},
            {Name = "(TT) The Woods Potion",                           Address = 0x23D3, BitIndex = 3, Chest = true},
            {Name = "(TT) The Woods Mythril Shard",                    Address = 0x23D3, BitIndex = 4, Chest = true},
            {Name = "(TT) The Woods Hi-Potion",                        Address = 0x23D3, BitIndex = 5, Chest = true},
            {Name = "(TT) Tram Common Hi-Potion",                      Address = 0x23D0, BitIndex = 5, Chest = true},
            {Name = "(TT) Tram Common AP Boost",                       Address = 0x23D0, BitIndex = 6, Chest = true},
            {Name = "(TT) Tram Common Tent",                           Address = 0x23D0, BitIndex = 7, Chest = true},
            {Name = "(TT) Tram Common Mythril Shard 1",                Address = 0x23D1, BitIndex = 0, Chest = true},
            {Name = "(TT) Tram Common Potion 1",                       Address = 0x23D1, BitIndex = 1, Chest = true},
            {Name = "(TT) Tram Common Mythril Shard 2",                Address = 0x23D1, BitIndex = 2, Chest = true},
            {Name = "(TT) Tram Common Potion 2",                       Address = 0x23D8, BitIndex = 5, Chest = true},
            {Name = "(TT) Station Plaza Secret Ansem Report 2",        Address = 0x1CE3, BitIndex = 3, Chest = false},
            {Name = "(TT) Munny Pouch Mickey",                         Address = 0x1CE3, BitIndex = 3, Chest = false},
            {Name = "(TT) Crystal Orb",                                Address = 0x1CE3, BitIndex = 3, Chest = false},
            {Name = "(TT) Central Station Tent",                       Address = 0x23D2, BitIndex = 0, Chest = true},
            {Name = "(TT) Central Station Hi-Potion",                  Address = 0x23D2, BitIndex = 1, Chest = true},
            {Name = "(TT) Central Station Mythril Shard",              Address = 0x23D2, BitIndex = 2, Chest = true},
            {Name = "(TT) The Tower Potion",                           Address = 0x23D6, BitIndex = 2, Chest = true},
            {Name = "(TT) The Tower Hi-Potion",                        Address = 0x23D6, BitIndex = 3, Chest = true},
            {Name = "(TT) The Tower Ether",                            Address = 0x23DB, BitIndex = 7, Chest = true},
            {Name = "(TT) Tower Entryway Ether",                       Address = 0x23D6, BitIndex = 4, Chest = true},
            {Name = "(TT) Tower Entryway Mythril Shard",               Address = 0x23D6, BitIndex = 5, Chest = true},
            {Name = "(TT) Sorcerer's Loft Tower Map",                  Address = 0x23D6, BitIndex = 6, Chest = true},
            {Name = "(TT) Tower Wardrobe Mythril Stone",               Address = 0x23D6, BitIndex = 7, Chest = true},
            {Name = "(TT) Star Seeker",                                Address = 0x1CE5, BitIndex = 2, Chest = false},
            {Name = "(TT) Valor Form",                                 Address = 0x1CE5, BitIndex = 2, Chest = false},
            {Name = "(TT2) Seifer's Trophy",                           Address = 0x1CE6, BitIndex = 4, Chest = false},
            {Name = "(TT2) Oathkeeper",                                Address = 0x1CE6, BitIndex = 7, Chest = false},
            {Name = "(TT2) Limit Form",                                Address = 0x1CE6, BitIndex = 7, Chest = false},
            {Name = "(TT3) Underground Concourse Mythril Gem",         Address = 0x23D8, BitIndex = 0, Chest = true},
            {Name = "(TT3) Underground Concourse Orichalcum",          Address = 0x23D8, BitIndex = 2, Chest = true},
            {Name = "(TT3) Underground Concourse AP Boost",            Address = 0x23D8, BitIndex = 1, Chest = true},
            {Name = "(TT3) Underground Concourse Mythril Crystal",     Address = 0x23D8, BitIndex = 3, Chest = true},
            {Name = "(TT3) Tunnelway Orichalcum",                      Address = 0x23D7, BitIndex = 6, Chest = true},
            {Name = "(TT3) Tunnelway Mythril Crystal",                 Address = 0x23D7, BitIndex = 7, Chest = true},
            {Name = "(TT3) Sunset Terrace Orichalcum+",                Address = 0x23D2, BitIndex = 7, Chest = true},
            {Name = "(TT3) Sunset Terrace Mythril Shard",              Address = 0x23D3, BitIndex = 0, Chest = true},
            {Name = "(TT3) Sunset Terrace Mythril Crystal",            Address = 0x23D3, BitIndex = 1, Chest = true},
            {Name = "(TT3) Sunset Terrace AP Boost",                   Address = 0x23D3, BitIndex = 2, Chest = true},
            {Name = "(TT3) Mansion Nobodies Bonus: Sora Slot 1",       Address = 0x370B, BitIndex = 0, Chest = false},
            {Name = "(TT3) Mansion Nobodies Bonus: Donald Slot 1",     Address = 0x370B, BitIndex = 0, Chest = false},
            {Name = "(TT3) Mansion Foyer Mythril Crystal",             Address = 0x23D4, BitIndex = 5, Chest = true},
            {Name = "(TT3) Mansion Foyer Mythril Stone",               Address = 0x23D4, BitIndex = 6, Chest = true},
            {Name = "(TT3) Mansion Foyer Serenity Crystal",            Address = 0x23D4, BitIndex = 7, Chest = true},
            {Name = "(TT3) Mansion Dining Room Mythril Crystal",       Address = 0x23D5, BitIndex = 2, Chest = true},
            {Name = "(TT3) Mansion Dining Room Mythril Stone",         Address = 0x23D5, BitIndex = 3, Chest = true},
            {Name = "(TT3) Mansion Library Orichalcum",                Address = 0x23D5, BitIndex = 5, Chest = true},
            {Name = "(TT3) Beam Secret Ansem Report 10",               Address = 0x1CE8, BitIndex = 3, Chest = false},
            {Name = "(TT3) Mansion Basement Corridor Ultimate Recipe", Address = 0x23D6, BitIndex = 1, Chest = true},
            {Name = "(TT3) Betwixt and Between",                       Address = 0x370B, BitIndex = 7, Chest = false},
            {Name = "(TT3) Betwixt and Between Bond of Flame",         Address = 0x1CE9, BitIndex = 1, Chest = false},
            {Name = "(Post TT3: Betwixt and Between) Data Axel",       Address = 0x1CEB, BitIndex = 4, Chest = false},
        },

        TWTNW_Checks = {
            {Name = "(TWTNW) Fragment Crossing Mythril Stone",              Address = 0x23CB, BitIndex = 4, Chest = true},
            {Name = "(TWTNW) Fragment Crossing Mythril Crystal",            Address = 0x23CB, BitIndex = 5, Chest = true},
            {Name = "(TWTNW) Fragment Crossing AP Boost",                   Address = 0x23CB, BitIndex = 6, Chest = true},
            {Name = "(TWTNW) Fragment Crossing Orichalcum",                 Address = 0x23CB, BitIndex = 7, Chest = true},
            {Name = "(TWTNW2) Roxas Bonus: Sora Slot 1",                    Address = 0x370C, BitIndex = 5, Chest = false},
            {Name = "(TWTNW2) Roxas Bonus: Sora Slot 2",                    Address = 0x370C, BitIndex = 5, Chest = false},
            {Name = "(TWTNW2) Roxas Secret Ansem Report 8",                 Address = 0x1ED1, BitIndex = 1, Chest = false},
            {Name = "(TWTNW2) Two Become One",                              Address = 0x1ED1, BitIndex = 1, Chest = false},
            {Name = "(TWTNW2) Memory's Skyscaper Mythril Crystal",          Address = 0x23CD, BitIndex = 3, Chest = true},
            {Name = "(TWTNW2) Memory's Skyscaper AP Boost",                 Address = 0x23DC, BitIndex = 0, Chest = true},
            {Name = "(TWTNW2) Memory's Skyscaper Mythril Stone",            Address = 0x23DC, BitIndex = 1, Chest = true},
            {Name = "(TWTNW2) The Brink of Despair Dark City Map",          Address = 0x23CA, BitIndex = 5, Chest = true},
            {Name = "(TWTNW2) The Brink of Despair Orichalcum+",            Address = 0x23DA, BitIndex = 2, Chest = true},
            {Name = "(TWTNW2) Nothing's Call Mythril Gem",                  Address = 0x23CC, BitIndex = 0, Chest = true},
            {Name = "(TWTNW2) Nothing's Call Orichalcum",                   Address = 0x23CC, BitIndex = 1, Chest = true},
            {Name = "(TWTNW2) Twilight's View Cosmic Belt",                 Address = 0x23CA, BitIndex = 6, Chest = true},
            {Name = "(TWTNW2) Xigbar Bonus: Sora Slot 1",                   Address = 0x3706, BitIndex = 7, Chest = false},
            {Name = "(TWTNW2) Xigbar Secret Ansem Report 3",                Address = 0x1ED2, BitIndex = 2, Chest = false},
            {Name = "(TWTNW2) Naught's Skyway Mythril Gem",                 Address = 0x23CC, BitIndex = 2, Chest = true},
            {Name = "(TWTNW2) Naught's Skyway Orichalcum",                  Address = 0x23CC, BitIndex = 3, Chest = true},
            {Name = "(TWTNW2) Naught's Skyway Mythril Crystal",             Address = 0x23CC, BitIndex = 4, Chest = true},
            {Name = "(TWTNW2) Oblivion",                                    Address = 0x1ED2, BitIndex = 4, Chest = false},
            {Name = "(TWTNW2) Castle That Never Was Map",                   Address = 0x1ED2, BitIndex = 4, Chest = false},
            {Name = "(TWTNW2) Luxord Bonus: Sora Slot 2",                   Address = 0x3707, BitIndex = 0, Chest = false},
            {Name = "(TWTNW2) Luxord Bonus: Sora Slot 1",                   Address = 0x3707, BitIndex = 0, Chest = false},
            {Name = "(TWTNW2) Luxord Secret Ansem Report 9",                Address = 0x1ED2, BitIndex = 7, Chest = false},
            {Name = "(TWTNW2) Saix Bonus: Sora Slot 1",                     Address = 0x3707, BitIndex = 1, Chest = false},
            {Name = "(TWTNW2) Saix Secret Ansem Report 12",                 Address = 0x1ED3, BitIndex = 2, Chest = false},
            {Name = "(TWTNW3) Secret Ansem Report 11 (Pre-Xemnas 1)",       Address = 0x1ED3, BitIndex = 6, Chest = false},
            {Name = "(TWTNW3) Ruin and Creation's Passage Mythril Stone",   Address = 0x23CC, BitIndex = 7, Chest = true},
            {Name = "(TWTNW3) Ruin and Creation's Passage AP Boost",        Address = 0x23CD, BitIndex = 0, Chest = true},
            {Name = "(TWTNW3) Ruin and Creation's Passage Mythril Crystal", Address = 0x23CD, BitIndex = 1, Chest = true},
            {Name = "(TWTNW3) Ruin and Creation's Passage Orichalcum",      Address = 0x23CD, BitIndex = 2, Chest = true},
            {Name = "(TWTNW3) Xemnas 1 Bonus: Sora Slot 1",                 Address = 0x3707, BitIndex = 2, Chest = false},
            {Name = "(TWTNW3) Xemnas 1 Bonus: Sora Slot 2",                 Address = 0x3707, BitIndex = 2, Chest = false},
            {Name = "(TWTNW3) Xemnas 1 Secret Ansem Report 13",             Address = 0x1ED4, BitIndex = 5, Chest = false},
            {Name = "Final Xemnas",                                         Address = 0x1ED8, BitIndex = 1, Chest = false},
            {Name = "(Post TWTNW3: The Altar of Naught) Data Xemnas",       Address = 0x1EDA, BitIndex = 2, Chest = false},
            {Name = "(Post LoD2: Summit) Data Xigbar",                      Address = 0x1ED9, BitIndex = 7, Chest = false},
            {Name = "(Post PL2: Peak) Data Saix",                           Address = 0x1EDA, BitIndex = 0, Chest = false},
            {Name = "(Post PR2: Treasure Heap) Data Luxord",                Address = 0x1EDA, BitIndex = 1, Chest = false},
            {Name = "(Post STT: Mansion Pod Room) Data Roxas",              Address = 0x1ED9, BitIndex = 6, Chest = false},
        },

        AT_Checks = {
            {Name = "(AT) Undersea Kingdom Map",     Address = 0x1DF4, BitIndex = 2, Chest = false},
            {Name = "(AT) Mysterious Abyss",         Address = 0x1DF5, BitIndex = 3, Chest = false},
            {Name = "(AT) Musical Blizzard Element", Address = 0x1DF4, BitIndex = 1, Chest = false},
            {Name = "(AT) Musical Orichalcum+",      Address = 0x1DF4, BitIndex = 1, Chest = false},
        },
    }
    return Worlds
end

function LocationDefs:FormLevels()

    ValorForm ={
        {Name = "Valor level 2", Address = 0x32F6, BitIndex = 2},
        {Name = "Valor level 3", Address = 0x32F6, BitIndex = 3},
        {Name = "Valor level 4", Address = 0x32F6, BitIndex = 4},
        {Name = "Valor level 5", Address = 0x32F6, BitIndex = 5},
        {Name = "Valor level 6", Address = 0x32F6, BitIndex = 6},
        {Name = "Valor level 7", Address = 0x32F6, BitIndex = 7},
    }
    WisdomForm = {
        {Name = "Wisdom level 2", Address = 0x332E, BitIndex = 2},
        {Name = "Wisdom level 3", Address = 0x332E, BitIndex = 3},
        {Name = "Wisdom level 4", Address = 0x332E, BitIndex = 4},
        {Name = "Wisdom level 5", Address = 0x332E, BitIndex = 5},
        {Name = "Wisdom level 6", Address = 0x332E, BitIndex = 6},
        {Name = "Wisdom level 7", Address = 0x332E, BitIndex = 7},
    }
    LimitForm = {
        {Name = "Limit level 2", Address = 0x3366, BitIndex = 2},
        {Name = "Limit level 3", Address = 0x3366, BitIndex = 3},
        {Name = "Limit level 4", Address = 0x3366, BitIndex = 4},
        {Name = "Limit level 5", Address = 0x3366, BitIndex = 5},
        {Name = "Limit level 6", Address = 0x3366, BitIndex = 6},
        {Name = "Limit level 7", Address = 0x3366, BitIndex = 7},
    }
    MasterForm = {
        {Name = "Master level 2", Address = 0x339E, BitIndex = 2},
        {Name = "Master level 3", Address = 0x339E, BitIndex = 3},
        {Name = "Master level 4", Address = 0x339E, BitIndex = 4},
        {Name = "Master level 5", Address = 0x339E, BitIndex = 5},
        {Name = "Master level 6", Address = 0x339E, BitIndex = 6},
        {Name = "Master level 7", Address = 0x339E, BitIndex = 7},
    }
    FinalForm = {
        {Name = "Final level 2", Address = 0x33D6, BitIndex = 2},
        {Name = "Final level 3", Address = 0x33D6, BitIndex = 3},
        {Name = "Final level 4", Address = 0x33D6, BitIndex = 4},
        {Name = "Final level 5", Address = 0x33D6, BitIndex = 5},
        {Name = "Final level 6", Address = 0x33D6, BitIndex = 6},
        {Name = "Final level 7", Address = 0x33D6, BitIndex = 7},
    }
    SummonLevels = {
        {Name = "Summon level 2", Address = 0x3526, BitIndex = 2},
        {Name = "Summon level 3", Address = 0x3526, BitIndex = 3},
        {Name = "Summon level 4", Address = 0x3526, BitIndex = 4},
        {Name = "Summon level 5", Address = 0x3526, BitIndex = 5},
        {Name = "Summon level 6", Address = 0x3526, BitIndex = 6},
        {Name = "Summon level 7", Address = 0x3526, BitIndex = 7},
    }
end

function LocationDefs:WeaponSlots()

    WeaponAbilities = {
        {Name = "Adamant Shield", Address = 0x35E6, BitIndex = 1},
        {Name = "Akashic Record", Address = 0x35ED, BitIndex = 1},
        {Name = "Chain Gear", Address = 0x35E7, BitIndex = 1},
        {Name = "Dream Cloud", Address = 0x35EA, BitIndex = 1},
        {Name = "Falling Star", Address = 0x35E9, BitIndex = 1},
        {Name = "Frozen Pride 2", Address = 0x36A2, BitIndex = 1},
        {Name = "Genji Shield", Address = 0x35EC, BitIndex = 1},
        {Name = "Knight Defender", Address = 0x35EB, BitIndex = 1},
        {Name = "Majestic Mushroom", Address = 0x36A5, BitIndex = 1},
        {Name = "Majestic Mushroom 2", Address = 0x36A6, BitIndex = 1},
        {Name = "Nobody Guard", Address = 0x35EE, BitIndex = 1},
        {Name = "Ogre Shield", Address = 0x35E8, BitIndex = 1},
        {Name = "Save The King 2", Address = 0x3693, BitIndex = 1},
        {Name = "Ultimate Mushroom", Address = 0x36A7, BitIndex = 1},
        {Name = "Comet Staff", Address = 0x35F2, BitIndex = 1},
        {Name = "Hammer Staff", Address = 0x35EF, BitIndex = 1},
        {Name = "Lords Broom", Address = 0x35F3, BitIndex = 1},
        {Name = "Meteor Staff", Address = 0x35F1, BitIndex = 1},
        {Name = "Nobody Lance", Address = 0x35F6, BitIndex = 1},
        {Name = "Precious Mushroom", Address = 0x369E, BitIndex = 1},
        {Name = "Precious Mushroom 2", Address = 0x369F, BitIndex = 1},
        {Name = "Premium Mushroom", Address = 0x36A0, BitIndex = 1},
        {Name = "Rising Dragon", Address = 0x35F5, BitIndex = 1},
        {Name = "Save The Queen 2", Address = 0x3692, BitIndex = 1},
        {Name = "Shamans Relic", Address = 0x35F7, BitIndex = 1},
        {Name = "Victory Bell", Address = 0x35F0, BitIndex = 1},
        {Name = "Wisdom Wand", Address = 0x35F4, BitIndex = 1},
        {Name = "Centurion 2", Address = 0x369B, BitIndex = 1},
        {Name = "Oathkeeper Slot", Address = 0x35A2, BitIndex = 1},
        {Name = "Oblivion Slot", Address = 0x35A3, BitIndex = 1},
        {Name = "Star Seeker Slot", Address = 0x367B, BitIndex = 1},
        {Name = "Hidden Dragon Slot", Address = 0x367C, BitIndex = 1},
        {Name = "Heros Crest Slot", Address = 0x367F, BitIndex = 1},
        {Name = "Monochrome Slot", Address = 0x3680, BitIndex = 1},
        {Name = "Follow the Wind Slot", Address = 0x3681, BitIndex = 1},
        {Name = "Circle of Life Slot", Address = 0x3682, BitIndex = 1},
        {Name = "Photon Debugger Slot", Address = 0x3683, BitIndex = 1},
        {Name = "Gull Wing Slot", Address = 0x3684, BitIndex = 1},
        {Name = "Rumbling Rose Slot", Address = 0x3685, BitIndex = 1},
        {Name = "Guardian Soul Slot", Address = 0x3686, BitIndex = 1},
        {Name = "Wishing Lamp Slot", Address = 0x3687, BitIndex = 1},
        {Name = "Decisive Pumpkin Slot", Address = 0x3688, BitIndex = 1},
        {Name = "Sleeping Lion Slot", Address = 0x3689, BitIndex = 1},
        {Name = "Sweet Memories Slot", Address = 0x368A, BitIndex = 1},
        {Name = "Mysterious Abyss Slot", Address = 0x368B, BitIndex = 1},
        {Name = "Two Become One Slot", Address = 0x3698, BitIndex = 1},
        {Name = "Fatal Crest Slot", Address = 0x368C, BitIndex = 1},
        {Name = "Bond of Flame Slot", Address = 0x368D, BitIndex = 1},
        {Name = "Fenrir Slot", Address = 0x368E, BitIndex = 1},
        {Name = "Ultima Weapon Slot", Address = 0x368F, BitIndex = 1},
        {Name = "Winners Proof Slot", Address = 0x3699, BitIndex = 1},
        {Name = "Pureblood Slot", Address = 0x35BF, BitIndex = 1},
    }

    FormWeaponAbilities = {
        --Form Keyblade Abilities
        {Name = "FAKE Slot", Address = 0x36C0, BitIndex = 1},
        {Name = "Detection Saber Slot", Address = 0x36C0, BitIndex = 6},
        {Name = "Edge of Ultima Slot", Address = 0x36C0, BitIndex = 4},
    }
 end

 function LocationDefs:TornPageLocks()
    PoohProgress = {
        {Name = "Torn Page 1", Address = 0x1DB7, BitIndex = 4}, -- --Scenario_1_start
        {Name = "Torn Page 2", Address = 0x1DB7, BitIndex = 7}, -- --Scenario_2_start
        {Name = "Torn Page 3", Address = 0x1DB8, BitIndex = 2}, -- --Scenario_3_start
        {Name = "Torn Page 4", Address = 0x1DB8, BitIndex = 4}, -- --Scenario_4_start
        {Name = "Torn Page 5", Address = 0x1DB8, BitIndex = 7}, -- --Scenario_5_start
    }
 end
return LocationDefs